#Análise Descritiva RJ

In [ ]:
#Carregando os pacotes

In [ ]:
import pandas as pd  # processamento de bancos de dados
import numpy as np  # processamento numérico
import matplotlib.pyplot as plt  # geração de gráficos
import seaborn as sns  # geração de gráficos alternativos

# Configuração de gráficos no notebook
%matplotlib inline
plt.rcParams["figure.figsize"] = [10, 5]
plt.style.use("fivethirtyeight")
%config InlineBackend.figure_format = 'retina'

# Configurações de fonte e matemática
from matplotlib import rc
rc('font', **{'family': 'sans-serif', 'sans-serif': ['DejaVu Sans'], 'size': 10})
rc('mathtext', **{'default': 'regular'})

In [ ]:
df = pd.read_csv("dadosRJ_tube_2015_2025.csv",sep=",")

In [ ]:
df.shape

(25630, 35)

In [ ]:
df.columns

Index(['nu_ano', 'cs_sexo', 'cs_raca', 'raiox_tora', 'agravalcoo',
       'agravdiabe', 'agravdoenc', 'bacilosc_e', 'cultura_es', 'dt_inic_tr',
       'bacilosc_2', 'bacilosc_4', 'tratsup_at', 'dt_encerra', 'pop_liber',
       'pop_rua', 'pop_imig', 'benef_gov', 'agravdroga', 'agravtabac',
       'ano_base', 'cura', 'pop', 'front', 'tempo_diag_trat_14', 'dt_cul',
       'dt_bac2', 'dt_bac4', 'eleg_eta2', 'eleg_eta3', 'ano_inc_trat',
       'ano_encerra', 'escola_faixa', 'contato_5_15', 'faixa_etaria'],
      dtype='object')

In [ ]:
df['pop'].describe()

count    2.562700e+04
mean     4.212033e+06
std      2.683237e+06
min      1.020700e+04
25%      8.081610e+05
50%      6.211223e+06
75%      6.211223e+06
max      6.211223e+06
Name: pop, dtype: float64

In [ ]:
import pandas as pd

# Criação da variável categórica com pd.cut
df['pop_grupo'] = pd.cut(
    df['pop'],
    bins=[-float('inf'),300000, 1000000, float('inf')],
    labels=['< 300000', '300000 a 1000000', '>1000000']
)

In [ ]:
df['pop_grupo'].value_counts(dropna=False)

pop_grupo
>1000000            16458
300000 a 1000000     7473
< 300000             1696
NaN                     3
Name: count, dtype: int64

In [ ]:
df['ano_encerra'].value_counts(dropna=False)

ano_encerra
2023    4472
2022    3803
2021    3047
2019    2974
2020    2892
2024    2832
2018    2539
2016    1211
2017    1052
2015     788
2025      20
Name: count, dtype: int64

In [ ]:
df['ano_enc_grupo'] = pd.cut(
    df['ano_encerra'],
    bins=[2014, 2022, float('inf')],
    labels=['2015-2022', '2023-2024']
)

In [ ]:
df['ano_enc_grupo'].value_counts(dropna=False)

ano_enc_grupo
2015-2022    18306
2023-2024     7324
Name: count, dtype: int64

In [ ]:
df['ano_inc_trat'].value_counts(dropna=False)

ano_inc_trat
2023    4953
2022    4180
2021    3319
2019    3049
2018    2859
2020    2816
2017    2376
2015    2008
2024      55
2016      14
2025       1
Name: count, dtype: int64

In [ ]:
df['ano_inctr_grupo'] = pd.cut(
    df['ano_inc_trat'],
    bins=[2014, 2022, float('inf')],
    labels=['2015-2022', '2023-2024']
)

In [ ]:
df['ano_inctr_grupo'].value_counts(dropna=False)

ano_inctr_grupo
2015-2022    20621
2023-2024     5009
Name: count, dtype: int64

In [ ]:
df.columns

Index(['nu_ano', 'cs_sexo', 'cs_raca', 'raiox_tora', 'agravalcoo',
       'agravdiabe', 'agravdoenc', 'bacilosc_e', 'cultura_es', 'dt_inic_tr',
       'bacilosc_2', 'bacilosc_4', 'tratsup_at', 'dt_encerra', 'pop_liber',
       'pop_rua', 'pop_imig', 'benef_gov', 'agravdroga', 'agravtabac',
       'ano_base', 'cura', 'pop', 'front', 'tempo_diag_trat_14', 'dt_cul',
       'dt_bac2', 'dt_bac4', 'eleg_eta2', 'eleg_eta3', 'ano_inc_trat',
       'ano_encerra', 'escola_faixa', 'contato_5_15', 'faixa_etaria',
       'pop_grupo', 'ano_enc_grupo', 'ano_inctr_grupo'],
      dtype='object')

###Atualizando categorias das variaveis

In [ ]:
df['cs_raca'].value_counts(dropna=False)

cs_raca
4.0    11698
1.0     6514
2.0     5766
9.0     1299
3.0      216
NaN       98
5.0       39
Name: count, dtype: int64

In [ ]:
import numpy as np

df['cs_raca'] = df['cs_raca'].replace(9, np.nan)

In [ ]:
df['raiox_tora'].value_counts(dropna=False)

raiox_tora
1.0    21723
4.0     3204
2.0      604
NaN       78
0.0       21
Name: count, dtype: int64

In [ ]:
import numpy as np

df['raiox_tora'] = df['raiox_tora'].replace(0, np.nan)

In [ ]:
df['bacilosc_2'].value_counts(dropna=False)

bacilosc_2
3.0    12124
2.0     6740
NaN     4587
1.0     1490
0.0      689
Name: count, dtype: int64

In [ ]:
import numpy as np

df['bacilosc_2'] = df['bacilosc_2'].replace(0, np.nan)

In [ ]:
df['bacilosc_4'].value_counts(dropna=False)

bacilosc_4
3.0    13799
NaN     6057
2.0     4665
0.0      865
1.0      244
Name: count, dtype: int64

In [ ]:
import numpy as np

df['bacilosc_4'] = df['bacilosc_4'].replace(0, np.nan)

In [ ]:
df['tratsup_at'].value_counts(dropna=False)

tratsup_at
1.0    13248
2.0     9271
NaN     2408
0.0      548
9.0      155
Name: count, dtype: int64

In [ ]:
import numpy as np

df['tratsup_at'] = df['tratsup_at'].replace(0, np.nan)

In [ ]:
import numpy as np

df['tratsup_at'] = df['tratsup_at'].replace(9, np.nan)

###Etapa1

In [ ]:
df.shape

(25630, 38)

##Proporção dos preditores e desfecho

In [ ]:
#Lista de variáveis com o desfecho
lista_variaveis = [ 'cura', 'cs_sexo', 'faixa_etaria','cs_raca', 'escola_faixa', 'contato_5_15',
                   'pop_rua','pop_liber','pop_imig','benef_gov', 'agravtabac','agravalcoo','agravdroga',
                    'agravdiabe', 'agravdoenc', 'tempo_diag_trat_14','raiox_tora', 'bacilosc_e',
                    'front', 'ano_inctr_grupo','ano_enc_grupo','pop_grupo'
                  ]

In [ ]:
for coluna in lista_variaveis:
    print(f"\n==== Variável: {coluna} ====")

    # Frequência absoluta
    freq_abs = df[coluna].value_counts(dropna=False)

    # Frequência relativa (em %)
    freq_rel = df[coluna].value_counts(normalize=True, dropna=False) * 100

    # Juntar em um único DataFrame para visualização
    tabela = pd.DataFrame({
        'Frequência Absoluta': freq_abs,
        'Frequência Relativa (%)': freq_rel.round(2)
    })

    print(tabela)

==== Variável: cura ====
      Frequência Absoluta  Frequência Relativa (%)
cura
1                   20798                    81.15
0                    4832                    18.85

==== Variável: cs_sexo ====
         Frequência Absoluta  Frequência Relativa (%)
cs_sexo
1.0                    17635                    68.81
0.0                     7993                    31.19
NaN                        2                     0.01

==== Variável: faixa_etaria ====
              Frequência Absoluta  Frequência Relativa (%)
faixa_etaria
1.0                         12637                    49.31
2.0                          7317                    28.55
3.0                          3394                    13.24
0.0                          2260                     8.82
NaN                            22                     0.09

==== Variável: cs_raca ====
         Frequência Absoluta  Frequência Relativa (%)
cs_raca
4.0                    11698                    45.64
1.0                     6514                    25.42
2.0                     5766                    22.50
NaN                     1397                     5.45
3.0                      216                     0.84
5.0                       39                     0.15

==== Variável: escola_faixa ====
              Frequência Absoluta  Frequência Relativa (%)
escola_faixa
0.0                         15697                    61.24
1.0                          5648                    22.04
NaN                          4056                    15.83
10.0                          229                     0.89

==== Variável: contato_5_15 ====
              Frequência Absoluta  Frequência Relativa (%)
contato_5_15
0.0                         23284                    90.85
1.0                          1977                     7.71
2.0                           224                     0.87
NaN                           145                     0.57

==== Variável: pop_rua ====
         Frequência Absoluta  Frequência Relativa (%)
pop_rua
0.0                    23981                    93.57
NaN                      896                     3.50
1.0                      753                     2.94

==== Variável: pop_liber ====
           Frequência Absoluta  Frequência Relativa (%)
pop_liber
0.0                      23224                    90.61
1.0                       1807                     7.05
NaN                        599                     2.34

==== Variável: pop_imig ====
          Frequência Absoluta  Frequência Relativa (%)
pop_imig
0.0                     24535                    95.73
NaN                      1000                     3.90
1.0                        95                     0.37

==== Variável: benef_gov ====
           Frequência Absoluta  Frequência Relativa (%)
benef_gov
0.0                      19845                    77.43
NaN                       3344                    13.05
1.0                       2441                     9.52

==== Variável: agravtabac ====
            Frequência Absoluta  Frequência Relativa (%)
agravtabac
0.0                       17083                    66.65
1.0                        6991                    27.28
NaN                        1556                     6.07

==== Variável: agravalcoo ====
            Frequência Absoluta  Frequência Relativa (%)
agravalcoo
0.0                       20306                    79.23
1.0                        3852                    15.03
NaN                        1472                     5.74

==== Variável: agravdroga ====
            Frequência Absoluta  Frequência Relativa (%)
agravdroga
0.0                       19669                    76.74
1.0                        4346                    16.96
NaN                        1615                     6.30

==== Variável: agravdiabe ====
            Frequência Absoluta  Frequência Relativa (%)
agravdiabe
0.0                       21789                    85.01
1.0                        2394                     9.34
NaN                        1447                     5.65

==== Variável: agravdoenc ====
            Frequência Absoluta  Frequência Relativa (%)
agravdoenc
0.0                       23358                    91.14
NaN                        1571                     6.13
1.0                         701                     2.74

==== Variável: tempo_diag_trat_14 ====
                    Frequência Absoluta  Frequência Relativa (%)
tempo_diag_trat_14
0.0                               24570                    95.86
1.0                                1060                     4.14

==== Variável: raiox_tora ====
            Frequência Absoluta  Frequência Relativa (%)
raiox_tora
1.0                       21723                    84.76
4.0                        3204                    12.50
2.0                         604                     2.36
NaN                          78                     0.30
0.0                          21                     0.08

==== Variável: bacilosc_e ====
            Frequência Absoluta  Frequência Relativa (%)
bacilosc_e
1.0                       16120                    62.90
3.0                        7214                    28.15
2.0                        2296                     8.96

==== Variável: front ====
       Frequência Absoluta  Frequência Relativa (%)
front
0                    25630                    100.0

==== Variável: ano_inctr_grupo ====
                 Frequência Absoluta  Frequência Relativa (%)
ano_inctr_grupo
2015-2022                      20621                    80.46
2023-2024                       5009                    19.54

==== Variável: ano_enc_grupo ====
               Frequência Absoluta  Frequência Relativa (%)
ano_enc_grupo
2015-2022                    18306                    71.42
2023-2024                     7324                    28.58

==== Variável: pop_grupo ====
                  Frequência Absoluta  Frequência Relativa (%)
pop_grupo
>1000000                        16458                    64.21
300000 a 1000000                 7473                    29.16
< 300000                         1696                     6.62
NaN                                 3                     0.01

In [ ]:
# Listas
lista_variavel_desfecho = ['cura']

lista_preditores = [ 'cs_sexo', 'faixa_etaria','cs_raca', 'escola_faixa', 'contato_5_15',
                   'pop_rua','pop_liber','pop_imig','benef_gov', 'agravtabac','agravalcoo','agravdroga',
                    'agravdiabe', 'agravdoenc', 'tempo_diag_trat_14','raiox_tora', 'bacilosc_e',
                    'front', 'ano_inctr_grupo','ano_enc_grupo','pop_grupo'
                  ]

# Dicionário para salvar os resultados
resultados = {}

desfecho = lista_variavel_desfecho[0]

for var in lista_preditores:

    # Versão temporária sem NA (convertendo para object)
    temp_var = df[var].astype('object').where(df[var].notna(), 'NA')

    # Contagem
    tabela = (
        pd.DataFrame({var: temp_var, desfecho: df[desfecho]})
        .groupby([var, desfecho], dropna=False)
        .size()
        .rename("Frequência Absoluta")
        .reset_index()
    )

    # Frequência relativa
    tabela["Frequência Relativa (%)"] = (
        tabela["Frequência Absoluta"]
        / tabela.groupby(var)["Frequência Absoluta"].transform("sum")
        * 100
    ).round(2)

    resultados[var] = tabela

# Exibir
for var, tabela in resultados.items():
    print(f"\n==== Variável: {var} ====")
    print(tabela)

==== Variável: cs_sexo ====
  cs_sexo  cura  Frequência Absoluta  Frequência Relativa (%)
0     0.0     0                 1006                    12.59
1     0.0     1                 6987                    87.41
2     1.0     0                 3826                    21.70
3     1.0     1                13809                    78.30
4      NA     1                    2                   100.00

==== Variável: faixa_etaria ====
  faixa_etaria  cura  Frequência Absoluta  Frequência Relativa (%)
0          0.0     0                  383                    16.95
1          0.0     1                 1877                    83.05
2          1.0     0                 2901                    22.96
3          1.0     1                 9736                    77.04
4          2.0     0                 1128                    15.42
5          2.0     1                 6189                    84.58
6          3.0     0                  417                    12.29
7          3.0     1                 2977                    87.71
8           NA     0                    3                    13.64
9           NA     1                   19                    86.36

==== Variável: cs_raca ====
   cs_raca  cura  Frequência Absoluta  Frequência Relativa (%)
0      1.0     0                  845                    12.97
1      1.0     1                 5669                    87.03
2      2.0     0                 1326                    23.00
3      2.0     1                 4440                    77.00
4      3.0     0                   40                    18.52
5      3.0     1                  176                    81.48
6      4.0     0                 2300                    19.66
7      4.0     1                 9398                    80.34
8      5.0     0                    7                    17.95
9      5.0     1                   32                    82.05
10      NA     0                  314                    22.48
11      NA     1                 1083                    77.52

==== Variável: escola_faixa ====
  escola_faixa  cura  Frequência Absoluta  Frequência Relativa (%)
0          0.0     0                 3286                    20.93
1          0.0     1                12411                    79.07
2          1.0     0                  551                     9.76
3          1.0     1                 5097                    90.24
4         10.0     0                   49                    21.40
5         10.0     1                  180                    78.60
6           NA     0                  946                    23.32
7           NA     1                 3110                    76.68

==== Variável: contato_5_15 ====
  contato_5_15  cura  Frequência Absoluta  Frequência Relativa (%)
0          0.0     0                 4366                    18.75
1          0.0     1                18918                    81.25
2          1.0     0                  366                    18.51
3          1.0     1                 1611                    81.49
4          2.0     0                   53                    23.66
5          2.0     1                  171                    76.34
6           NA     0                   47                    32.41
7           NA     1                   98                    67.59

==== Variável: pop_rua ====
  pop_rua  cura  Frequência Absoluta  Frequência Relativa (%)
0     0.0     0                 4223                    17.61
1     0.0     1                19758                    82.39
2     1.0     0                  400                    53.12
3     1.0     1                  353                    46.88
4      NA     0                  209                    23.33
5      NA     1                  687                    76.67

==== Variável: pop_liber ====
  pop_liber  cura  Frequência Absoluta  Frequência Relativa (%)
0       0.0     0                 4324                    18.62
1       0.0     1                18900                    81.38
2       1.0     0                  383                    21.20
3       1.0     1                 1424                    78.80
4        NA     0                  125                    20.87
5        NA     1                  474                    79.13

==== Variável: pop_imig ====
  pop_imig  cura  Frequência Absoluta  Frequência Relativa (%)
0      0.0     0                 4569                    18.62
1      0.0     1                19966                    81.38
2      1.0     0                   23                    24.21
3      1.0     1                   72                    75.79
4       NA     0                  240                    24.00
5       NA     1                  760                    76.00

==== Variável: benef_gov ====
  benef_gov  cura  Frequência Absoluta  Frequência Relativa (%)
0       0.0     0                 3676                    18.52
1       0.0     1                16169                    81.48
2       1.0     0                  406                    16.63
3       1.0     1                 2035                    83.37
4        NA     0                  750                    22.43
5        NA     1                 2594                    77.57

==== Variável: agravtabac ====
  agravtabac  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 2445                    14.31
1        0.0     1                14638                    85.69
2        1.0     0                 1944                    27.81
3        1.0     1                 5047                    72.19
4         NA     0                  443                    28.47
5         NA     1                 1113                    71.53

==== Variável: agravalcoo ====
  agravalcoo  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 3348                    16.49
1        0.0     1                16958                    83.51
2        1.0     0                 1067                    27.70
3        1.0     1                 2785                    72.30
4         NA     0                  417                    28.33
5         NA     1                 1055                    71.67

==== Variável: agravdroga ====
  agravdroga  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 2777                    14.12
1        0.0     1                16892                    85.88
2        1.0     0                 1608                    37.00
3        1.0     1                 2738                    63.00
4         NA     0                  447                    27.68
5         NA     1                 1168                    72.32

==== Variável: agravdiabe ====
  agravdiabe  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 4147                    19.03
1        0.0     1                17642                    80.97
2        1.0     0                  269                    11.24
3        1.0     1                 2125                    88.76
4         NA     0                  416                    28.75
5         NA     1                 1031                    71.25

==== Variável: agravdoenc ====
  agravdoenc  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 4210                    18.02
1        0.0     1                19148                    81.98
2        1.0     0                  173                    24.68
3        1.0     1                  528                    75.32
4         NA     0                  449                    28.58
5         NA     1                 1122                    71.42

==== Variável: tempo_diag_trat_14 ====
   tempo_diag_trat_14  cura  Frequência Absoluta  Frequência Relativa (%)
0                 0.0     0                 4552                    18.53
1                 0.0     1                20018                    81.47
2                 1.0     0                  280                    26.42
3                 1.0     1                  780                    73.58

==== Variável: raiox_tora ====
  raiox_tora  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                    5                    23.81
1        0.0     1                   16                    76.19
2        1.0     0                 3925                    18.07
3        1.0     1                17798                    81.93
4        2.0     0                   75                    12.42
5        2.0     1                  529                    87.58
6        4.0     0                  807                    25.19
7        4.0     1                 2397                    74.81
8         NA     0                   20                    25.64
9         NA     1                   58                    74.36

==== Variável: bacilosc_e ====
   bacilosc_e  cura  Frequência Absoluta  Frequência Relativa (%)
0         1.0     0                 2981                    18.49
1         1.0     1                13139                    81.51
2         2.0     0                  359                    15.64
3         2.0     1                 1937                    84.36
4         3.0     0                 1492                    20.68
5         3.0     1                 5722                    79.32

==== Variável: front ====
   front  cura  Frequência Absoluta  Frequência Relativa (%)
0      0     0                 4832                    18.85
1      0     1                20798                    81.15

==== Variável: ano_inctr_grupo ====
  ano_inctr_grupo  cura  Frequência Absoluta  Frequência Relativa (%)
0       2015-2022     0                 3903                    18.93
1       2015-2022     1                16718                    81.07
2       2023-2024     0                  929                    18.55
3       2023-2024     1                 4080                    81.45

==== Variável: ano_enc_grupo ====
  ano_enc_grupo  cura  Frequência Absoluta  Frequência Relativa (%)
0     2015-2022     0                 3594                    19.63
1     2015-2022     1                14712                    80.37
2     2023-2024     0                 1238                    16.90
3     2023-2024     1                 6086                    83.10

==== Variável: pop_grupo ====
          pop_grupo  cura  Frequência Absoluta  Frequência Relativa (%)
0  300000 a 1000000     0                 1717                    22.98
1  300000 a 1000000     1                 5756                    77.02
2          < 300000     0                  313                    18.46
3          < 300000     1                 1383                    81.54
4          >1000000     0                 2802                    17.03
5          >1000000     1                13656                    82.97
6                NA     1                    3                   100.00

###Etapas 2 e 3

In [ ]:
df2 = df.loc[df['eleg_eta2'] == 1].copy()
df3 = df.loc[df['eleg_eta3'] == 1].copy()

###Etapa 2

##Proporção dos preditores e desfecho

In [ ]:
df2.shape

(24537, 38)

In [ ]:
#Lista de variáveis com o desfecho
lista_variaveis = [ 'cura', 'cs_sexo', 'faixa_etaria','cs_raca', 'escola_faixa', 'contato_5_15',
                   'pop_rua','pop_liber','pop_imig','benef_gov', 'agravtabac','agravalcoo','agravdroga',
                    'agravdiabe', 'agravdoenc', 'tempo_diag_trat_14','raiox_tora', 'cultura_es','bacilosc_e',
                    'bacilosc_2', 'tratsup_at','front', 'ano_inctr_grupo','ano_enc_grupo','pop_grupo'
                  ]

In [ ]:
for coluna in lista_variaveis:
    print(f"\n==== Variável: {coluna} ====")

    # Frequência absoluta
    freq_abs = df2[coluna].value_counts(dropna=False)

    # Frequência relativa (em %)
    freq_rel = df2[coluna].value_counts(normalize=True, dropna=False) * 100

    # Juntar em um único DataFrame para visualização
    tabela = pd.DataFrame({
        'Frequência Absoluta': freq_abs,
        'Frequência Relativa (%)': freq_rel.round(2)
    })

    print(tabela)

==== Variável: cura ====
      Frequência Absoluta  Frequência Relativa (%)
cura
1                   20537                     83.7
0                    4000                     16.3

==== Variável: cs_sexo ====
         Frequência Absoluta  Frequência Relativa (%)
cs_sexo
1.0                    16822                    68.56
0.0                     7713                    31.43
NaN                        2                     0.01

==== Variável: faixa_etaria ====
              Frequência Absoluta  Frequência Relativa (%)
faixa_etaria
1.0                         12139                    49.47
2.0                          7012                    28.58
3.0                          3184                    12.98
0.0                          2181                     8.89
NaN                            21                     0.09

==== Variável: cs_raca ====
         Frequência Absoluta  Frequência Relativa (%)
cs_raca
4.0                    11217                    45.71
1.0                     6276                    25.58
2.0                     5482                    22.34
NaN                     1317                     5.37
3.0                      207                     0.84
5.0                       38                     0.15

==== Variável: escola_faixa ====
              Frequência Absoluta  Frequência Relativa (%)
escola_faixa
0.0                         15033                    61.27
1.0                          5513                    22.47
NaN                          3774                    15.38
10.0                          217                     0.88

==== Variável: contato_5_15 ====
              Frequência Absoluta  Frequência Relativa (%)
contato_5_15
0.0                         22315                    90.94
1.0                          1889                     7.70
2.0                           210                     0.86
NaN                           123                     0.50

==== Variável: pop_rua ====
         Frequência Absoluta  Frequência Relativa (%)
pop_rua
0.0                    23056                    93.96
NaN                      842                     3.43
1.0                      639                     2.60

==== Variável: pop_liber ====
           Frequência Absoluta  Frequência Relativa (%)
pop_liber
0.0                      22217                    90.54
1.0                       1756                     7.16
NaN                        564                     2.30

==== Variável: pop_imig ====
          Frequência Absoluta  Frequência Relativa (%)
pop_imig
0.0                     23503                    95.79
NaN                       947                     3.86
1.0                        87                     0.35

==== Variável: benef_gov ====
           Frequência Absoluta  Frequência Relativa (%)
benef_gov
0.0                      19069                    77.72
NaN                       3107                    12.66
1.0                       2361                     9.62

==== Variável: agravtabac ====
            Frequência Absoluta  Frequência Relativa (%)
agravtabac
0.0                       16481                    67.17
1.0                        6615                    26.96
NaN                        1441                     5.87

==== Variável: agravalcoo ====
            Frequência Absoluta  Frequência Relativa (%)
agravalcoo
0.0                       19546                    79.66
1.0                        3634                    14.81
NaN                        1357                     5.53

==== Variável: agravdroga ====
            Frequência Absoluta  Frequência Relativa (%)
agravdroga
0.0                       18967                    77.30
1.0                        4069                    16.58
NaN                        1501                     6.12

==== Variável: agravdiabe ====
            Frequência Absoluta  Frequência Relativa (%)
agravdiabe
0.0                       20917                    85.25
1.0                        2281                     9.30
NaN                        1339                     5.46

==== Variável: agravdoenc ====
            Frequência Absoluta  Frequência Relativa (%)
agravdoenc
0.0                       22424                    91.39
NaN                        1448                     5.90
1.0                         665                     2.71

==== Variável: tempo_diag_trat_14 ====
                    Frequência Absoluta  Frequência Relativa (%)
tempo_diag_trat_14
0.0                               23559                    96.01
1.0                                 978                     3.99

==== Variável: raiox_tora ====
            Frequência Absoluta  Frequência Relativa (%)
raiox_tora
1.0                       20849                    84.97
4.0                        3009                    12.26
2.0                         588                     2.40
NaN                          73                     0.30
0.0                          18                     0.07

==== Variável: cultura_es ====
            Frequência Absoluta  Frequência Relativa (%)
cultura_es
4.0                       11859                    48.33
1.0                       10731                    43.73
2.0                        1791                     7.30
3.0                         156                     0.64

==== Variável: bacilosc_e ====
            Frequência Absoluta  Frequência Relativa (%)
bacilosc_e
1.0                       15439                    62.92
3.0                        6916                    28.19
2.0                        2182                     8.89

==== Variável: bacilosc_2 ====
            Frequência Absoluta  Frequência Relativa (%)
bacilosc_2
3.0                       11746                    47.87
2.0                        6698                    27.30
NaN                        4625                    18.85
1.0                        1468                     5.98

==== Variável: tratsup_at ====
            Frequência Absoluta  Frequência Relativa (%)
tratsup_at
1.0                       12822                    52.26
2.0                        8858                    36.10
NaN                        2213                     9.02
0.0                         508                     2.07
9.0                         136                     0.55

==== Variável: front ====
       Frequência Absoluta  Frequência Relativa (%)
front
0                    24537                    100.0

==== Variável: ano_inctr_grupo ====
                 Frequência Absoluta  Frequência Relativa (%)
ano_inctr_grupo
2015-2022                      19751                    80.49
2023-2024                       4786                    19.51

==== Variável: ano_enc_grupo ====
               Frequência Absoluta  Frequência Relativa (%)
ano_enc_grupo
2015-2022                    17448                    71.11
2023-2024                     7089                    28.89

==== Variável: pop_grupo ====
                  Frequência Absoluta  Frequência Relativa (%)
pop_grupo
>1000000                        15816                    64.46
300000 a 1000000                 7124                    29.03
< 300000                         1594                     6.50
NaN                                 3                     0.01

In [ ]:
# Listas
lista_variavel_desfecho = ['cura']

lista_preditores = [ 'cs_sexo', 'faixa_etaria','cs_raca', 'escola_faixa', 'contato_5_15',
                   'pop_rua','pop_liber','pop_imig','benef_gov', 'agravtabac','agravalcoo','agravdroga',
                    'agravdiabe', 'agravdoenc', 'tempo_diag_trat_14','raiox_tora', 'cultura_es','bacilosc_e',
                    'bacilosc_2', 'tratsup_at','front', 'ano_inctr_grupo','ano_enc_grupo','pop_grupo']

# Dicionário para salvar os resultados
resultados = {}

desfecho = lista_variavel_desfecho[0]

for var in lista_preditores:

    # Versão temporária sem NA (convertendo para object)
    temp_var = df2[var].astype('object').where(df2[var].notna(), 'NA')

    # Contagem
    tabela = (
        pd.DataFrame({var: temp_var, desfecho: df2[desfecho]})
        .groupby([var, desfecho], dropna=False)
        .size()
        .rename("Frequência Absoluta")
        .reset_index()
    )

    # Frequência relativa
    tabela["Frequência Relativa (%)"] = (
        tabela["Frequência Absoluta"]
        / tabela.groupby(var)["Frequência Absoluta"].transform("sum")
        * 100
    ).round(2)

    resultados[var] = tabela

# Exibir
for var, tabela in resultados.items():
    print(f"\n==== Variável: {var} ====")
    print(tabela)

==== Variável: cs_sexo ====
  cs_sexo  cura  Frequência Absoluta  Frequência Relativa (%)
0     0.0     0                  815                    10.57
1     0.0     1                 6898                    89.43
2     1.0     0                 3185                    18.93
3     1.0     1                13637                    81.07
4      NA     1                    2                   100.00

==== Variável: faixa_etaria ====
  faixa_etaria  cura  Frequência Absoluta  Frequência Relativa (%)
0          0.0     0                  325                    14.90
1          0.0     1                 1856                    85.10
2          1.0     0                 2534                    20.87
3          1.0     1                 9605                    79.13
4          2.0     0                  907                    12.93
5          2.0     1                 6105                    87.07
6          3.0     0                  232                     7.29
7          3.0     1                 2952                    92.71
8           NA     0                    2                     9.52
9           NA     1                   19                    90.48

==== Variável: cs_raca ====
   cs_raca  cura  Frequência Absoluta  Frequência Relativa (%)
0      1.0     0                  671                    10.69
1      1.0     1                 5605                    89.31
2      2.0     0                 1098                    20.03
3      2.0     1                 4384                    79.97
4      3.0     0                   32                    15.46
5      3.0     1                  175                    84.54
6      4.0     0                 1939                    17.29
7      4.0     1                 9278                    82.71
8      5.0     0                    6                    15.79
9      5.0     1                   32                    84.21
10      NA     0                  254                    19.29
11      NA     1                 1063                    80.71

==== Variável: escola_faixa ====
  escola_faixa  cura  Frequência Absoluta  Frequência Relativa (%)
0          0.0     0                 2758                    18.35
1          0.0     1                12275                    81.65
2          1.0     0                  467                     8.47
3          1.0     1                 5046                    91.53
4         10.0     0                   39                    17.97
5         10.0     1                  178                    82.03
6           NA     0                  736                    19.50
7           NA     1                 3038                    80.50

==== Variável: contato_5_15 ====
  contato_5_15  cura  Frequência Absoluta  Frequência Relativa (%)
0          0.0     0                 3630                    16.27
1          0.0     1                18685                    83.73
2          1.0     0                  298                    15.78
3          1.0     1                 1591                    84.22
4          2.0     0                   43                    20.48
5          2.0     1                  167                    79.52
6           NA     0                   29                    23.58
7           NA     1                   94                    76.42

==== Variável: pop_rua ====
  pop_rua  cura  Frequência Absoluta  Frequência Relativa (%)
0     0.0     0                 3539                    15.35
1     0.0     1                19517                    84.65
2     1.0     0                  294                    46.01
3     1.0     1                  345                    53.99
4      NA     0                  167                    19.83
5      NA     1                  675                    80.17

==== Variável: pop_liber ====
  pop_liber  cura  Frequência Absoluta  Frequência Relativa (%)
0       0.0     0                 3555                    16.00
1       0.0     1                18662                    84.00
2       1.0     0                  349                    19.87
3       1.0     1                 1407                    80.13
4        NA     0                   96                    17.02
5        NA     1                  468                    82.98

==== Variável: pop_imig ====
  pop_imig  cura  Frequência Absoluta  Frequência Relativa (%)
0      0.0     0                 3786                    16.11
1      0.0     1                19717                    83.89
2      1.0     0                   17                    19.54
3      1.0     1                   70                    80.46
4       NA     0                  197                    20.80
5       NA     1                  750                    79.20

==== Variável: benef_gov ====
  benef_gov  cura  Frequência Absoluta  Frequência Relativa (%)
0       0.0     0                 3087                    16.19
1       0.0     1                15982                    83.81
2       1.0     0                  345                    14.61
3       1.0     1                 2016                    85.39
4        NA     0                  568                    18.28
5        NA     1                 2539                    81.72

==== Variável: agravtabac ====
  agravtabac  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 2024                    12.28
1        0.0     1                14457                    87.72
2        1.0     0                 1626                    24.58
3        1.0     1                 4989                    75.42
4         NA     0                  350                    24.29
5         NA     1                 1091                    75.71

==== Variável: agravalcoo ====
  agravalcoo  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 2786                    14.25
1        0.0     1                16760                    85.75
2        1.0     0                  884                    24.33
3        1.0     1                 2750                    75.67
4         NA     0                  330                    24.32
5         NA     1                 1027                    75.68

==== Variável: agravdroga ====
  agravdroga  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 2288                    12.06
1        0.0     1                16679                    87.94
2        1.0     0                 1359                    33.40
3        1.0     1                 2710                    66.60
4         NA     0                  353                    23.52
5         NA     1                 1148                    76.48

==== Variável: agravdiabe ====
  agravdiabe  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 3489                    16.68
1        0.0     1                17428                    83.32
2        1.0     0                  181                     7.94
3        1.0     1                 2100                    92.06
4         NA     0                  330                    24.65
5         NA     1                 1009                    75.35

==== Variável: agravdoenc ====
  agravdoenc  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 3504                    15.63
1        0.0     1                18920                    84.37
2        1.0     0                  143                    21.50
3        1.0     1                  522                    78.50
4         NA     0                  353                    24.38
5         NA     1                 1095                    75.62

==== Variável: tempo_diag_trat_14 ====
   tempo_diag_trat_14  cura  Frequência Absoluta  Frequência Relativa (%)
0                 0.0     0                 3781                    16.05
1                 0.0     1                19778                    83.95
2                 1.0     0                  219                    22.39
3                 1.0     1                  759                    77.61

==== Variável: raiox_tora ====
  raiox_tora  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                    4                    22.22
1        0.0     1                   14                    77.78
2        1.0     0                 3268                    15.67
3        1.0     1                17581                    84.33
4        2.0     0                   63                    10.71
5        2.0     1                  525                    89.29
6        4.0     0                  649                    21.57
7        4.0     1                 2360                    78.43
8         NA     0                   16                    21.92
9         NA     1                   57                    78.08

==== Variável: cultura_es ====
   cultura_es  cura  Frequência Absoluta  Frequência Relativa (%)
0         1.0     0                 1615                    15.05
1         1.0     1                 9116                    84.95
2         2.0     0                  173                     9.66
3         2.0     1                 1618                    90.34
4         3.0     0                   15                     9.62
5         3.0     1                  141                    90.38
6         4.0     0                 2197                    18.53
7         4.0     1                 9662                    81.47

==== Variável: bacilosc_e ====
   bacilosc_e  cura  Frequência Absoluta  Frequência Relativa (%)
0         1.0     0                 2462                    15.95
1         1.0     1                12977                    84.05
2         2.0     0                  273                    12.51
3         2.0     1                 1909                    87.49
4         3.0     0                 1265                    18.29
5         3.0     1                 5651                    81.71

==== Variável: bacilosc_2 ====
  bacilosc_2  cura  Frequência Absoluta  Frequência Relativa (%)
0        1.0     0                  196                    13.35
1        1.0     1                 1272                    86.65
2        2.0     0                  554                     8.27
3        2.0     1                 6144                    91.73
4        3.0     0                 2007                    17.09
5        3.0     1                 9739                    82.91
6         NA     0                 1243                    26.88
7         NA     1                 3382                    73.12

==== Variável: tratsup_at ====
  tratsup_at  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                  112                    22.05
1        0.0     1                  396                    77.95
2        1.0     0                 1571                    12.25
3        1.0     1                11251                    87.75
4        2.0     0                 1726                    19.49
5        2.0     1                 7132                    80.51
6        9.0     0                   30                    22.06
7        9.0     1                  106                    77.94
8         NA     0                  561                    25.35
9         NA     1                 1652                    74.65

==== Variável: front ====
   front  cura  Frequência Absoluta  Frequência Relativa (%)
0      0     0                 4000                     16.3
1      0     1                20537                     83.7

==== Variável: ano_inctr_grupo ====
  ano_inctr_grupo  cura  Frequência Absoluta  Frequência Relativa (%)
0       2015-2022     0                 3249                    16.45
1       2015-2022     1                16502                    83.55
2       2023-2024     0                  751                    15.69
3       2023-2024     1                 4035                    84.31

==== Variável: ano_enc_grupo ====
  ano_enc_grupo  cura  Frequência Absoluta  Frequência Relativa (%)
0     2015-2022     0                 2953                    16.92
1     2015-2022     1                14495                    83.08
2     2023-2024     0                 1047                    14.77
3     2023-2024     1                 6042                    85.23

==== Variável: pop_grupo ====
          pop_grupo  cura  Frequência Absoluta  Frequência Relativa (%)
0  300000 a 1000000     0                 1445                    20.28
1  300000 a 1000000     1                 5679                    79.72
2          < 300000     0                  234                    14.68
3          < 300000     1                 1360                    85.32
4          >1000000     0                 2321                    14.68
5          >1000000     1                13495                    85.32
6                NA     1                    3                   100.00

###Etapa 3

In [ ]:
df3.shape

(23121, 38)

##Proporção dos preditores e desfecho

In [ ]:
#Lista de variáveis com o desfecho
lista_variaveis = ['cura', 'cs_sexo', 'faixa_etaria','cs_raca', 'escola_faixa', 'contato_5_15',
                   'pop_rua','pop_liber','pop_imig','benef_gov', 'agravtabac','agravalcoo','agravdroga',
                    'agravdiabe', 'agravdoenc', 'tempo_diag_trat_14','raiox_tora', 'cultura_es','bacilosc_e',
                    'bacilosc_2', 'bacilosc_4','tratsup_at','front', 'ano_inctr_grupo','ano_enc_grupo','pop_grupo']

In [ ]:
for coluna in lista_variaveis:
    print(f"\n==== Variável: {coluna} ====")

    # Frequência absoluta
    freq_abs = df3[coluna].value_counts(dropna=False)

    # Frequência relativa (em %)
    freq_rel = df3[coluna].value_counts(normalize=True, dropna=False) * 100

    # Juntar em um único DataFrame para visualização
    tabela = pd.DataFrame({
        'Frequência Absoluta': freq_abs,
        'Frequência Relativa (%)': freq_rel.round(2)
    })

    print(tabela)

==== Variável: cura ====
      Frequência Absoluta  Frequência Relativa (%)
cura
1                   20395                    88.21
0                    2726                    11.79

==== Variável: cs_sexo ====
         Frequência Absoluta  Frequência Relativa (%)
cs_sexo
1.0                    15715                    67.97
0.0                     7404                    32.02
NaN                        2                     0.01

==== Variável: faixa_etaria ====
              Frequência Absoluta  Frequência Relativa (%)
faixa_etaria
1.0                         11288                    48.82
2.0                          6670                    28.85
3.0                          3084                    13.34
0.0                          2059                     8.91
NaN                            20                     0.09

==== Variável: cs_raca ====
         Frequência Absoluta  Frequência Relativa (%)
cs_raca
4.0                    10542                    45.59
1.0                     6029                    26.08
2.0                     5074                    21.95
NaN                     1241                     5.37
3.0                      198                     0.86
5.0                       37                     0.16

==== Variável: escola_faixa ====
              Frequência Absoluta  Frequência Relativa (%)
escola_faixa
0.0                         14031                    60.69
1.0                          5353                    23.15
NaN                          3529                    15.26
10.0                          208                     0.90

==== Variável: contato_5_15 ====
              Frequência Absoluta  Frequência Relativa (%)
contato_5_15
0.0                         21012                    90.88
1.0                          1801                     7.79
2.0                           199                     0.86
NaN                           109                     0.47

==== Variável: pop_rua ====
         Frequência Absoluta  Frequência Relativa (%)
pop_rua
0.0                    21813                    94.34
NaN                      798                     3.45
1.0                      510                     2.21

==== Variável: pop_liber ====
           Frequência Absoluta  Frequência Relativa (%)
pop_liber
0.0                      20909                    90.43
1.0                       1683                     7.28
NaN                        529                     2.29

==== Variável: pop_imig ====
          Frequência Absoluta  Frequência Relativa (%)
pop_imig
0.0                     22147                    95.79
NaN                       894                     3.87
1.0                        80                     0.35

==== Variável: benef_gov ====
           Frequência Absoluta  Frequência Relativa (%)
benef_gov
0.0                      17989                    77.80
NaN                       2915                    12.61
1.0                       2217                     9.59

==== Variável: agravtabac ====
            Frequência Absoluta  Frequência Relativa (%)
agravtabac
0.0                       15745                    68.10
1.0                        6017                    26.02
NaN                        1359                     5.88

==== Variável: agravalcoo ====
            Frequência Absoluta  Frequência Relativa (%)
agravalcoo
0.0                       18560                    80.27
1.0                        3282                    14.19
NaN                        1279                     5.53

==== Variável: agravdroga ====
            Frequência Absoluta  Frequência Relativa (%)
agravdroga
0.0                       18142                    78.47
1.0                        3563                    15.41
NaN                        1416                     6.12

==== Variável: agravdiabe ====
            Frequência Absoluta  Frequência Relativa (%)
agravdiabe
0.0                       19646                    84.97
1.0                        2208                     9.55
NaN                        1267                     5.48

==== Variável: agravdoenc ====
            Frequência Absoluta  Frequência Relativa (%)
agravdoenc
0.0                       21145                    91.45
NaN                        1367                     5.91
1.0                         609                     2.63

==== Variável: tempo_diag_trat_14 ====
                    Frequência Absoluta  Frequência Relativa (%)
tempo_diag_trat_14
0.0                               22239                    96.19
1.0                                 882                     3.81

==== Variável: raiox_tora ====
            Frequência Absoluta  Frequência Relativa (%)
raiox_tora
1.0                       19707                    85.23
4.0                        2767                    11.97
2.0                         562                     2.43
NaN                          69                     0.30
0.0                          16                     0.07

==== Variável: cultura_es ====
            Frequência Absoluta  Frequência Relativa (%)
cultura_es
4.0                       11026                    47.69
1.0                       10219                    44.20
2.0                        1728                     7.47
3.0                         148                     0.64

==== Variável: bacilosc_e ====
            Frequência Absoluta  Frequência Relativa (%)
bacilosc_e
1.0                       14555                    62.95
3.0                        6493                    28.08
2.0                        2073                     8.97

==== Variável: bacilosc_2 ====
            Frequência Absoluta  Frequência Relativa (%)
bacilosc_2
3.0                       11072                    47.89
2.0                        6555                    28.35
NaN                        4085                    17.67
1.0                        1409                     6.09

==== Variável: bacilosc_4 ====
            Frequência Absoluta  Frequência Relativa (%)
bacilosc_4
3.0                       13031                    56.36
NaN                        5250                    22.71
2.0                        4606                    19.92
1.0                         234                     1.01

==== Variável: tratsup_at ====
            Frequência Absoluta  Frequência Relativa (%)
tratsup_at
1.0                       12300                    53.20
2.0                        8204                    35.48
NaN                        2028                     8.77
0.0                         466                     2.02
9.0                         123                     0.53

==== Variável: front ====
       Frequência Absoluta  Frequência Relativa (%)
front
0                    23121                    100.0

==== Variável: ano_inctr_grupo ====
                 Frequência Absoluta  Frequência Relativa (%)
ano_inctr_grupo
2015-2022                      18627                    80.56
2023-2024                       4494                    19.44

==== Variável: ano_enc_grupo ====
               Frequência Absoluta  Frequência Relativa (%)
ano_enc_grupo
2015-2022                    16389                    70.88
2023-2024                     6732                    29.12

==== Variável: pop_grupo ====
                  Frequência Absoluta  Frequência Relativa (%)
pop_grupo
>1000000                        15109                    65.35
300000 a 1000000                 6510                    28.16
< 300000                         1499                     6.48
NaN                                 3                     0.01

In [ ]:
# Listas
lista_variavel_desfecho = ['cura']

lista_preditores = ['cs_sexo', 'faixa_etaria','cs_raca', 'escola_faixa', 'contato_5_15',
                   'pop_rua','pop_liber','pop_imig','benef_gov', 'agravtabac','agravalcoo','agravdroga',
                    'agravdiabe', 'agravdoenc', 'tempo_diag_trat_14','raiox_tora', 'cultura_es','bacilosc_e',
                    'bacilosc_2', 'bacilosc_4','tratsup_at','front', 'ano_inctr_grupo','ano_enc_grupo','pop_grupo']

# Dicionário para salvar os resultados
resultados = {}

desfecho = lista_variavel_desfecho[0]

for var in lista_preditores:

    # Versão temporária sem NA (convertendo para object)
    temp_var = df3[var].astype('object').where(df3[var].notna(), 'NA')

    # Contagem
    tabela = (
        pd.DataFrame({var: temp_var, desfecho: df3[desfecho]})
        .groupby([var, desfecho], dropna=False)
        .size()
        .rename("Frequência Absoluta")
        .reset_index()
    )

    # Frequência relativa
    tabela["Frequência Relativa (%)"] = (
        tabela["Frequência Absoluta"]
        / tabela.groupby(var)["Frequência Absoluta"].transform("sum")
        * 100
    ).round(2)

    resultados[var] = tabela

# Exibir
for var, tabela in resultados.items():
    print(f"\n==== Variável: {var} ====")
    print(tabela)

==== Variável: cs_sexo ====
  cs_sexo  cura  Frequência Absoluta  Frequência Relativa (%)
0     0.0     0                  550                     7.43
1     0.0     1                 6854                    92.57
2     1.0     0                 2176                    13.85
3     1.0     1                13539                    86.15
4      NA     1                    2                   100.00

==== Variável: faixa_etaria ====
  faixa_etaria  cura  Frequência Absoluta  Frequência Relativa (%)
0          0.0     0                  215                    10.44
1          0.0     1                 1844                    89.56
2          1.0     0                 1763                    15.62
3          1.0     1                 9525                    84.38
4          2.0     0                  607                     9.10
5          2.0     1                 6063                    90.90
6          3.0     0                  140                     4.54
7          3.0     1                 2944                    95.46
8           NA     0                    1                     5.00
9           NA     1                   19                    95.00

==== Variável: cs_raca ====
   cs_raca  cura  Frequência Absoluta  Frequência Relativa (%)
0      1.0     0                  459                     7.61
1      1.0     1                 5570                    92.39
2      2.0     0                  723                    14.25
3      2.0     1                 4351                    85.75
4      3.0     0                   23                    11.62
5      3.0     1                  175                    88.38
6      4.0     0                 1329                    12.61
7      4.0     1                 9213                    87.39
8      5.0     0                    5                    13.51
9      5.0     1                   32                    86.49
10      NA     0                  187                    15.07
11      NA     1                 1054                    84.93

==== Variável: escola_faixa ====
  escola_faixa  cura  Frequência Absoluta  Frequência Relativa (%)
0          0.0     0                 1851                    13.19
1          0.0     1                12180                    86.81
2          1.0     0                  330                     6.16
3          1.0     1                 5023                    93.84
4         10.0     0                   30                    14.42
5         10.0     1                  178                    85.58
6           NA     0                  515                    14.59
7           NA     1                 3014                    85.41

==== Variável: contato_5_15 ====
  contato_5_15  cura  Frequência Absoluta  Frequência Relativa (%)
0          0.0     0                 2458                    11.70
1          0.0     1                18554                    88.30
2          1.0     0                  217                    12.05
3          1.0     1                 1584                    87.95
4          2.0     0                   35                    17.59
5          2.0     1                  164                    82.41
6           NA     0                   16                    14.68
7           NA     1                   93                    85.32

==== Variável: pop_rua ====
  pop_rua  cura  Frequência Absoluta  Frequência Relativa (%)
0     0.0     0                 2433                    11.15
1     0.0     1                19380                    88.85
2     1.0     0                  167                    32.75
3     1.0     1                  343                    67.25
4      NA     0                  126                    15.79
5      NA     1                  672                    84.21

==== Variável: pop_liber ====
  pop_liber  cura  Frequência Absoluta  Frequência Relativa (%)
0       0.0     0                 2370                    11.33
1       0.0     1                18539                    88.67
2       1.0     0                  292                    17.35
3       1.0     1                 1391                    82.65
4        NA     0                   64                    12.10
5        NA     1                  465                    87.90

==== Variável: pop_imig ====
  pop_imig  cura  Frequência Absoluta  Frequência Relativa (%)
0      0.0     0                 2567                    11.59
1      0.0     1                19580                    88.41
2      1.0     0                   11                    13.75
3      1.0     1                   69                    86.25
4       NA     0                  148                    16.55
5       NA     1                  746                    83.45

==== Variável: benef_gov ====
  benef_gov  cura  Frequência Absoluta  Frequência Relativa (%)
0       0.0     0                 2116                    11.76
1       0.0     1                15873                    88.24
2       1.0     0                  214                     9.65
3       1.0     1                 2003                    90.35
4        NA     0                  396                    13.58
5        NA     1                 2519                    86.42

==== Variável: agravtabac ====
  agravtabac  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 1374                     8.73
1        0.0     1                14371                    91.27
2        1.0     0                 1074                    17.85
3        1.0     1                 4943                    82.15
4         NA     0                  278                    20.46
5         NA     1                 1081                    79.54

==== Variável: agravalcoo ====
  agravalcoo  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 1911                    10.30
1        0.0     1                16649                    89.70
2        1.0     0                  554                    16.88
3        1.0     1                 2728                    83.12
4         NA     0                  261                    20.41
5         NA     1                 1018                    79.59

==== Variável: agravdroga ====
  agravdroga  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 1568                     8.64
1        0.0     1                16574                    91.36
2        1.0     0                  881                    24.73
3        1.0     1                 2682                    75.27
4         NA     0                  277                    19.56
5         NA     1                 1139                    80.44

==== Variável: agravdiabe ====
  agravdiabe  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 2343                    11.93
1        0.0     1                17303                    88.07
2        1.0     0                  120                     5.43
3        1.0     1                 2088                    94.57
4         NA     0                  263                    20.76
5         NA     1                 1004                    79.24

==== Variável: agravdoenc ====
  agravdoenc  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 2355                    11.14
1        0.0     1                18790                    88.86
2        1.0     0                   93                    15.27
3        1.0     1                  516                    84.73
4         NA     0                  278                    20.34
5         NA     1                 1089                    79.66

==== Variável: tempo_diag_trat_14 ====
   tempo_diag_trat_14  cura  Frequência Absoluta  Frequência Relativa (%)
0                 0.0     0                 2592                    11.66
1                 0.0     1                19647                    88.34
2                 1.0     0                  134                    15.19
3                 1.0     1                  748                    84.81

==== Variável: raiox_tora ====
  raiox_tora  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                    2                    12.50
1        0.0     1                   14                    87.50
2        1.0     0                 2246                    11.40
3        1.0     1                17461                    88.60
4        2.0     0                   39                     6.94
5        2.0     1                  523                    93.06
6        4.0     0                  427                    15.43
7        4.0     1                 2340                    84.57
8         NA     0                   12                    17.39
9         NA     1                   57                    82.61

==== Variável: cultura_es ====
   cultura_es  cura  Frequência Absoluta  Frequência Relativa (%)
0         1.0     0                 1148                    11.23
1         1.0     1                 9071                    88.77
2         2.0     0                  129                     7.47
3         2.0     1                 1599                    92.53
4         3.0     0                    9                     6.08
5         3.0     1                  139                    93.92
6         4.0     0                 1440                    13.06
7         4.0     1                 9586                    86.94

==== Variável: bacilosc_e ====
   bacilosc_e  cura  Frequência Absoluta  Frequência Relativa (%)
0         1.0     0                 1669                    11.47
1         1.0     1                12886                    88.53
2         2.0     0                  178                     8.59
3         2.0     1                 1895                    91.41
4         3.0     0                  879                    13.54
5         3.0     1                 5614                    86.46

==== Variável: bacilosc_2 ====
  bacilosc_2  cura  Frequência Absoluta  Frequência Relativa (%)
0        1.0     0                  147                    10.43
1        1.0     1                 1262                    89.57
2        2.0     0                  434                     6.62
3        2.0     1                 6121                    93.38
4        3.0     0                 1401                    12.65
5        3.0     1                 9671                    87.35
6         NA     0                  744                    18.21
7         NA     1                 3341                    81.79

==== Variável: bacilosc_4 ====
  bacilosc_4  cura  Frequência Absoluta  Frequência Relativa (%)
0        1.0     0                   24                    10.26
1        1.0     1                  210                    89.74
2        2.0     0                  224                     4.86
3        2.0     1                 4382                    95.14
4        3.0     0                 1344                    10.31
5        3.0     1                11687                    89.69
6         NA     0                 1134                    21.60
7         NA     1                 4116                    78.40

==== Variável: tratsup_at ====
  tratsup_at  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                   75                    16.09
1        0.0     1                  391                    83.91
2        1.0     0                 1125                     9.15
3        1.0     1                11175                    90.85
4        2.0     0                 1116                    13.60
5        2.0     1                 7088                    86.40
6        9.0     0                   17                    13.82
7        9.0     1                  106                    86.18
8         NA     0                  393                    19.38
9         NA     1                 1635                    80.62

==== Variável: front ====
   front  cura  Frequência Absoluta  Frequência Relativa (%)
0      0     0                 2726                    11.79
1      0     1                20395                    88.21

==== Variável: ano_inctr_grupo ====
  ano_inctr_grupo  cura  Frequência Absoluta  Frequência Relativa (%)
0       2015-2022     0                 2240                    12.03
1       2015-2022     1                16387                    87.97
2       2023-2024     0                  486                    10.81
3       2023-2024     1                 4008                    89.19

==== Variável: ano_enc_grupo ====
  ano_enc_grupo  cura  Frequência Absoluta  Frequência Relativa (%)
0     2015-2022     0                 1998                    12.19
1     2015-2022     1                14391                    87.81
2     2023-2024     0                  728                    10.81
3     2023-2024     1                 6004                    89.19

==== Variável: pop_grupo ====
          pop_grupo  cura  Frequência Absoluta  Frequência Relativa (%)
0  300000 a 1000000     0                  867                    13.32
1  300000 a 1000000     1                 5643                    86.68
2          < 300000     0                  151                    10.07
3          < 300000     1                 1348                    89.93
4          >1000000     0                 1708                    11.30
5          >1000000     1                13401                    88.70
6                NA     1                    3                   100.00

#Análise Descritiva RJ

In [202]:
#Carregando os pacotes

In [203]:
import pandas as pd  # processamento de bancos de dados
import numpy as np  # processamento numérico
import matplotlib.pyplot as plt  # geração de gráficos
import seaborn as sns  # geração de gráficos alternativos

# Configuração de gráficos no notebook
%matplotlib inline
plt.rcParams["figure.figsize"] = [10, 5]
plt.style.use("fivethirtyeight")
%config InlineBackend.figure_format = 'retina'

# Configurações de fonte e matemática
from matplotlib import rc
rc('font', **{'family': 'sans-serif', 'sans-serif': ['DejaVu Sans'], 'size': 10})
rc('mathtext', **{'default': 'regular'})

###Etapa1

In [204]:
df = pd.read_csv("dfrj1.csv",sep=",")

In [205]:
df.shape

(25630, 26)

In [206]:
df.columns

Index(['nu_ano', 'cs_sexo', 'cs_raca', 'sg_uf', 'raiox_tora', 'agravalcoo',
       'agravdiabe', 'agravdoenc', 'bacilosc_e', 'pop_liber', 'pop_rua',
       'pop_imig', 'benef_gov', 'agravdroga', 'agravtabac', 'ano_base', 'cura',
       'pop', 'front', 'tempo_diag_trat_14', 'dt_cul', 'ano_inc_trat',
       'ano_encerra', 'escola_faixa', 'contato_5_15', 'faixa_etaria'],
      dtype='object')

In [207]:
df['pop'].describe()

count    2.562700e+04
mean     4.212033e+06
std      2.683237e+06
min      1.020700e+04
25%      8.081610e+05
50%      6.211223e+06
75%      6.211223e+06
max      6.211223e+06
Name: pop, dtype: float64

In [208]:
import pandas as pd

# Criação da variável categórica com pd.cut
df['pop_grupo'] = pd.cut(
    df['pop'],
    bins=[-float('inf'),300000, 1000000, float('inf')],
    labels=['< 300000', '300000 a 1000000', '>1000000']
)

In [209]:
df['pop_grupo'].value_counts(dropna=False)

pop_grupo
>1000000            16458
300000 a 1000000     7473
< 300000             1696
NaN                     3
Name: count, dtype: int64

In [210]:
df['ano_encerra'].value_counts(dropna=False)

ano_encerra
2023    4472
2022    3803
2021    3047
2019    2974
2020    2892
2024    2832
2018    2539
2016    1211
2017    1052
2015     788
2025      20
Name: count, dtype: int64

In [211]:
df['ano_enc_grupo'] = pd.cut(
    df['ano_encerra'],
    bins=[2014, 2022, float('inf')],
    labels=['2015-2022', '2023-2024']
)

In [212]:
df['ano_enc_grupo'].value_counts(dropna=False)

ano_enc_grupo
2015-2022    18306
2023-2024     7324
Name: count, dtype: int64

In [213]:
df['ano_inc_trat'].value_counts(dropna=False)

ano_inc_trat
2023    4953
2022    4180
2021    3319
2019    3049
2018    2859
2020    2816
2017    2376
2015    2008
2024      55
2016      14
2025       1
Name: count, dtype: int64

In [214]:
df['ano_inctr_grupo'] = pd.cut(
    df['ano_inc_trat'],
    bins=[2014, 2022, float('inf')],
    labels=['2015-2022', '2023-2024']
)

In [215]:
df['ano_inctr_grupo'].value_counts(dropna=False)

ano_inctr_grupo
2015-2022    20621
2023-2024     5009
Name: count, dtype: int64

In [216]:
df.columns

Index(['nu_ano', 'cs_sexo', 'cs_raca', 'sg_uf', 'raiox_tora', 'agravalcoo',
       'agravdiabe', 'agravdoenc', 'bacilosc_e', 'pop_liber', 'pop_rua',
       'pop_imig', 'benef_gov', 'agravdroga', 'agravtabac', 'ano_base', 'cura',
       'pop', 'front', 'tempo_diag_trat_14', 'dt_cul', 'ano_inc_trat',
       'ano_encerra', 'escola_faixa', 'contato_5_15', 'faixa_etaria',
       'pop_grupo', 'ano_enc_grupo', 'ano_inctr_grupo'],
      dtype='object')

##Proporção dos preditores e desfecho

In [217]:
#Lista de variáveis com o desfecho
lista_variaveis = [ 'cura', 'cs_sexo', 'faixa_etaria','cs_raca', 'escola_faixa', 'contato_5_15',
                   'pop_rua','pop_liber','pop_imig','benef_gov', 'agravtabac','agravalcoo','agravdroga',
                    'agravdiabe', 'agravdoenc', 'tempo_diag_trat_14','raiox_tora', 'bacilosc_e',
                    'front', 'ano_inctr_grupo','ano_enc_grupo','pop_grupo'
                  ]

In [218]:
for coluna in lista_variaveis:
    print(f"\n==== Variável: {coluna} ====")

    # Frequência absoluta
    freq_abs = df[coluna].value_counts(dropna=False)

    # Frequência relativa (em %)
    freq_rel = df[coluna].value_counts(normalize=True, dropna=False) * 100

    # Juntar em um único DataFrame para visualização
    tabela = pd.DataFrame({
        'Frequência Absoluta': freq_abs,
        'Frequência Relativa (%)': freq_rel.round(2)
    })

    print(tabela)

==== Variável: cura ====
      Frequência Absoluta  Frequência Relativa (%)
cura
1                   20798                    81.15
0                    4832                    18.85

==== Variável: cs_sexo ====
         Frequência Absoluta  Frequência Relativa (%)
cs_sexo
1.0                    17635                    68.81
0.0                     7993                    31.19
NaN                        2                     0.01

==== Variável: faixa_etaria ====
              Frequência Absoluta  Frequência Relativa (%)
faixa_etaria
1.0                         12637                    49.31
2.0                          7317                    28.55
3.0                          3394                    13.24
0.0                          2260                     8.82
NaN                            22                     0.09

==== Variável: cs_raca ====
         Frequência Absoluta  Frequência Relativa (%)
cs_raca
4.0                    11698                    45.64
1.0                     6514                    25.42
2.0                     5766                    22.50
NaN                     1397                     5.45
3.0                      216                     0.84
5.0                       39                     0.15

==== Variável: escola_faixa ====
              Frequência Absoluta  Frequência Relativa (%)
escola_faixa
0.0                         15697                    61.24
1.0                          5648                    22.04
NaN                          4056                    15.83
10.0                          229                     0.89

==== Variável: contato_5_15 ====
              Frequência Absoluta  Frequência Relativa (%)
contato_5_15
0.0                         23284                    90.85
1.0                          1977                     7.71
2.0                           224                     0.87
NaN                           145                     0.57

==== Variável: pop_rua ====
         Frequência Absoluta  Frequência Relativa (%)
pop_rua
0.0                    23981                    93.57
NaN                      896                     3.50
1.0                      753                     2.94

==== Variável: pop_liber ====
           Frequência Absoluta  Frequência Relativa (%)
pop_liber
0.0                      23224                    90.61
1.0                       1807                     7.05
NaN                        599                     2.34

==== Variável: pop_imig ====
          Frequência Absoluta  Frequência Relativa (%)
pop_imig
0.0                     24535                    95.73
NaN                      1000                     3.90
1.0                        95                     0.37

==== Variável: benef_gov ====
           Frequência Absoluta  Frequência Relativa (%)
benef_gov
0.0                      19845                    77.43
NaN                       3344                    13.05
1.0                       2441                     9.52

==== Variável: agravtabac ====
            Frequência Absoluta  Frequência Relativa (%)
agravtabac
0.0                       17083                    66.65
1.0                        6991                    27.28
NaN                        1556                     6.07

==== Variável: agravalcoo ====
            Frequência Absoluta  Frequência Relativa (%)
agravalcoo
0.0                       20306                    79.23
1.0                        3852                    15.03
NaN                        1472                     5.74

==== Variável: agravdroga ====
            Frequência Absoluta  Frequência Relativa (%)
agravdroga
0.0                       19669                    76.74
1.0                        4346                    16.96
NaN                        1615                     6.30

==== Variável: agravdiabe ====
            Frequência Absoluta  Frequência Relativa (%)
agravdiabe
0.0                       21789                    85.01
1.0                        2394                     9.34
NaN                        1447                     5.65

==== Variável: agravdoenc ====
            Frequência Absoluta  Frequência Relativa (%)
agravdoenc
0.0                       23358                    91.14
NaN                        1571                     6.13
1.0                         701                     2.74

==== Variável: tempo_diag_trat_14 ====
                    Frequência Absoluta  Frequência Relativa (%)
tempo_diag_trat_14
0.0                               24570                    95.86
1.0                                1060                     4.14

==== Variável: raiox_tora ====
            Frequência Absoluta  Frequência Relativa (%)
raiox_tora
1.0                       21723                    84.76
4.0                        3204                    12.50
2.0                         604                     2.36
NaN                          99                     0.39

==== Variável: bacilosc_e ====
            Frequência Absoluta  Frequência Relativa (%)
bacilosc_e
1.0                       16120                    62.90
3.0                        7214                    28.15
2.0                        2296                     8.96

==== Variável: front ====
       Frequência Absoluta  Frequência Relativa (%)
front
0                    25630                    100.0

==== Variável: ano_inctr_grupo ====
                 Frequência Absoluta  Frequência Relativa (%)
ano_inctr_grupo
2015-2022                      20621                    80.46
2023-2024                       5009                    19.54

==== Variável: ano_enc_grupo ====
               Frequência Absoluta  Frequência Relativa (%)
ano_enc_grupo
2015-2022                    18306                    71.42
2023-2024                     7324                    28.58

==== Variável: pop_grupo ====
                  Frequência Absoluta  Frequência Relativa (%)
pop_grupo
>1000000                        16458                    64.21
300000 a 1000000                 7473                    29.16
< 300000                         1696                     6.62
NaN                                 3                     0.01

In [219]:
# Listas
lista_variavel_desfecho = ['cura']

lista_preditores = [ 'cs_sexo', 'faixa_etaria','cs_raca', 'escola_faixa', 'contato_5_15',
                   'pop_rua','pop_liber','pop_imig','benef_gov', 'agravtabac','agravalcoo','agravdroga',
                    'agravdiabe', 'agravdoenc', 'tempo_diag_trat_14','raiox_tora', 'bacilosc_e',
                    'front', 'ano_inctr_grupo','ano_enc_grupo','pop_grupo'
                  ]

# Dicionário para salvar os resultados
resultados = {}

desfecho = lista_variavel_desfecho[0]

for var in lista_preditores:

    # Versão temporária sem NA (convertendo para object)
    temp_var = df[var].astype('object').where(df[var].notna(), 'NA')

    # Contagem
    tabela = (
        pd.DataFrame({var: temp_var, desfecho: df[desfecho]})
        .groupby([var, desfecho], dropna=False)
        .size()
        .rename("Frequência Absoluta")
        .reset_index()
    )

    # Frequência relativa
    tabela["Frequência Relativa (%)"] = (
        tabela["Frequência Absoluta"]
        / tabela.groupby(var)["Frequência Absoluta"].transform("sum")
        * 100
    ).round(2)

    resultados[var] = tabela

# Exibir
for var, tabela in resultados.items():
    print(f"\n==== Variável: {var} ====")
    print(tabela)

==== Variável: cs_sexo ====
  cs_sexo  cura  Frequência Absoluta  Frequência Relativa (%)
0     0.0     0                 1006                    12.59
1     0.0     1                 6987                    87.41
2     1.0     0                 3826                    21.70
3     1.0     1                13809                    78.30
4      NA     1                    2                   100.00

==== Variável: faixa_etaria ====
  faixa_etaria  cura  Frequência Absoluta  Frequência Relativa (%)
0          0.0     0                  383                    16.95
1          0.0     1                 1877                    83.05
2          1.0     0                 2901                    22.96
3          1.0     1                 9736                    77.04
4          2.0     0                 1128                    15.42
5          2.0     1                 6189                    84.58
6          3.0     0                  417                    12.29
7          3.0     1                 2977                    87.71
8           NA     0                    3                    13.64
9           NA     1                   19                    86.36

==== Variável: cs_raca ====
   cs_raca  cura  Frequência Absoluta  Frequência Relativa (%)
0      1.0     0                  845                    12.97
1      1.0     1                 5669                    87.03
2      2.0     0                 1326                    23.00
3      2.0     1                 4440                    77.00
4      3.0     0                   40                    18.52
5      3.0     1                  176                    81.48
6      4.0     0                 2300                    19.66
7      4.0     1                 9398                    80.34
8      5.0     0                    7                    17.95
9      5.0     1                   32                    82.05
10      NA     0                  314                    22.48
11      NA     1                 1083                    77.52

==== Variável: escola_faixa ====
  escola_faixa  cura  Frequência Absoluta  Frequência Relativa (%)
0          0.0     0                 3286                    20.93
1          0.0     1                12411                    79.07
2          1.0     0                  551                     9.76
3          1.0     1                 5097                    90.24
4         10.0     0                   49                    21.40
5         10.0     1                  180                    78.60
6           NA     0                  946                    23.32
7           NA     1                 3110                    76.68

==== Variável: contato_5_15 ====
  contato_5_15  cura  Frequência Absoluta  Frequência Relativa (%)
0          0.0     0                 4366                    18.75
1          0.0     1                18918                    81.25
2          1.0     0                  366                    18.51
3          1.0     1                 1611                    81.49
4          2.0     0                   53                    23.66
5          2.0     1                  171                    76.34
6           NA     0                   47                    32.41
7           NA     1                   98                    67.59

==== Variável: pop_rua ====
  pop_rua  cura  Frequência Absoluta  Frequência Relativa (%)
0     0.0     0                 4223                    17.61
1     0.0     1                19758                    82.39
2     1.0     0                  400                    53.12
3     1.0     1                  353                    46.88
4      NA     0                  209                    23.33
5      NA     1                  687                    76.67

==== Variável: pop_liber ====
  pop_liber  cura  Frequência Absoluta  Frequência Relativa (%)
0       0.0     0                 4324                    18.62
1       0.0     1                18900                    81.38
2       1.0     0                  383                    21.20
3       1.0     1                 1424                    78.80
4        NA     0                  125                    20.87
5        NA     1                  474                    79.13

==== Variável: pop_imig ====
  pop_imig  cura  Frequência Absoluta  Frequência Relativa (%)
0      0.0     0                 4569                    18.62
1      0.0     1                19966                    81.38
2      1.0     0                   23                    24.21
3      1.0     1                   72                    75.79
4       NA     0                  240                    24.00
5       NA     1                  760                    76.00

==== Variável: benef_gov ====
  benef_gov  cura  Frequência Absoluta  Frequência Relativa (%)
0       0.0     0                 3676                    18.52
1       0.0     1                16169                    81.48
2       1.0     0                  406                    16.63
3       1.0     1                 2035                    83.37
4        NA     0                  750                    22.43
5        NA     1                 2594                    77.57

==== Variável: agravtabac ====
  agravtabac  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 2445                    14.31
1        0.0     1                14638                    85.69
2        1.0     0                 1944                    27.81
3        1.0     1                 5047                    72.19
4         NA     0                  443                    28.47
5         NA     1                 1113                    71.53

==== Variável: agravalcoo ====
  agravalcoo  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 3348                    16.49
1        0.0     1                16958                    83.51
2        1.0     0                 1067                    27.70
3        1.0     1                 2785                    72.30
4         NA     0                  417                    28.33
5         NA     1                 1055                    71.67

==== Variável: agravdroga ====
  agravdroga  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 2777                    14.12
1        0.0     1                16892                    85.88
2        1.0     0                 1608                    37.00
3        1.0     1                 2738                    63.00
4         NA     0                  447                    27.68
5         NA     1                 1168                    72.32

==== Variável: agravdiabe ====
  agravdiabe  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 4147                    19.03
1        0.0     1                17642                    80.97
2        1.0     0                  269                    11.24
3        1.0     1                 2125                    88.76
4         NA     0                  416                    28.75
5         NA     1                 1031                    71.25

==== Variável: agravdoenc ====
  agravdoenc  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 4210                    18.02
1        0.0     1                19148                    81.98
2        1.0     0                  173                    24.68
3        1.0     1                  528                    75.32
4         NA     0                  449                    28.58
5         NA     1                 1122                    71.42

==== Variável: tempo_diag_trat_14 ====
   tempo_diag_trat_14  cura  Frequência Absoluta  Frequência Relativa (%)
0                 0.0     0                 4552                    18.53
1                 0.0     1                20018                    81.47
2                 1.0     0                  280                    26.42
3                 1.0     1                  780                    73.58

==== Variável: raiox_tora ====
  raiox_tora  cura  Frequência Absoluta  Frequência Relativa (%)
0        1.0     0                 3925                    18.07
1        1.0     1                17798                    81.93
2        2.0     0                   75                    12.42
3        2.0     1                  529                    87.58
4        4.0     0                  807                    25.19
5        4.0     1                 2397                    74.81
6         NA     0                   25                    25.25
7         NA     1                   74                    74.75

==== Variável: bacilosc_e ====
   bacilosc_e  cura  Frequência Absoluta  Frequência Relativa (%)
0         1.0     0                 2981                    18.49
1         1.0     1                13139                    81.51
2         2.0     0                  359                    15.64
3         2.0     1                 1937                    84.36
4         3.0     0                 1492                    20.68
5         3.0     1                 5722                    79.32

==== Variável: front ====
   front  cura  Frequência Absoluta  Frequência Relativa (%)
0      0     0                 4832                    18.85
1      0     1                20798                    81.15

==== Variável: ano_inctr_grupo ====
  ano_inctr_grupo  cura  Frequência Absoluta  Frequência Relativa (%)
0       2015-2022     0                 3903                    18.93
1       2015-2022     1                16718                    81.07
2       2023-2024     0                  929                    18.55
3       2023-2024     1                 4080                    81.45

==== Variável: ano_enc_grupo ====
  ano_enc_grupo  cura  Frequência Absoluta  Frequência Relativa (%)
0     2015-2022     0                 3594                    19.63
1     2015-2022     1                14712                    80.37
2     2023-2024     0                 1238                    16.90
3     2023-2024     1                 6086                    83.10

==== Variável: pop_grupo ====
          pop_grupo  cura  Frequência Absoluta  Frequência Relativa (%)
0  300000 a 1000000     0                 1717                    22.98
1  300000 a 1000000     1                 5756                    77.02
2          < 300000     0                  313                    18.46
3          < 300000     1                 1383                    81.54
4          >1000000     0                 2802                    17.03
5          >1000000     1                13656                    82.97
6                NA     1                    3                   100.00

###Etapa2

In [220]:
df = pd.read_csv("dfrj2.csv",sep=",")

In [221]:
df.shape

(24537, 29)

In [222]:
df.shape

(24537, 29)

In [223]:
df.columns

Index(['nu_ano', 'cs_sexo', 'cs_raca', 'sg_uf', 'raiox_tora', 'agravalcoo',
       'agravdiabe', 'agravdoenc', 'bacilosc_e', 'cultura_es', 'bacilosc_2',
       'tratsup_at', 'pop_liber', 'pop_rua', 'pop_imig', 'benef_gov',
       'agravdroga', 'agravtabac', 'ano_base', 'cura', 'pop', 'front',
       'tempo_diag_trat_14', 'dt_cul', 'ano_inc_trat', 'ano_encerra',
       'escola_faixa', 'contato_5_15', 'faixa_etaria'],
      dtype='object')

In [224]:
df['pop'].describe()

count    2.453400e+04
mean     4.226834e+06
std      2.677561e+06
min      1.182800e+04
25%      8.081610e+05
50%      6.211223e+06
75%      6.211223e+06
max      6.211223e+06
Name: pop, dtype: float64

In [225]:
import pandas as pd

# Criação da variável categórica com pd.cut
df['pop_grupo'] = pd.cut(
    df['pop'],
    bins=[-float('inf'),300000, 1000000, float('inf')],
    labels=['< 300000', '300000 a 1000000', '>1000000']
)

In [226]:
df['pop_grupo'].value_counts(dropna=False)

pop_grupo
>1000000            15816
300000 a 1000000     7124
< 300000             1594
NaN                     3
Name: count, dtype: int64

In [227]:
df['ano_encerra'].value_counts(dropna=False)

ano_encerra
2023    4267
2022    3599
2021    2909
2019    2873
2024    2803
2020    2771
2018    2432
2016    1201
2017     972
2015     691
2025      19
Name: count, dtype: int64

In [228]:
df['ano_enc_grupo'] = pd.cut(
    df['ano_encerra'],
    bins=[2014, 2022, float('inf')],
    labels=['2015-2022', '2023-2024']
)

In [229]:
df['ano_enc_grupo'].value_counts(dropna=False)

ano_enc_grupo
2015-2022    17448
2023-2024     7089
Name: count, dtype: int64

In [230]:
df['ano_inc_trat'].value_counts(dropna=False)

ano_inc_trat
2023    4740
2022    3983
2021    3179
2019    2949
2018    2755
2020    2686
2017    2284
2015    1903
2024      46
2016      12
Name: count, dtype: int64

In [231]:
df['ano_inctr_grupo'] = pd.cut(
    df['ano_inc_trat'],
    bins=[2014, 2022, float('inf')],
    labels=['2015-2022', '2023-2024']
)

In [232]:
df['ano_inctr_grupo'].value_counts(dropna=False)

ano_inctr_grupo
2015-2022    19751
2023-2024     4786
Name: count, dtype: int64

In [233]:
df.columns

Index(['nu_ano', 'cs_sexo', 'cs_raca', 'sg_uf', 'raiox_tora', 'agravalcoo',
       'agravdiabe', 'agravdoenc', 'bacilosc_e', 'cultura_es', 'bacilosc_2',
       'tratsup_at', 'pop_liber', 'pop_rua', 'pop_imig', 'benef_gov',
       'agravdroga', 'agravtabac', 'ano_base', 'cura', 'pop', 'front',
       'tempo_diag_trat_14', 'dt_cul', 'ano_inc_trat', 'ano_encerra',
       'escola_faixa', 'contato_5_15', 'faixa_etaria', 'pop_grupo',
       'ano_enc_grupo', 'ano_inctr_grupo'],
      dtype='object')

##Proporção dos preditores e desfecho

In [234]:
#Lista de variáveis com o desfecho
lista_variaveis = [ 'cura', 'cs_sexo', 'faixa_etaria','cs_raca', 'escola_faixa', 'contato_5_15',
                   'pop_rua','pop_liber','pop_imig','benef_gov', 'agravtabac','agravalcoo','agravdroga',
                    'agravdiabe', 'agravdoenc', 'tempo_diag_trat_14','raiox_tora', 'cultura_es','bacilosc_e',
                    'bacilosc_2', 'tratsup_at','front', 'ano_inctr_grupo','ano_enc_grupo','pop_grupo'
                  ]

In [235]:
for coluna in lista_variaveis:
    print(f"\n==== Variável: {coluna} ====")

    # Frequência absoluta
    freq_abs = df[coluna].value_counts(dropna=False)

    # Frequência relativa (em %)
    freq_rel = df[coluna].value_counts(normalize=True, dropna=False) * 100

    # Juntar em um único DataFrame para visualização
    tabela = pd.DataFrame({
        'Frequência Absoluta': freq_abs,
        'Frequência Relativa (%)': freq_rel.round(2)
    })

    print(tabela)

==== Variável: cura ====
      Frequência Absoluta  Frequência Relativa (%)
cura
1                   20537                     83.7
0                    4000                     16.3

==== Variável: cs_sexo ====
         Frequência Absoluta  Frequência Relativa (%)
cs_sexo
1.0                    16822                    68.56
0.0                     7713                    31.43
NaN                        2                     0.01

==== Variável: faixa_etaria ====
              Frequência Absoluta  Frequência Relativa (%)
faixa_etaria
1.0                         12139                    49.47
2.0                          7012                    28.58
3.0                          3184                    12.98
0.0                          2181                     8.89
NaN                            21                     0.09

==== Variável: cs_raca ====
         Frequência Absoluta  Frequência Relativa (%)
cs_raca
4.0                    11217                    45.71
1.0                     6276                    25.58
2.0                     5482                    22.34
NaN                     1317                     5.37
3.0                      207                     0.84
5.0                       38                     0.15

==== Variável: escola_faixa ====
              Frequência Absoluta  Frequência Relativa (%)
escola_faixa
0.0                         15033                    61.27
1.0                          5513                    22.47
NaN                          3774                    15.38
10.0                          217                     0.88

==== Variável: contato_5_15 ====
              Frequência Absoluta  Frequência Relativa (%)
contato_5_15
0.0                         22315                    90.94
1.0                          1889                     7.70
2.0                           210                     0.86
NaN                           123                     0.50

==== Variável: pop_rua ====
         Frequência Absoluta  Frequência Relativa (%)
pop_rua
0.0                    23056                    93.96
NaN                      842                     3.43
1.0                      639                     2.60

==== Variável: pop_liber ====
           Frequência Absoluta  Frequência Relativa (%)
pop_liber
0.0                      22217                    90.54
1.0                       1756                     7.16
NaN                        564                     2.30

==== Variável: pop_imig ====
          Frequência Absoluta  Frequência Relativa (%)
pop_imig
0.0                     23503                    95.79
NaN                       947                     3.86
1.0                        87                     0.35

==== Variável: benef_gov ====
           Frequência Absoluta  Frequência Relativa (%)
benef_gov
0.0                      19069                    77.72
NaN                       3107                    12.66
1.0                       2361                     9.62

==== Variável: agravtabac ====
            Frequência Absoluta  Frequência Relativa (%)
agravtabac
0.0                       16481                    67.17
1.0                        6615                    26.96
NaN                        1441                     5.87

==== Variável: agravalcoo ====
            Frequência Absoluta  Frequência Relativa (%)
agravalcoo
0.0                       19546                    79.66
1.0                        3634                    14.81
NaN                        1357                     5.53

==== Variável: agravdroga ====
            Frequência Absoluta  Frequência Relativa (%)
agravdroga
0.0                       18967                    77.30
1.0                        4069                    16.58
NaN                        1501                     6.12

==== Variável: agravdiabe ====
            Frequência Absoluta  Frequência Relativa (%)
agravdiabe
0.0                       20917                    85.25
1.0                        2281                     9.30
NaN                        1339                     5.46

==== Variável: agravdoenc ====
            Frequência Absoluta  Frequência Relativa (%)
agravdoenc
0.0                       22424                    91.39
NaN                        1448                     5.90
1.0                         665                     2.71

==== Variável: tempo_diag_trat_14 ====
                    Frequência Absoluta  Frequência Relativa (%)
tempo_diag_trat_14
0.0                               23559                    96.01
1.0                                 978                     3.99

==== Variável: raiox_tora ====
            Frequência Absoluta  Frequência Relativa (%)
raiox_tora
1.0                       20849                    84.97
4.0                        3009                    12.26
2.0                         588                     2.40
NaN                          91                     0.37

==== Variável: cultura_es ====
            Frequência Absoluta  Frequência Relativa (%)
cultura_es
4.0                       11859                    48.33
1.0                       10731                    43.73
2.0                        1791                     7.30
3.0                         156                     0.64

==== Variável: bacilosc_e ====
            Frequência Absoluta  Frequência Relativa (%)
bacilosc_e
1.0                       15439                    62.92
3.0                        6916                    28.19
2.0                        2182                     8.89

==== Variável: bacilosc_2 ====
            Frequência Absoluta  Frequência Relativa (%)
bacilosc_2
3.0                       11746                    47.87
2.0                        6698                    27.30
NaN                        4625                    18.85
1.0                        1468                     5.98

==== Variável: tratsup_at ====
            Frequência Absoluta  Frequência Relativa (%)
tratsup_at
1.0                       12822                    52.26
2.0                        8858                    36.10
NaN                        2857                    11.64

==== Variável: front ====
       Frequência Absoluta  Frequência Relativa (%)
front
0                    24537                    100.0

==== Variável: ano_inctr_grupo ====
                 Frequência Absoluta  Frequência Relativa (%)
ano_inctr_grupo
2015-2022                      19751                    80.49
2023-2024                       4786                    19.51

==== Variável: ano_enc_grupo ====
               Frequência Absoluta  Frequência Relativa (%)
ano_enc_grupo
2015-2022                    17448                    71.11
2023-2024                     7089                    28.89

==== Variável: pop_grupo ====
                  Frequência Absoluta  Frequência Relativa (%)
pop_grupo
>1000000                        15816                    64.46
300000 a 1000000                 7124                    29.03
< 300000                         1594                     6.50
NaN                                 3                     0.01

In [236]:
# Listas
lista_variavel_desfecho = ['cura']

lista_preditores = [ 'cs_sexo', 'faixa_etaria','cs_raca', 'escola_faixa', 'contato_5_15',
                   'pop_rua','pop_liber','pop_imig','benef_gov', 'agravtabac','agravalcoo','agravdroga',
                    'agravdiabe', 'agravdoenc', 'tempo_diag_trat_14','raiox_tora', 'cultura_es','bacilosc_e',
                    'bacilosc_2', 'tratsup_at','front', 'ano_inctr_grupo','ano_enc_grupo','pop_grupo']

# Dicionário para salvar os resultados
resultados = {}

desfecho = lista_variavel_desfecho[0]

for var in lista_preditores:

    # Versão temporária sem NA (convertendo para object)
    temp_var = df[var].astype('object').where(df[var].notna(), 'NA')

    # Contagem
    tabela = (
        pd.DataFrame({var: temp_var, desfecho: df[desfecho]})
        .groupby([var, desfecho], dropna=False)
        .size()
        .rename("Frequência Absoluta")
        .reset_index()
    )

    # Frequência relativa
    tabela["Frequência Relativa (%)"] = (
        tabela["Frequência Absoluta"]
        / tabela.groupby(var)["Frequência Absoluta"].transform("sum")
        * 100
    ).round(2)

    resultados[var] = tabela

# Exibir
for var, tabela in resultados.items():
    print(f"\n==== Variável: {var} ====")
    print(tabela)

==== Variável: cs_sexo ====
  cs_sexo  cura  Frequência Absoluta  Frequência Relativa (%)
0     0.0     0                  815                    10.57
1     0.0     1                 6898                    89.43
2     1.0     0                 3185                    18.93
3     1.0     1                13637                    81.07
4      NA     1                    2                   100.00

==== Variável: faixa_etaria ====
  faixa_etaria  cura  Frequência Absoluta  Frequência Relativa (%)
0          0.0     0                  325                    14.90
1          0.0     1                 1856                    85.10
2          1.0     0                 2534                    20.87
3          1.0     1                 9605                    79.13
4          2.0     0                  907                    12.93
5          2.0     1                 6105                    87.07
6          3.0     0                  232                     7.29
7          3.0     1                 2952                    92.71
8           NA     0                    2                     9.52
9           NA     1                   19                    90.48

==== Variável: cs_raca ====
   cs_raca  cura  Frequência Absoluta  Frequência Relativa (%)
0      1.0     0                  671                    10.69
1      1.0     1                 5605                    89.31
2      2.0     0                 1098                    20.03
3      2.0     1                 4384                    79.97
4      3.0     0                   32                    15.46
5      3.0     1                  175                    84.54
6      4.0     0                 1939                    17.29
7      4.0     1                 9278                    82.71
8      5.0     0                    6                    15.79
9      5.0     1                   32                    84.21
10      NA     0                  254                    19.29
11      NA     1                 1063                    80.71

==== Variável: escola_faixa ====
  escola_faixa  cura  Frequência Absoluta  Frequência Relativa (%)
0          0.0     0                 2758                    18.35
1          0.0     1                12275                    81.65
2          1.0     0                  467                     8.47
3          1.0     1                 5046                    91.53
4         10.0     0                   39                    17.97
5         10.0     1                  178                    82.03
6           NA     0                  736                    19.50
7           NA     1                 3038                    80.50

==== Variável: contato_5_15 ====
  contato_5_15  cura  Frequência Absoluta  Frequência Relativa (%)
0          0.0     0                 3630                    16.27
1          0.0     1                18685                    83.73
2          1.0     0                  298                    15.78
3          1.0     1                 1591                    84.22
4          2.0     0                   43                    20.48
5          2.0     1                  167                    79.52
6           NA     0                   29                    23.58
7           NA     1                   94                    76.42

==== Variável: pop_rua ====
  pop_rua  cura  Frequência Absoluta  Frequência Relativa (%)
0     0.0     0                 3539                    15.35
1     0.0     1                19517                    84.65
2     1.0     0                  294                    46.01
3     1.0     1                  345                    53.99
4      NA     0                  167                    19.83
5      NA     1                  675                    80.17

==== Variável: pop_liber ====
  pop_liber  cura  Frequência Absoluta  Frequência Relativa (%)
0       0.0     0                 3555                    16.00
1       0.0     1                18662                    84.00
2       1.0     0                  349                    19.87
3       1.0     1                 1407                    80.13
4        NA     0                   96                    17.02
5        NA     1                  468                    82.98

==== Variável: pop_imig ====
  pop_imig  cura  Frequência Absoluta  Frequência Relativa (%)
0      0.0     0                 3786                    16.11
1      0.0     1                19717                    83.89
2      1.0     0                   17                    19.54
3      1.0     1                   70                    80.46
4       NA     0                  197                    20.80
5       NA     1                  750                    79.20

==== Variável: benef_gov ====
  benef_gov  cura  Frequência Absoluta  Frequência Relativa (%)
0       0.0     0                 3087                    16.19
1       0.0     1                15982                    83.81
2       1.0     0                  345                    14.61
3       1.0     1                 2016                    85.39
4        NA     0                  568                    18.28
5        NA     1                 2539                    81.72

==== Variável: agravtabac ====
  agravtabac  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 2024                    12.28
1        0.0     1                14457                    87.72
2        1.0     0                 1626                    24.58
3        1.0     1                 4989                    75.42
4         NA     0                  350                    24.29
5         NA     1                 1091                    75.71

==== Variável: agravalcoo ====
  agravalcoo  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 2786                    14.25
1        0.0     1                16760                    85.75
2        1.0     0                  884                    24.33
3        1.0     1                 2750                    75.67
4         NA     0                  330                    24.32
5         NA     1                 1027                    75.68

==== Variável: agravdroga ====
  agravdroga  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 2288                    12.06
1        0.0     1                16679                    87.94
2        1.0     0                 1359                    33.40
3        1.0     1                 2710                    66.60
4         NA     0                  353                    23.52
5         NA     1                 1148                    76.48

==== Variável: agravdiabe ====
  agravdiabe  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 3489                    16.68
1        0.0     1                17428                    83.32
2        1.0     0                  181                     7.94
3        1.0     1                 2100                    92.06
4         NA     0                  330                    24.65
5         NA     1                 1009                    75.35

==== Variável: agravdoenc ====
  agravdoenc  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 3504                    15.63
1        0.0     1                18920                    84.37
2        1.0     0                  143                    21.50
3        1.0     1                  522                    78.50
4         NA     0                  353                    24.38
5         NA     1                 1095                    75.62

==== Variável: tempo_diag_trat_14 ====
   tempo_diag_trat_14  cura  Frequência Absoluta  Frequência Relativa (%)
0                 0.0     0                 3781                    16.05
1                 0.0     1                19778                    83.95
2                 1.0     0                  219                    22.39
3                 1.0     1                  759                    77.61

==== Variável: raiox_tora ====
  raiox_tora  cura  Frequência Absoluta  Frequência Relativa (%)
0        1.0     0                 3268                    15.67
1        1.0     1                17581                    84.33
2        2.0     0                   63                    10.71
3        2.0     1                  525                    89.29
4        4.0     0                  649                    21.57
5        4.0     1                 2360                    78.43
6         NA     0                   20                    21.98
7         NA     1                   71                    78.02

==== Variável: cultura_es ====
   cultura_es  cura  Frequência Absoluta  Frequência Relativa (%)
0         1.0     0                 1615                    15.05
1         1.0     1                 9116                    84.95
2         2.0     0                  173                     9.66
3         2.0     1                 1618                    90.34
4         3.0     0                   15                     9.62
5         3.0     1                  141                    90.38
6         4.0     0                 2197                    18.53
7         4.0     1                 9662                    81.47

==== Variável: bacilosc_e ====
   bacilosc_e  cura  Frequência Absoluta  Frequência Relativa (%)
0         1.0     0                 2462                    15.95
1         1.0     1                12977                    84.05
2         2.0     0                  273                    12.51
3         2.0     1                 1909                    87.49
4         3.0     0                 1265                    18.29
5         3.0     1                 5651                    81.71

==== Variável: bacilosc_2 ====
  bacilosc_2  cura  Frequência Absoluta  Frequência Relativa (%)
0        1.0     0                  196                    13.35
1        1.0     1                 1272                    86.65
2        2.0     0                  554                     8.27
3        2.0     1                 6144                    91.73
4        3.0     0                 2007                    17.09
5        3.0     1                 9739                    82.91
6         NA     0                 1243                    26.88
7         NA     1                 3382                    73.12

==== Variável: tratsup_at ====
  tratsup_at  cura  Frequência Absoluta  Frequência Relativa (%)
0        1.0     0                 1571                    12.25
1        1.0     1                11251                    87.75
2        2.0     0                 1726                    19.49
3        2.0     1                 7132                    80.51
4         NA     0                  703                    24.61
5         NA     1                 2154                    75.39

==== Variável: front ====
   front  cura  Frequência Absoluta  Frequência Relativa (%)
0      0     0                 4000                     16.3
1      0     1                20537                     83.7

==== Variável: ano_inctr_grupo ====
  ano_inctr_grupo  cura  Frequência Absoluta  Frequência Relativa (%)
0       2015-2022     0                 3249                    16.45
1       2015-2022     1                16502                    83.55
2       2023-2024     0                  751                    15.69
3       2023-2024     1                 4035                    84.31

==== Variável: ano_enc_grupo ====
  ano_enc_grupo  cura  Frequência Absoluta  Frequência Relativa (%)
0     2015-2022     0                 2953                    16.92
1     2015-2022     1                14495                    83.08
2     2023-2024     0                 1047                    14.77
3     2023-2024     1                 6042                    85.23

==== Variável: pop_grupo ====
          pop_grupo  cura  Frequência Absoluta  Frequência Relativa (%)
0  300000 a 1000000     0                 1445                    20.28
1  300000 a 1000000     1                 5679                    79.72
2          < 300000     0                  234                    14.68
3          < 300000     1                 1360                    85.32
4          >1000000     0                 2321                    14.68
5          >1000000     1                13495                    85.32
6                NA     1                    3                   100.00

###Etapa3

In [237]:
df = pd.read_csv("dfrj3.csv",sep=",")

In [238]:
df.shape

(23121, 30)

In [239]:
df.shape

(23121, 30)

In [240]:
df.columns

Index(['nu_ano', 'cs_sexo', 'cs_raca', 'sg_uf', 'raiox_tora', 'agravalcoo',
       'agravdiabe', 'agravdoenc', 'bacilosc_e', 'cultura_es', 'bacilosc_2',
       'bacilosc_4', 'tratsup_at', 'pop_liber', 'pop_rua', 'pop_imig',
       'benef_gov', 'agravdroga', 'agravtabac', 'ano_base', 'cura', 'pop',
       'front', 'tempo_diag_trat_14', 'dt_cul', 'ano_inc_trat', 'ano_encerra',
       'escola_faixa', 'contato_5_15', 'faixa_etaria'],
      dtype='object')

In [241]:
df['pop'].describe()

count    2.311800e+04
mean     4.275912e+06
std      2.662878e+06
min      1.182800e+04
25%      8.081610e+05
50%      6.211223e+06
75%      6.211223e+06
max      6.211223e+06
Name: pop, dtype: float64

In [242]:
import pandas as pd

# Criação da variável categórica com pd.cut
df['pop_grupo'] = pd.cut(
    df['pop'],
    bins=[-float('inf'),300000, 1000000, float('inf')],
    labels=['< 300000', '300000 a 1000000', '>1000000']
)

In [243]:
df['pop_grupo'].value_counts(dropna=False)

pop_grupo
>1000000            15109
300000 a 1000000     6510
< 300000             1499
NaN                     3
Name: count, dtype: int64

In [244]:
df['ano_encerra'].value_counts(dropna=False)

ano_encerra
2023    3998
2022    3380
2021    2730
2024    2715
2019    2703
2020    2627
2018    2281
2016    1163
2017     885
2015     620
2025      19
Name: count, dtype: int64

In [245]:
df['ano_enc_grupo'] = pd.cut(
    df['ano_encerra'],
    bins=[2014, 2022, float('inf')],
    labels=['2015-2022', '2023-2024']
)

In [246]:
df['ano_enc_grupo'].value_counts(dropna=False)

ano_enc_grupo
2015-2022    16389
2023-2024     6732
Name: count, dtype: int64

In [247]:
df['ano_inc_trat'].value_counts(dropna=False)

ano_inc_trat
2023    4454
2022    3752
2021    2988
2019    2782
2018    2587
2020    2545
2017    2167
2015    1795
2024      40
2016      11
Name: count, dtype: int64

In [248]:
df['ano_inctr_grupo'] = pd.cut(
    df['ano_inc_trat'],
    bins=[2014, 2022, float('inf')],
    labels=['2015-2022', '2023-2024']
)

In [249]:
df['ano_inctr_grupo'].value_counts(dropna=False)

ano_inctr_grupo
2015-2022    18627
2023-2024     4494
Name: count, dtype: int64

In [250]:
df.columns

Index(['nu_ano', 'cs_sexo', 'cs_raca', 'sg_uf', 'raiox_tora', 'agravalcoo',
       'agravdiabe', 'agravdoenc', 'bacilosc_e', 'cultura_es', 'bacilosc_2',
       'bacilosc_4', 'tratsup_at', 'pop_liber', 'pop_rua', 'pop_imig',
       'benef_gov', 'agravdroga', 'agravtabac', 'ano_base', 'cura', 'pop',
       'front', 'tempo_diag_trat_14', 'dt_cul', 'ano_inc_trat', 'ano_encerra',
       'escola_faixa', 'contato_5_15', 'faixa_etaria', 'pop_grupo',
       'ano_enc_grupo', 'ano_inctr_grupo'],
      dtype='object')

##Proporção dos preditores e desfecho

In [251]:
#Lista de variáveis com o desfecho
lista_variaveis = ['cura', 'cs_sexo', 'faixa_etaria','cs_raca', 'escola_faixa', 'contato_5_15',
                   'pop_rua','pop_liber','pop_imig','benef_gov', 'agravtabac','agravalcoo','agravdroga',
                    'agravdiabe', 'agravdoenc', 'tempo_diag_trat_14','raiox_tora', 'cultura_es','bacilosc_e',
                    'bacilosc_2', 'bacilosc_4','tratsup_at','front', 'ano_inctr_grupo','ano_enc_grupo','pop_grupo']

In [252]:
for coluna in lista_variaveis:
    print(f"\n==== Variável: {coluna} ====")

    # Frequência absoluta
    freq_abs = df[coluna].value_counts(dropna=False)

    # Frequência relativa (em %)
    freq_rel = df[coluna].value_counts(normalize=True, dropna=False) * 100

    # Juntar em um único DataFrame para visualização
    tabela = pd.DataFrame({
        'Frequência Absoluta': freq_abs,
        'Frequência Relativa (%)': freq_rel.round(2)
    })

    print(tabela)

==== Variável: cura ====
      Frequência Absoluta  Frequência Relativa (%)
cura
1                   20395                    88.21
0                    2726                    11.79

==== Variável: cs_sexo ====
         Frequência Absoluta  Frequência Relativa (%)
cs_sexo
1.0                    15715                    67.97
0.0                     7404                    32.02
NaN                        2                     0.01

==== Variável: faixa_etaria ====
              Frequência Absoluta  Frequência Relativa (%)
faixa_etaria
1.0                         11288                    48.82
2.0                          6670                    28.85
3.0                          3084                    13.34
0.0                          2059                     8.91
NaN                            20                     0.09

==== Variável: cs_raca ====
         Frequência Absoluta  Frequência Relativa (%)
cs_raca
4.0                    10542                    45.59
1.0                     6029                    26.08
2.0                     5074                    21.95
NaN                     1241                     5.37
3.0                      198                     0.86
5.0                       37                     0.16

==== Variável: escola_faixa ====
              Frequência Absoluta  Frequência Relativa (%)
escola_faixa
0.0                         14031                    60.69
1.0                          5353                    23.15
NaN                          3529                    15.26
10.0                          208                     0.90

==== Variável: contato_5_15 ====
              Frequência Absoluta  Frequência Relativa (%)
contato_5_15
0.0                         21012                    90.88
1.0                          1801                     7.79
2.0                           199                     0.86
NaN                           109                     0.47

==== Variável: pop_rua ====
         Frequência Absoluta  Frequência Relativa (%)
pop_rua
0.0                    21813                    94.34
NaN                      798                     3.45
1.0                      510                     2.21

==== Variável: pop_liber ====
           Frequência Absoluta  Frequência Relativa (%)
pop_liber
0.0                      20909                    90.43
1.0                       1683                     7.28
NaN                        529                     2.29

==== Variável: pop_imig ====
          Frequência Absoluta  Frequência Relativa (%)
pop_imig
0.0                     22147                    95.79
NaN                       894                     3.87
1.0                        80                     0.35

==== Variável: benef_gov ====
           Frequência Absoluta  Frequência Relativa (%)
benef_gov
0.0                      17989                    77.80
NaN                       2915                    12.61
1.0                       2217                     9.59

==== Variável: agravtabac ====
            Frequência Absoluta  Frequência Relativa (%)
agravtabac
0.0                       15745                    68.10
1.0                        6017                    26.02
NaN                        1359                     5.88

==== Variável: agravalcoo ====
            Frequência Absoluta  Frequência Relativa (%)
agravalcoo
0.0                       18560                    80.27
1.0                        3282                    14.19
NaN                        1279                     5.53

==== Variável: agravdroga ====
            Frequência Absoluta  Frequência Relativa (%)
agravdroga
0.0                       18142                    78.47
1.0                        3563                    15.41
NaN                        1416                     6.12

==== Variável: agravdiabe ====
            Frequência Absoluta  Frequência Relativa (%)
agravdiabe
0.0                       19646                    84.97
1.0                        2208                     9.55
NaN                        1267                     5.48

==== Variável: agravdoenc ====
            Frequência Absoluta  Frequência Relativa (%)
agravdoenc
0.0                       21145                    91.45
NaN                        1367                     5.91
1.0                         609                     2.63

==== Variável: tempo_diag_trat_14 ====
                    Frequência Absoluta  Frequência Relativa (%)
tempo_diag_trat_14
0.0                               22239                    96.19
1.0                                 882                     3.81

==== Variável: raiox_tora ====
            Frequência Absoluta  Frequência Relativa (%)
raiox_tora
1.0                       19707                    85.23
4.0                        2767                    11.97
2.0                         562                     2.43
NaN                          85                     0.37

==== Variável: cultura_es ====
            Frequência Absoluta  Frequência Relativa (%)
cultura_es
4.0                       11026                    47.69
1.0                       10219                    44.20
2.0                        1728                     7.47
3.0                         148                     0.64

==== Variável: bacilosc_e ====
            Frequência Absoluta  Frequência Relativa (%)
bacilosc_e
1.0                       14555                    62.95
3.0                        6493                    28.08
2.0                        2073                     8.97

==== Variável: bacilosc_2 ====
            Frequência Absoluta  Frequência Relativa (%)
bacilosc_2
3.0                       11072                    47.89
2.0                        6555                    28.35
NaN                        4085                    17.67
1.0                        1409                     6.09

==== Variável: bacilosc_4 ====
            Frequência Absoluta  Frequência Relativa (%)
bacilosc_4
3.0                       13031                    56.36
NaN                        5250                    22.71
2.0                        4606                    19.92
1.0                         234                     1.01

==== Variável: tratsup_at ====
            Frequência Absoluta  Frequência Relativa (%)
tratsup_at
1.0                       12300                    53.20
2.0                        8204                    35.48
NaN                        2617                    11.32

==== Variável: front ====
       Frequência Absoluta  Frequência Relativa (%)
front
0                    23121                    100.0

==== Variável: ano_inctr_grupo ====
                 Frequência Absoluta  Frequência Relativa (%)
ano_inctr_grupo
2015-2022                      18627                    80.56
2023-2024                       4494                    19.44

==== Variável: ano_enc_grupo ====
               Frequência Absoluta  Frequência Relativa (%)
ano_enc_grupo
2015-2022                    16389                    70.88
2023-2024                     6732                    29.12

==== Variável: pop_grupo ====
                  Frequência Absoluta  Frequência Relativa (%)
pop_grupo
>1000000                        15109                    65.35
300000 a 1000000                 6510                    28.16
< 300000                         1499                     6.48
NaN                                 3                     0.01

In [253]:
# Listas
lista_variavel_desfecho = ['cura']

lista_preditores = ['cs_sexo', 'faixa_etaria','cs_raca', 'escola_faixa', 'contato_5_15',
                   'pop_rua','pop_liber','pop_imig','benef_gov', 'agravtabac','agravalcoo','agravdroga',
                    'agravdiabe', 'agravdoenc', 'tempo_diag_trat_14','raiox_tora', 'cultura_es','bacilosc_e',
                    'bacilosc_2', 'bacilosc_4','tratsup_at','front', 'ano_inctr_grupo','ano_enc_grupo','pop_grupo']

# Dicionário para salvar os resultados
resultados = {}

desfecho = lista_variavel_desfecho[0]

for var in lista_preditores:

    # Versão temporária sem NA (convertendo para object)
    temp_var = df[var].astype('object').where(df[var].notna(), 'NA')

    # Contagem
    tabela = (
        pd.DataFrame({var: temp_var, desfecho: df[desfecho]})
        .groupby([var, desfecho], dropna=False)
        .size()
        .rename("Frequência Absoluta")
        .reset_index()
    )

    # Frequência relativa
    tabela["Frequência Relativa (%)"] = (
        tabela["Frequência Absoluta"]
        / tabela.groupby(var)["Frequência Absoluta"].transform("sum")
        * 100
    ).round(2)

    resultados[var] = tabela

# Exibir
for var, tabela in resultados.items():
    print(f"\n==== Variável: {var} ====")
    print(tabela)

==== Variável: cs_sexo ====
  cs_sexo  cura  Frequência Absoluta  Frequência Relativa (%)
0     0.0     0                  550                     7.43
1     0.0     1                 6854                    92.57
2     1.0     0                 2176                    13.85
3     1.0     1                13539                    86.15
4      NA     1                    2                   100.00

==== Variável: faixa_etaria ====
  faixa_etaria  cura  Frequência Absoluta  Frequência Relativa (%)
0          0.0     0                  215                    10.44
1          0.0     1                 1844                    89.56
2          1.0     0                 1763                    15.62
3          1.0     1                 9525                    84.38
4          2.0     0                  607                     9.10
5          2.0     1                 6063                    90.90
6          3.0     0                  140                     4.54
7          3.0     1                 2944                    95.46
8           NA     0                    1                     5.00
9           NA     1                   19                    95.00

==== Variável: cs_raca ====
   cs_raca  cura  Frequência Absoluta  Frequência Relativa (%)
0      1.0     0                  459                     7.61
1      1.0     1                 5570                    92.39
2      2.0     0                  723                    14.25
3      2.0     1                 4351                    85.75
4      3.0     0                   23                    11.62
5      3.0     1                  175                    88.38
6      4.0     0                 1329                    12.61
7      4.0     1                 9213                    87.39
8      5.0     0                    5                    13.51
9      5.0     1                   32                    86.49
10      NA     0                  187                    15.07
11      NA     1                 1054                    84.93

==== Variável: escola_faixa ====
  escola_faixa  cura  Frequência Absoluta  Frequência Relativa (%)
0          0.0     0                 1851                    13.19
1          0.0     1                12180                    86.81
2          1.0     0                  330                     6.16
3          1.0     1                 5023                    93.84
4         10.0     0                   30                    14.42
5         10.0     1                  178                    85.58
6           NA     0                  515                    14.59
7           NA     1                 3014                    85.41

==== Variável: contato_5_15 ====
  contato_5_15  cura  Frequência Absoluta  Frequência Relativa (%)
0          0.0     0                 2458                    11.70
1          0.0     1                18554                    88.30
2          1.0     0                  217                    12.05
3          1.0     1                 1584                    87.95
4          2.0     0                   35                    17.59
5          2.0     1                  164                    82.41
6           NA     0                   16                    14.68
7           NA     1                   93                    85.32

==== Variável: pop_rua ====
  pop_rua  cura  Frequência Absoluta  Frequência Relativa (%)
0     0.0     0                 2433                    11.15
1     0.0     1                19380                    88.85
2     1.0     0                  167                    32.75
3     1.0     1                  343                    67.25
4      NA     0                  126                    15.79
5      NA     1                  672                    84.21

==== Variável: pop_liber ====
  pop_liber  cura  Frequência Absoluta  Frequência Relativa (%)
0       0.0     0                 2370                    11.33
1       0.0     1                18539                    88.67
2       1.0     0                  292                    17.35
3       1.0     1                 1391                    82.65
4        NA     0                   64                    12.10
5        NA     1                  465                    87.90

==== Variável: pop_imig ====
  pop_imig  cura  Frequência Absoluta  Frequência Relativa (%)
0      0.0     0                 2567                    11.59
1      0.0     1                19580                    88.41
2      1.0     0                   11                    13.75
3      1.0     1                   69                    86.25
4       NA     0                  148                    16.55
5       NA     1                  746                    83.45

==== Variável: benef_gov ====
  benef_gov  cura  Frequência Absoluta  Frequência Relativa (%)
0       0.0     0                 2116                    11.76
1       0.0     1                15873                    88.24
2       1.0     0                  214                     9.65
3       1.0     1                 2003                    90.35
4        NA     0                  396                    13.58
5        NA     1                 2519                    86.42

==== Variável: agravtabac ====
  agravtabac  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 1374                     8.73
1        0.0     1                14371                    91.27
2        1.0     0                 1074                    17.85
3        1.0     1                 4943                    82.15
4         NA     0                  278                    20.46
5         NA     1                 1081                    79.54

==== Variável: agravalcoo ====
  agravalcoo  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 1911                    10.30
1        0.0     1                16649                    89.70
2        1.0     0                  554                    16.88
3        1.0     1                 2728                    83.12
4         NA     0                  261                    20.41
5         NA     1                 1018                    79.59

==== Variável: agravdroga ====
  agravdroga  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 1568                     8.64
1        0.0     1                16574                    91.36
2        1.0     0                  881                    24.73
3        1.0     1                 2682                    75.27
4         NA     0                  277                    19.56
5         NA     1                 1139                    80.44

==== Variável: agravdiabe ====
  agravdiabe  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 2343                    11.93
1        0.0     1                17303                    88.07
2        1.0     0                  120                     5.43
3        1.0     1                 2088                    94.57
4         NA     0                  263                    20.76
5         NA     1                 1004                    79.24

==== Variável: agravdoenc ====
  agravdoenc  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                 2355                    11.14
1        0.0     1                18790                    88.86
2        1.0     0                   93                    15.27
3        1.0     1                  516                    84.73
4         NA     0                  278                    20.34
5         NA     1                 1089                    79.66

==== Variável: tempo_diag_trat_14 ====
   tempo_diag_trat_14  cura  Frequência Absoluta  Frequência Relativa (%)
0                 0.0     0                 2592                    11.66
1                 0.0     1                19647                    88.34
2                 1.0     0                  134                    15.19
3                 1.0     1                  748                    84.81

==== Variável: raiox_tora ====
  raiox_tora  cura  Frequência Absoluta  Frequência Relativa (%)
0        1.0     0                 2246                    11.40
1        1.0     1                17461                    88.60
2        2.0     0                   39                     6.94
3        2.0     1                  523                    93.06
4        4.0     0                  427                    15.43
5        4.0     1                 2340                    84.57
6         NA     0                   14                    16.47
7         NA     1                   71                    83.53

==== Variável: cultura_es ====
   cultura_es  cura  Frequência Absoluta  Frequência Relativa (%)
0         1.0     0                 1148                    11.23
1         1.0     1                 9071                    88.77
2         2.0     0                  129                     7.47
3         2.0     1                 1599                    92.53
4         3.0     0                    9                     6.08
5         3.0     1                  139                    93.92
6         4.0     0                 1440                    13.06
7         4.0     1                 9586                    86.94

==== Variável: bacilosc_e ====
   bacilosc_e  cura  Frequência Absoluta  Frequência Relativa (%)
0         1.0     0                 1669                    11.47
1         1.0     1                12886                    88.53
2         2.0     0                  178                     8.59
3         2.0     1                 1895                    91.41
4         3.0     0                  879                    13.54
5         3.0     1                 5614                    86.46

==== Variável: bacilosc_2 ====
  bacilosc_2  cura  Frequência Absoluta  Frequência Relativa (%)
0        1.0     0                  147                    10.43
1        1.0     1                 1262                    89.57
2        2.0     0                  434                     6.62
3        2.0     1                 6121                    93.38
4        3.0     0                 1401                    12.65
5        3.0     1                 9671                    87.35
6         NA     0                  744                    18.21
7         NA     1                 3341                    81.79

==== Variável: bacilosc_4 ====
  bacilosc_4  cura  Frequência Absoluta  Frequência Relativa (%)
0        1.0     0                   24                    10.26
1        1.0     1                  210                    89.74
2        2.0     0                  224                     4.86
3        2.0     1                 4382                    95.14
4        3.0     0                 1344                    10.31
5        3.0     1                11687                    89.69
6         NA     0                 1134                    21.60
7         NA     1                 4116                    78.40

==== Variável: tratsup_at ====
  tratsup_at  cura  Frequência Absoluta  Frequência Relativa (%)
0        1.0     0                 1125                     9.15
1        1.0     1                11175                    90.85
2        2.0     0                 1116                    13.60
3        2.0     1                 7088                    86.40
4         NA     0                  485                    18.53
5         NA     1                 2132                    81.47

==== Variável: front ====
   front  cura  Frequência Absoluta  Frequência Relativa (%)
0      0     0                 2726                    11.79
1      0     1                20395                    88.21

==== Variável: ano_inctr_grupo ====
  ano_inctr_grupo  cura  Frequência Absoluta  Frequência Relativa (%)
0       2015-2022     0                 2240                    12.03
1       2015-2022     1                16387                    87.97
2       2023-2024     0                  486                    10.81
3       2023-2024     1                 4008                    89.19

==== Variável: ano_enc_grupo ====
  ano_enc_grupo  cura  Frequência Absoluta  Frequência Relativa (%)
0     2015-2022     0                 1998                    12.19
1     2015-2022     1                14391                    87.81
2     2023-2024     0                  728                    10.81
3     2023-2024     1                 6004                    89.19

==== Variável: pop_grupo ====
          pop_grupo  cura  Frequência Absoluta  Frequência Relativa (%)
0  300000 a 1000000     0                  867                    13.32
1  300000 a 1000000     1                 5643                    86.68
2          < 300000     0                  151                    10.07
3          < 300000     1                 1348                    89.93
4          >1000000     0                 1708                    11.30
5          >1000000     1                13401                    88.70
6                NA     1                    3                   100.00