In [1]:
#mount google colab
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
#Definindo semente

In [3]:
#instalação das bibliotecas não nativas no Colab
!pip install boruta shap
!pip install xgboost
!pip install lightgbm
!pip install catboost
!pip install tabpfn

Collecting boruta
  Downloading Boruta-0.4.3-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: shap in /usr/local/lib/python3.13/dist-packages (0.52.0)
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python3.13/dist-packages (from boruta) (2.1.3)
Requirement already satisfied: scikit-learn>=0.17.1 in /usr/local/lib/python3.13/dist-packages (from boruta) (1.6.1)
Requirement already satisfied: scipy>=0.17.0 in /usr/local/lib/python3.13/dist-packages (from boruta) (1.16.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from shap) (2.2.3)
Requirement already satisfied: tqdm>=4.27.0 in /usr/local/lib/python3.13/dist-packages (from shap) (4.67.3)
Requirement already satisfied: packaging>20.9 in /usr/local/lib/python3.13/dist-packages (from shap) (26.3)
Requirement already satisfied: slicer==0.0.8 in /usr/local/lib/python3.13/dist-packages (from shap) (0.0.8)
Requirement already satisfied: numba in /usr/local/lib/python3.13/dist-packages (from shap) (0.61.2)
Requirement already satisfied: llvmlite in /usr/local/lib/python3.13/dist-packages (from shap) (0.44.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.13/dist-packages (from shap) (3.1.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.17.1->boruta) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.17.1->boruta) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->shap) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->shap) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->shap) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->shap) (1.17.0)
Downloading Boruta-0.4.3-py3-none-any.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.9/57.9 kB 3.3 MB/s eta 0:00:00
Installing collected packages: boruta
Successfully installed boruta-0.4.3
Requirement already satisfied: xgboost in /usr/local/lib/python3.13/dist-packages (3.4.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from xgboost) (1.16.3)
Requirement already satisfied: nvidia-nccl-cu13 in /usr/local/lib/python3.13/dist-packages (from xgboost) (2.31.2)
Requirement already satisfied: lightgbm in /usr/local/lib/python3.13/dist-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from lightgbm) (2.1.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from lightgbm) (1.16.3)
Collecting catboost
  Downloading catboost-1.2.10-cp313-cp313-manylinux2014_x86_64.whl.metadata (1.4 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.13/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.1.3)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.2.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.13/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.13/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp313-cp313-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.2 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10
Collecting tabpfn
  Downloading tabpfn-8.5.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: torch>=2.5 in /usr/local/lib/python3.13/dist-packages (from tabpfn) (2.11.0+cpu)
Requirement already satisfied: safetensors>=0.4.0 in /usr/local/lib/python3.13/dist-packages (from tabpfn) (0.8.0)
Requirement already satisfied: numpy>=1.21.6 in /usr/local/lib/python3.13/dist-packages (from tabpfn) (2.1.3)
Requirement already satisfied: scikit-learn>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from tabpfn) (1.6.1)
Requirement already satisfied: typing_extensions>=4.12.0 in /usr/local/lib/python3.13/dist-packages (from tabpfn) (4.16.0)
Requirement already satisfied: scipy>=1.11.1 in /usr/local/lib/python3.13/dist-packages (from tabpfn) (1.16.3)
Requirement already satisfied: pandas>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from tabpfn) (2.2.3)
Requirement already satisfied: einops>=0.4.0 in /usr/local/lib/python3.13/dist-packages (from tabpfn) (0.8.2)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from tabpfn) (1.29.0)
Requirement already satisfied: pydantic>=2.8.0 in /usr/local/lib/python3.13/dist-packages (from tabpfn) (2.13.5)
Collecting pydantic-settings>=2.10.1 (from tabpfn)
  Downloading pydantic_settings-2.15.0-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from tabpfn) (1.6.0)
Requirement already satisfied: tqdm>=4.66.0 in /usr/local/lib/python3.13/dist-packages (from tabpfn) (4.67.3)
Requirement already satisfied: filelock>=3.11.0 in /usr/local/lib/python3.13/dist-packages (from tabpfn) (3.32.5)
Requirement already satisfied: lightgbm>=4.4 in /usr/local/lib/python3.13/dist-packages (from tabpfn) (4.6.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->tabpfn) (8.5.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->tabpfn) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->tabpfn) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->tabpfn) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->tabpfn) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->tabpfn) (6.0.3)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->tabpfn) (3.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.4.0->tabpfn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.4.0->tabpfn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.4.0->tabpfn) (2026.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.8.0->tabpfn) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.8.0->tabpfn) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.8.0->tabpfn) (0.4.4)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.13/dist-packages (from pydantic-settings>=2.10.1->tabpfn) (1.2.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.2.0->tabpfn) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=2.5->tabpfn) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.5->tabpfn) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.5->tabpfn) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=2.5->tabpfn) (3.1.6)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->tabpfn) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->tabpfn) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->tabpfn) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->tabpfn) (3.19)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->tabpfn) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->tabpfn) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=2.5->tabpfn) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=2.5->tabpfn) (3.0.3)
Downloading tabpfn-8.5.0-py3-none-any.whl (771 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 771.2/771.2 kB 28.4 MB/s eta 0:00:00
Downloading pydantic_settings-2.15.0-py3-none-any.whl (69 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 kB 3.9 MB/s eta 0:00:00
Installing collected packages: pydantic-settings, tabpfn
Successfully installed pydantic-settings-2.15.0 tabpfn-8.5.0

In [4]:
def set_seed(seed=42):
    import random
    import numpy as np
    random.seed(seed)
    np.random.seed(seed)

    try:
        import torch
        torch.manual_seed(seed)
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False
    except ImportError:
        pass

    try:
        import tensorflow as tf
        tf.random.set_seed(seed)
    except ImportError:
        pass

In [5]:
#manipulação de dados
import pandas as pd
import numpy as np

#deepcopy
from copy import deepcopy

#modelos que iremos aplicar nos dados
from xgboost import XGBClassifier

#obtenção do grid e randomized search
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import roc_curve, auc

#visualização de dados
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt

#seleção das variáveis
from boruta import BorutaPy

#importancia das variaveis
import shap

#definição de seed para reprodutibilidade
seed = 42

In [6]:
# Instalando pacotes

In [7]:
!pip install dfply
!pip install scikit-plot
!pip install graphviz
!pip install dtreeviz
!pip install imbalanced-learn
!pip install pycalib

Collecting dfply
  Downloading dfply-0.3.3-py3-none-any.whl.metadata (452 bytes)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from dfply) (2.1.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from dfply) (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->dfply) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->dfply) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->dfply) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->dfply) (1.17.0)
Downloading dfply-0.3.3-py3-none-any.whl (612 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 612.4/612.4 kB 24.1 MB/s eta 0:00:00
Installing collected packages: dfply
Successfully installed dfply-0.3.3
Collecting scikit-plot
  Downloading scikit_plot-0.3.7-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: matplotlib>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from scikit-plot) (3.10.0)
Requirement already satisfied: scikit-learn>=0.18 in /usr/local/lib/python3.13/dist-packages (from scikit-plot) (1.6.1)
Requirement already satisfied: scipy>=0.9 in /usr/local/lib/python3.13/dist-packages (from scikit-plot) (1.16.3)
Requirement already satisfied: joblib>=0.10 in /usr/local/lib/python3.13/dist-packages (from scikit-plot) (1.6.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=0.10->scikit-plot) (3.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=1.4.0->scikit-plot) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=1.4.0->scikit-plot) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=1.4.0->scikit-plot) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=1.4.0->scikit-plot) (1.5.1)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=1.4.0->scikit-plot) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=1.4.0->scikit-plot) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=1.4.0->scikit-plot) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=1.4.0->scikit-plot) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=1.4.0->scikit-plot) (2.9.0.post0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.18->scikit-plot) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib>=1.4.0->scikit-plot) (1.17.0)
Downloading scikit_plot-0.3.7-py3-none-any.whl (33 kB)
Installing collected packages: scikit-plot
Successfully installed scikit-plot-0.3.7
Requirement already satisfied: graphviz in /usr/local/lib/python3.13/dist-packages (0.21)
Collecting dtreeviz
  Downloading dtreeviz-2.3.2-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: graphviz>=0.9 in /usr/local/lib/python3.13/dist-packages (from dtreeviz) (0.21)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from dtreeviz) (2.2.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from dtreeviz) (2.1.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (from dtreeviz) (1.6.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (from dtreeviz) (3.10.0)
Collecting colour (from dtreeviz)
  Downloading colour-0.1.5-py2.py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dtreeviz) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dtreeviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dtreeviz) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dtreeviz) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dtreeviz) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dtreeviz) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dtreeviz) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib->dtreeviz) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->dtreeviz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->dtreeviz) (2026.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->dtreeviz) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->dtreeviz) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->dtreeviz) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn->dtreeviz) (3.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib->dtreeviz) (1.17.0)
Downloading dtreeviz-2.3.2-py3-none-any.whl (102 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.3/102.3 kB 6.7 MB/s eta 0:00:00
Downloading colour-0.1.5-py2.py3-none-any.whl (23 kB)
Installing collected packages: colour, dtreeviz
Successfully installed colour-0.1.5 dtreeviz-2.3.2
Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.13/dist-packages (0.14.2)
Requirement already satisfied: numpy<3,>=1.25.2 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn) (2.1.3)
Requirement already satisfied: scipy<2,>=1.11.4 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn) (1.6.1)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.6 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn) (0.1.6)
Requirement already satisfied: joblib<2,>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn) (1.6.0)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib<2,>=1.2.0->imbalanced-learn) (3.1.2)
Collecting pycalib
  Downloading pycalib-0.1.0.dev6.tar.gz (34 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.22 in /usr/local/lib/python3.13/dist-packages (from pycalib) (2.1.3)
Requirement already satisfied: scipy>=1.6 in /usr/local/lib/python3.13/dist-packages (from pycalib) (1.16.3)
Requirement already satisfied: scikit-learn>=0.24 in /usr/local/lib/python3.13/dist-packages (from pycalib) (1.6.1)
Requirement already satisfied: matplotlib>=3.3 in /usr/local/lib/python3.13/dist-packages (from pycalib) (3.10.0)
Requirement already satisfied: statsmodels>=0.12 in /usr/local/lib/python3.13/dist-packages (from pycalib) (0.15.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3->pycalib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3->pycalib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3->pycalib) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3->pycalib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3->pycalib) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3->pycalib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3->pycalib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3->pycalib) (2.9.0.post0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.24->pycalib) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.24->pycalib) (3.6.0)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in /usr/local/lib/python3.13/dist-packages (from statsmodels>=0.12->pycalib) (2.2.3)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels>=0.12->pycalib) (1.0.3)
Requirement already satisfied: formulaic>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from statsmodels>=0.12->pycalib) (1.2.2)
Requirement already satisfied: interface-meta>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels>=0.12->pycalib) (2.0.1)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels>=0.12->pycalib) (2.25.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels>=0.12->pycalib) (4.16.0)
Requirement already satisfied: wrapt>=1.17.0rc1 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels>=0.12->pycalib) (2.4.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn>=0.24->pycalib) (3.1.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas!=2.1.0,>=1.4->statsmodels>=0.12->pycalib) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas!=2.1.0,>=1.4->statsmodels>=0.12->pycalib) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3->pycalib) (1.17.0)
Building wheels for collected packages: pycalib
  Building wheel for pycalib (setup.py) ... done
  Created wheel for pycalib: filename=pycalib-0.1.0.dev6-py3-none-any.whl size=37368 sha256=38f22ca57590771f035544a4bfa6b9c7cba891f72766e2637e905135259c0b9b
  Stored in directory: /root/.cache/pip/wheels/ec/b5/10/93c91bf324e855f115998634a7f6091b62d7a6a32d6e62c05b
Successfully built pycalib
Installing collected packages: pycalib
Successfully installed pycalib-0.1.0.dev6

In [8]:
# Carregando pacotes

In [9]:
import pandas as pd  # processamento de bancos de dados
import numpy as np  # processamento numérico
import matplotlib.pyplot as plt  # geração de gráficos
import seaborn as sns  # geração de gráficos alternativos

#manipulação de dados
import pandas as pd
import numpy as np

#deepcopy
from copy import deepcopy

#modelos que iremos aplicar nos dados
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from tabpfn import TabPFNClassifier

#obtenção do grid e randomized search
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, FixedThresholdClassifier
from sklearn.metrics import roc_curve, precision_recall_curve, auc, classification_report, confusion_matrix
from sklearn.calibration import calibration_curve

#visualização de dados
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt

# Configuração de gráficos no notebook
%matplotlib inline
plt.rcParams["figure.figsize"] = [10, 5]
plt.style.use("fivethirtyeight")
%config InlineBackend.figure_format = 'retina'

# Configurações de fonte e matemática
from matplotlib import rc
rc('font', **{'family': 'sans-serif', 'sans-serif': ['DejaVu Sans'], 'size': 10})
rc('mathtext', **{'default': 'regular'})

#manipulação de dados
import pandas as pd
import numpy as np

#deepcopy
from copy import deepcopy

#modelos que iremos aplicar nos dados
from xgboost import XGBClassifier

#obtenção do grid e randomized search
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import roc_curve, auc

#visualização de dados
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt

#seleção das variáveis
from boruta import BorutaPy

#importancia das variaveis
import shap

# SCIKIT-LEARN

#bibliotecas do sklearn para preprocessamento
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder

from sklearn.metrics import (roc_curve, auc, confusion_matrix, classification_report,
                             precision_score, recall_score, f1_score, roc_auc_score,
                             accuracy_score, brier_score_loss)
from sklearn.model_selection import (KFold, cross_val_score, train_test_split,
                                     GridSearchCV, RandomizedSearchCV)
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.calibration import CalibratedClassifierCV
from sklearn.calibration import calibration_curve

from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

from catboost import CatBoostClassifier

from sklearn import preprocessing
from tabpfn import TabPFNClassifier

import shap

# Biblioteca dfply
from dfply import *

# Visualização de árvores de decisão
from dtreeviz.trees import *

from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, confusion_matrix
)

from collections import Counter

# Ignorar warnings
import warnings
warnings.filterwarnings("ignore")

# Definição de semente de aleatoriedade
np.random.seed(42)

#definição de seed para reprodutibilidade
seed = 42

#Etapa1

In [10]:
#Import da base de treino e teste
df_train = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Artigo1_RJ/Etapa1/dados_treino_xgb1boruta_rj_2015_2025.csv",
                        encoding='latin1', sep=",")
df_test = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Artigo1_RJ/Etapa1/dados_teste_xgb1boruta_rj_2015_2025.csv",
                        encoding='latin1', sep=",")

In [11]:
df_train.shape

(18306, 26)

In [12]:
df_train.columns

Index(['pop', 'cs_sexo_0.0', 'cs_sexo_1.0', 'cs_raca_1.0', 'cs_raca_2.0',
       'raiox_tora_4.0', 'agravalcoo_0.0', 'agravalcoo_1.0', 'agravdiabe_1.0',
       'bacilosc_e_3.0', 'pop_liber_1.0', 'pop_rua_1.0', 'benef_gov_9.0',
       'agravdroga_0.0', 'agravdroga_1.0', 'agravtabac_0.0', 'agravtabac_1.0',
       'escola_faixa_0.0', 'escola_faixa_1.0', 'escola_faixa_9.0',
       'faixa_etaria_1.0', 'agravalcoo_9.0', 'benef_gov_0.0',
       'faixa_etaria_0.0', 'faixa_etaria_2.0', 'cura'],
      dtype='object')

In [13]:
import pandas as pd

df_train["pop_grupo"] = pd.cut(
    df_train["pop"],
    bins=[-float("inf"), -1.476, -1.25, float("inf")],
    labels=['< 300000', '300000 a 1000000', '>1000000']
)


df_test["pop_grupo"] = pd.cut(
    df_test["pop"],
    bins=[-float("inf"), -1.476, -1.25, float("inf")],
    labels=['< 300000', '300000 a 1000000', '>1000000']
)

In [14]:
#Separação das bases entre X_train, X_test, y_train, y_test
X_train_novo=df_train.drop(columns = "cura")
y_train=df_train.cura
X_test_novo=df_test.drop(columns = "cura")
y_test=df_test.cura

In [15]:
#Visualização da proporção do desfecho na base de treino
y_train.value_counts(normalize=True)

cura
1    0.803671
0    0.196329
Name: proportion, dtype: float64

In [16]:
import joblib

caminho = "/content/drive/MyDrive/Colab Notebooks/Artigo1_RJ/Etapa1/best_model_xgb_novo.pkl"

xgb = joblib.load(caminho)

print("✅ Modelo carregado com sucesso")

✅ Modelo carregado com sucesso

In [17]:
data = joblib.load(caminho)

xgb = data["model_xgb_novo"]
print(data["params_xgb_novo"])
print(data["method_xgb_novo"])

{'n_estimators': 200, 'max_depth': 4, 'learning_rate': 0.06193785329107693, 'subsample': 0.8648682549169897, 'colsample_bytree': 0.6495150359640375, 'gamma': 0.1861675099363223, 'reg_alpha': 0.0021545465077712276, 'reg_lambda': 1.7162020163560698}
Optuna

In [18]:
from xgboost import XGBClassifier

# ===============================
# Criar DataFrame final de AUCs
# ===============================

params_xgb = data["params_xgb_novo"]

xgb = XGBClassifier(
    **params_xgb,
    **({"random_state": seed}
       if "random_state" not in params_xgb
       else {})
)

In [19]:
X_train = df_train.drop(columns=['cura'])
y_train = df_train['cura']

xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.6495150359640375, device=None,
              early_stopping_rounds=None, enable_categorical=True,
              eval_metric=None, feature_types=None, feature_weights=None,
              gamma=0.1861675099363223, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.06193785329107693,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [20]:
print(X_train.shape)
print(y_train.shape)
print(y_train.value_counts(normalize=True))

(18306, 26)
(18306,)
cura
1    0.803671
0    0.196329
Name: proportion, dtype: float64

In [21]:
X_test_model = X_test_novo.copy()

y_prob = xgb.predict_proba(X_test_model)[:, 1]

In [22]:
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score
from sklearn.utils import resample


def auc_por_subgrupo_com_ic(X_test, y_test, y_prob, coluna, n_boot=2000, seed=42):

    df = X_test.copy()
    df = df.copy()

    df["y_true"] = np.array(y_test)
    df["y_prob"] = np.array(y_prob)

    resultados = []

    for g in df[coluna].dropna().unique():

        sub = df[df[coluna] == g]

        y_true = sub["y_true"].values
        y_prob_sub = sub["y_prob"].values

        # precisa de pelo menos 2 classes
        if len(np.unique(y_true)) < 2:
            resultados.append({
                "Subgrupo": coluna,
                "Categoria": g,
                "N": len(sub),
                "AUC-ROC": np.nan,
                "IC95%_inferior": np.nan,
                "IC95%_superior": np.nan
            })
            continue

        # AUC original
        auc_original = roc_auc_score(y_true, y_prob_sub)

        # Bootstrap
        aucs = []

        rng = np.random.default_rng(seed)  # garante reprodutibilidade SEM travar o bootstrap

        n = len(y_true)

        for _ in range(n_boot):

            idx = rng.integers(0, n, n)

            y_true_b = y_true[idx]
            y_prob_b = y_prob_sub[idx]

            # precisa de pelo menos 2 classes no bootstrap
            if len(np.unique(y_true_b)) < 2:
                continue

            aucs.append(roc_auc_score(y_true_b, y_prob_b))

        aucs = np.array(aucs)

        ic_inf = np.percentile(aucs, 2.5)
        ic_sup = np.percentile(aucs, 97.5)

        resultados.append({
            "Subgrupo": coluna,
            "Categoria": g,
            "N": len(sub),
            "AUC-ROC": auc_original,
            "IC95%_inferior": ic_inf,
            "IC95%_superior": ic_sup
        })

    return pd.DataFrame(resultados)

In [23]:
auc_raca = auc_por_subgrupo_com_ic(
    X_test_novo,
    y_test,
    y_prob,
    "cs_raca_1.0"
)

print(auc_raca)

      Subgrupo  Categoria     N   AUC-ROC  IC95%_inferior  IC95%_superior
0  cs_raca_1.0        1.0  1716  0.691971        0.648721        0.735557
1  cs_raca_1.0        0.0  5608  0.714636        0.695539        0.731837

In [24]:
auc_raca = auc_por_subgrupo_com_ic(
    X_test_novo,
    y_test,
    y_prob,
    "cs_raca_2.0"
)

print(auc_raca)

      Subgrupo  Categoria     N   AUC-ROC  IC95%_inferior  IC95%_superior
0  cs_raca_2.0        0.0  5493  0.716401        0.696694        0.736066
1  cs_raca_2.0        1.0  1831  0.726955        0.697792        0.755179

In [25]:
auc_escola = auc_por_subgrupo_com_ic(
    X_test_novo,
    y_test,
    y_prob,
    "escola_faixa_1.0"
)

print(auc_escola)

           Subgrupo  Categoria     N   AUC-ROC  IC95%_inferior  IC95%_superior
0  escola_faixa_1.0        0.0  5459  0.711998        0.694038        0.729235
1  escola_faixa_1.0        1.0  1865  0.661034        0.613134        0.707649

In [26]:
auc_escola = auc_por_subgrupo_com_ic(
    X_test_novo,
    y_test,
    y_prob,
    "escola_faixa_0.0"
)

print(auc_escola)

           Subgrupo  Categoria     N   AUC-ROC  IC95%_inferior  IC95%_superior
0  escola_faixa_0.0        1.0  4592  0.721196        0.702561        0.739725
1  escola_faixa_0.0        0.0  2732  0.709944        0.680181        0.739478

In [27]:
auc_escola = auc_por_subgrupo_com_ic(
    X_test_novo,
    y_test,
    y_prob,
    "escola_faixa_9.0"
)

print(auc_escola)

           Subgrupo  Categoria     N   AUC-ROC  IC95%_inferior  IC95%_superior
0  escola_faixa_9.0        0.0  6533  0.725484        0.707786        0.742883
1  escola_faixa_9.0        1.0   791  0.666617        0.618911        0.714347

In [28]:
auc_pop = auc_por_subgrupo_com_ic(
    X_test_novo,
    y_test,
    y_prob,
    "pop_grupo"
)

print(auc_pop)

    Subgrupo         Categoria     N   AUC-ROC  IC95%_inferior  IC95%_superior
0  pop_grupo  300000 a 1000000  1571  0.729456        0.696453        0.760640
1  pop_grupo          >1000000  5021  0.718654        0.699100        0.739469
2  pop_grupo          < 300000   732  0.678232        0.624534        0.730951

#Etapa2

In [29]:
#Import da base de treino e teste
df_train = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Artigo1_RJ/Etapa2/dados_treino_cat2boruta_rj_2015_2025.csv",
                        encoding='latin1', sep=",")
df_test = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Artigo1_RJ/Etapa2/dados_teste_cat2boruta_rj_2015_2025.csv",
                        encoding='latin1', sep=",")

In [30]:
df_train.shape

(17448, 24)

In [31]:
df_train.columns

Index(['pop', 'cs_sexo_0.0', 'cs_sexo_1.0', 'cs_raca_1.0', 'cs_raca_2.0',
       'raiox_tora_4.0', 'agravalcoo_1.0', 'agravdiabe_1.0', 'cultura_es_2.0',
       'cultura_es_4.0', 'bacilosc_2_2.0', 'bacilosc_2_9.0', 'pop_liber_1.0',
       'pop_rua_1.0', 'agravdroga_0.0', 'agravdroga_1.0', 'agravtabac_0.0',
       'agravtabac_1.0', 'escola_faixa_0.0', 'escola_faixa_1.0',
       'faixa_etaria_1.0', 'faixa_etaria_2.0', 'faixa_etaria_3.0', 'cura'],
      dtype='object')

In [32]:
import pandas as pd

df_train["pop_grupo"] = pd.cut(
    df_train["pop"],
    bins=[-float("inf"), -1.484, -1.26, float("inf")],
    labels=['< 300000', '300000 a 1000000', '>1000000']
)


df_test["pop_grupo"] = pd.cut(
    df_test["pop"],
    bins=[-float("inf"), -1.484, -1.26, float("inf")],
    labels=['< 300000', '300000 a 1000000', '>1000000']
)

In [33]:
#Separação das bases entre X_train, X_test, y_train, y_test
X_train_novo=df_train.drop(columns = "cura")
y_train=df_train.cura
X_test_novo=df_test.drop(columns = "cura")
y_test=df_test.cura

In [34]:
#Visualização da proporção do desfecho na base de treino
y_train.value_counts(normalize=True)

cura
1    0.830754
0    0.169246
Name: proportion, dtype: float64

In [35]:
import joblib

caminho = "/content/drive/MyDrive/Colab Notebooks/Artigo1_RJ/Etapa2/best_model_cat_novo.pkl"

cat = joblib.load(caminho)

print("✅ Modelo carregado com sucesso")

✅ Modelo carregado com sucesso

In [36]:
data = joblib.load(caminho)

cat = data["model_cat_novo"]
print(data["params_cat_novo"])
print(data["method_cat_novo"])

{'n_estimators': 500, 'max_depth': 4, 'min_data_in_leaf': 5, 'subsample': 0.8680963214010124, 'reg_lambda': 1.7391886518816502}
Optuna

In [37]:
from catboost import CatBoostClassifier

# ===============================
# Criar DataFrame final de AUCs
# ===============================

params_cat = data["params_cat_novo"]

cat = CatBoostClassifier(
    **params_cat,
    **({"random_state": seed}
       if "random_state" not in params_xgb
       else {})
)

In [38]:
X_train = df_train.drop(columns=['cura'])
y_train = df_train['cura']

# Identify categorical features
cat_features = X_train.select_dtypes(include='category').columns.tolist()

cat.fit(X_train, y_train, cat_features=cat_features)

0:	learn: 0.6742170	total: 66.5ms	remaining: 33.2s
1:	learn: 0.6572377	total: 82.2ms	remaining: 20.5s
2:	learn: 0.6413791	total: 96.2ms	remaining: 15.9s
3:	learn: 0.6260334	total: 112ms	remaining: 13.9s
4:	learn: 0.6124360	total: 129ms	remaining: 12.8s
5:	learn: 0.5990961	total: 143ms	remaining: 11.8s
6:	learn: 0.5873023	total: 158ms	remaining: 11.1s
7:	learn: 0.5751725	total: 171ms	remaining: 10.5s
8:	learn: 0.5644069	total: 187ms	remaining: 10.2s
9:	learn: 0.5549289	total: 201ms	remaining: 9.87s
10:	learn: 0.5458098	total: 216ms	remaining: 9.6s
11:	learn: 0.5368286	total: 231ms	remaining: 9.39s
12:	learn: 0.5288205	total: 247ms	remaining: 9.27s
13:	learn: 0.5210671	total: 261ms	remaining: 9.07s
14:	learn: 0.5140980	total: 280ms	remaining: 9.06s
15:	learn: 0.5080836	total: 295ms	remaining: 8.93s
16:	learn: 0.5020591	total: 313ms	remaining: 8.9s
17:	learn: 0.4956206	total: 328ms	remaining: 8.78s
18:	learn: 0.4909907	total: 341ms	remaining: 8.62s
19:	learn: 0.4854394	total: 355ms	remaining: 8.53s
20:	learn: 0.4806402	total: 371ms	remaining: 8.46s
21:	learn: 0.4767284	total: 386ms	remaining: 8.39s
22:	learn: 0.4725867	total: 400ms	remaining: 8.3s
23:	learn: 0.4684512	total: 416ms	remaining: 8.25s
24:	learn: 0.4647966	total: 430ms	remaining: 8.16s
25:	learn: 0.4613300	total: 443ms	remaining: 8.07s
26:	learn: 0.4580841	total: 455ms	remaining: 7.97s
27:	learn: 0.4549047	total: 470ms	remaining: 7.93s
28:	learn: 0.4519133	total: 486ms	remaining: 7.89s
29:	learn: 0.4491060	total: 501ms	remaining: 7.85s
30:	learn: 0.4463902	total: 518ms	remaining: 7.83s
31:	learn: 0.4444272	total: 535ms	remaining: 7.82s
32:	learn: 0.4420284	total: 550ms	remaining: 7.79s
33:	learn: 0.4399539	total: 564ms	remaining: 7.73s
34:	learn: 0.4379915	total: 578ms	remaining: 7.68s
35:	learn: 0.4361291	total: 595ms	remaining: 7.67s
36:	learn: 0.4343850	total: 613ms	remaining: 7.67s
37:	learn: 0.4327302	total: 640ms	remaining: 7.78s
38:	learn: 0.4312000	total: 671ms	remaining: 7.94s
39:	learn: 0.4296849	total: 689ms	remaining: 7.93s
40:	learn: 0.4284155	total: 706ms	remaining: 7.9s
41:	learn: 0.4272300	total: 723ms	remaining: 7.88s
42:	learn: 0.4259463	total: 736ms	remaining: 7.83s
43:	learn: 0.4246931	total: 750ms	remaining: 7.78s
44:	learn: 0.4235377	total: 770ms	remaining: 7.78s
45:	learn: 0.4222700	total: 784ms	remaining: 7.74s
46:	learn: 0.4213163	total: 799ms	remaining: 7.7s
47:	learn: 0.4202840	total: 812ms	remaining: 7.64s
48:	learn: 0.4194943	total: 824ms	remaining: 7.58s
49:	learn: 0.4185803	total: 837ms	remaining: 7.53s
50:	learn: 0.4177877	total: 853ms	remaining: 7.51s
51:	learn: 0.4170506	total: 871ms	remaining: 7.51s
52:	learn: 0.4163994	total: 897ms	remaining: 7.56s
53:	learn: 0.4155893	total: 926ms	remaining: 7.65s
54:	learn: 0.4148673	total: 942ms	remaining: 7.62s
55:	learn: 0.4141740	total: 962ms	remaining: 7.63s
56:	learn: 0.4134816	total: 978ms	remaining: 7.6s
57:	learn: 0.4128992	total: 993ms	remaining: 7.56s
58:	learn: 0.4123033	total: 1s	remaining: 7.52s
59:	learn: 0.4117952	total: 1.02s	remaining: 7.48s
60:	learn: 0.4113495	total: 1.03s	remaining: 7.45s
61:	learn: 0.4107921	total: 1.05s	remaining: 7.4s
62:	learn: 0.4102842	total: 1.06s	remaining: 7.38s
63:	learn: 0.4097884	total: 1.08s	remaining: 7.34s
64:	learn: 0.4093860	total: 1.09s	remaining: 7.29s
65:	learn: 0.4089897	total: 1.1s	remaining: 7.27s
66:	learn: 0.4086126	total: 1.12s	remaining: 7.25s
67:	learn: 0.4081041	total: 1.14s	remaining: 7.24s
68:	learn: 0.4076904	total: 1.15s	remaining: 7.2s
69:	learn: 0.4073016	total: 1.17s	remaining: 7.18s
70:	learn: 0.4068677	total: 1.18s	remaining: 7.15s
71:	learn: 0.4065167	total: 1.2s	remaining: 7.11s
72:	learn: 0.4061879	total: 1.21s	remaining: 7.08s
73:	learn: 0.4058428	total: 1.23s	remaining: 7.05s
74:	learn: 0.4055485	total: 1.24s	remaining: 7.04s
75:	learn: 0.4052361	total: 1.25s	remaining: 7s
76:	learn: 0.4049408	total: 1.27s	remaining: 6.99s
77:	learn: 0.4047134	total: 1.29s	remaining: 6.96s
78:	learn: 0.4043333	total: 1.3s	remaining: 6.93s
79:	learn: 0.4041877	total: 1.32s	remaining: 6.91s
80:	learn: 0.4038811	total: 1.33s	remaining: 6.9s
81:	learn: 0.4035467	total: 1.35s	remaining: 6.89s
82:	learn: 0.4032775	total: 1.37s	remaining: 6.88s
83:	learn: 0.4030164	total: 1.39s	remaining: 6.87s
84:	learn: 0.4028196	total: 1.4s	remaining: 6.85s
85:	learn: 0.4025759	total: 1.42s	remaining: 6.83s
86:	learn: 0.4023422	total: 1.43s	remaining: 6.79s
87:	learn: 0.4021472	total: 1.44s	remaining: 6.76s
88:	learn: 0.4018842	total: 1.46s	remaining: 6.74s
89:	learn: 0.4016619	total: 1.47s	remaining: 6.7s
90:	learn: 0.4015629	total: 1.48s	remaining: 6.67s
91:	learn: 0.4013721	total: 1.5s	remaining: 6.64s
92:	learn: 0.4011729	total: 1.51s	remaining: 6.62s
93:	learn: 0.4009852	total: 1.53s	remaining: 6.62s
94:	learn: 0.4008760	total: 1.55s	remaining: 6.6s
95:	learn: 0.4007669	total: 1.56s	remaining: 6.59s
96:	learn: 0.4005548	total: 1.58s	remaining: 6.57s
97:	learn: 0.4004331	total: 1.6s	remaining: 6.55s
98:	learn: 0.4002685	total: 1.61s	remaining: 6.52s
99:	learn: 0.4001008	total: 1.62s	remaining: 6.5s
100:	learn: 0.3999064	total: 1.64s	remaining: 6.47s
101:	learn: 0.3997444	total: 1.65s	remaining: 6.46s
102:	learn: 0.3996083	total: 1.68s	remaining: 6.46s
103:	learn: 0.3994816	total: 1.7s	remaining: 6.49s
104:	learn: 0.3993849	total: 1.72s	remaining: 6.47s
105:	learn: 0.3991761	total: 1.73s	remaining: 6.45s
106:	learn: 0.3990270	total: 1.75s	remaining: 6.42s
107:	learn: 0.3989389	total: 1.76s	remaining: 6.4s
108:	learn: 0.3988001	total: 1.78s	remaining: 6.38s
109:	learn: 0.3987016	total: 1.8s	remaining: 6.37s
110:	learn: 0.3985820	total: 1.81s	remaining: 6.34s
111:	learn: 0.3984492	total: 1.82s	remaining: 6.32s
112:	learn: 0.3982859	total: 1.84s	remaining: 6.29s
113:	learn: 0.3981927	total: 1.85s	remaining: 6.27s
114:	learn: 0.3980618	total: 1.87s	remaining: 6.25s
115:	learn: 0.3979378	total: 1.88s	remaining: 6.23s
116:	learn: 0.3979109	total: 1.89s	remaining: 6.19s
117:	learn: 0.3978131	total: 1.91s	remaining: 6.17s
118:	learn: 0.3976612	total: 1.92s	remaining: 6.15s
119:	learn: 0.3975173	total: 1.93s	remaining: 6.12s
120:	learn: 0.3974106	total: 1.95s	remaining: 6.11s
121:	learn: 0.3972831	total: 1.97s	remaining: 6.09s
122:	learn: 0.3971939	total: 1.98s	remaining: 6.08s
123:	learn: 0.3970268	total: 2s	remaining: 6.07s
124:	learn: 0.3969533	total: 2.02s	remaining: 6.06s
125:	learn: 0.3968324	total: 2.03s	remaining: 6.04s
126:	learn: 0.3967524	total: 2.05s	remaining: 6.02s
127:	learn: 0.3966734	total: 2.06s	remaining: 5.99s
128:	learn: 0.3965818	total: 2.08s	remaining: 5.97s
129:	learn: 0.3964785	total: 2.09s	remaining: 5.95s
130:	learn: 0.3963843	total: 2.11s	remaining: 5.94s
131:	learn: 0.3962294	total: 2.12s	remaining: 5.92s
132:	learn: 0.3961292	total: 2.14s	remaining: 5.9s
133:	learn: 0.3960312	total: 2.15s	remaining: 5.88s
134:	learn: 0.3959504	total: 2.17s	remaining: 5.86s
135:	learn: 0.3958650	total: 2.19s	remaining: 5.85s
136:	learn: 0.3957803	total: 2.2s	remaining: 5.83s
137:	learn: 0.3957580	total: 2.21s	remaining: 5.81s
138:	learn: 0.3956537	total: 2.23s	remaining: 5.78s
139:	learn: 0.3955670	total: 2.24s	remaining: 5.76s
140:	learn: 0.3954707	total: 2.25s	remaining: 5.74s
141:	learn: 0.3953872	total: 2.27s	remaining: 5.71s
142:	learn: 0.3953056	total: 2.28s	remaining: 5.69s
143:	learn: 0.3952384	total: 2.29s	remaining: 5.67s
144:	learn: 0.3951667	total: 2.31s	remaining: 5.64s
145:	learn: 0.3950695	total: 2.32s	remaining: 5.62s
146:	learn: 0.3950235	total: 2.33s	remaining: 5.6s
147:	learn: 0.3949670	total: 2.34s	remaining: 5.58s
148:	learn: 0.3949173	total: 2.36s	remaining: 5.57s
149:	learn: 0.3949042	total: 2.37s	remaining: 5.54s
150:	learn: 0.3948215	total: 2.39s	remaining: 5.53s
151:	learn: 0.3947396	total: 2.41s	remaining: 5.51s
152:	learn: 0.3946741	total: 2.42s	remaining: 5.5s
153:	learn: 0.3945820	total: 2.44s	remaining: 5.49s
154:	learn: 0.3945093	total: 2.46s	remaining: 5.46s
155:	learn: 0.3944147	total: 2.47s	remaining: 5.45s
156:	learn: 0.3942991	total: 2.48s	remaining: 5.43s
157:	learn: 0.3942279	total: 2.5s	remaining: 5.41s
158:	learn: 0.3941434	total: 2.51s	remaining: 5.39s
159:	learn: 0.3941185	total: 2.52s	remaining: 5.36s
160:	learn: 0.3940573	total: 2.54s	remaining: 5.35s
161:	learn: 0.3939549	total: 2.55s	remaining: 5.32s
162:	learn: 0.3938947	total: 2.57s	remaining: 5.31s
163:	learn: 0.3938338	total: 2.58s	remaining: 5.29s
164:	learn: 0.3937868	total: 2.6s	remaining: 5.28s
165:	learn: 0.3937490	total: 2.62s	remaining: 5.27s
166:	learn: 0.3936896	total: 2.63s	remaining: 5.25s
167:	learn: 0.3936031	total: 2.65s	remaining: 5.24s
168:	learn: 0.3935241	total: 2.67s	remaining: 5.22s
169:	learn: 0.3934821	total: 2.68s	remaining: 5.2s
170:	learn: 0.3934592	total: 2.69s	remaining: 5.18s
171:	learn: 0.3933823	total: 2.72s	remaining: 5.19s
172:	learn: 0.3933397	total: 2.74s	remaining: 5.19s
173:	learn: 0.3932981	total: 2.76s	remaining: 5.17s
174:	learn: 0.3932523	total: 2.78s	remaining: 5.16s
175:	learn: 0.3932139	total: 2.8s	remaining: 5.16s
176:	learn: 0.3932027	total: 2.82s	remaining: 5.14s
177:	learn: 0.3931416	total: 2.83s	remaining: 5.13s
178:	learn: 0.3931359	total: 2.85s	remaining: 5.11s
179:	learn: 0.3930862	total: 2.86s	remaining: 5.09s
180:	learn: 0.3930217	total: 2.88s	remaining: 5.07s
181:	learn: 0.3929608	total: 2.89s	remaining: 5.06s
182:	learn: 0.3929261	total: 2.91s	remaining: 5.04s
183:	learn: 0.3929261	total: 2.92s	remaining: 5.01s
184:	learn: 0.3928861	total: 2.93s	remaining: 4.99s
185:	learn: 0.3928672	total: 2.95s	remaining: 4.98s
186:	learn: 0.3928258	total: 2.96s	remaining: 4.96s
187:	learn: 0.3927679	total: 2.98s	remaining: 4.94s
188:	learn: 0.3927141	total: 3s	remaining: 4.93s
189:	learn: 0.3926697	total: 3.01s	remaining: 4.92s
190:	learn: 0.3926016	total: 3.03s	remaining: 4.9s
191:	learn: 0.3925531	total: 3.05s	remaining: 4.89s
192:	learn: 0.3924909	total: 3.06s	remaining: 4.87s
193:	learn: 0.3924589	total: 3.08s	remaining: 4.86s
194:	learn: 0.3923915	total: 3.1s	remaining: 4.84s
195:	learn: 0.3923794	total: 3.11s	remaining: 4.82s
196:	learn: 0.3922941	total: 3.12s	remaining: 4.8s
197:	learn: 0.3922807	total: 3.13s	remaining: 4.78s
198:	learn: 0.3922160	total: 3.15s	remaining: 4.77s
199:	learn: 0.3921718	total: 3.17s	remaining: 4.75s
200:	learn: 0.3921556	total: 3.18s	remaining: 4.73s
201:	learn: 0.3920752	total: 3.19s	remaining: 4.71s
202:	learn: 0.3919941	total: 3.21s	remaining: 4.69s
203:	learn: 0.3919556	total: 3.22s	remaining: 4.68s
204:	learn: 0.3919045	total: 3.24s	remaining: 4.67s
205:	learn: 0.3918576	total: 3.26s	remaining: 4.65s
206:	learn: 0.3918162	total: 3.27s	remaining: 4.63s
207:	learn: 0.3917459	total: 3.29s	remaining: 4.62s
208:	learn: 0.3917213	total: 3.3s	remaining: 4.6s
209:	learn: 0.3916904	total: 3.32s	remaining: 4.58s
210:	learn: 0.3916427	total: 3.33s	remaining: 4.57s
211:	learn: 0.3916170	total: 3.35s	remaining: 4.55s
212:	learn: 0.3915845	total: 3.37s	remaining: 4.53s
213:	learn: 0.3915421	total: 3.38s	remaining: 4.51s
214:	learn: 0.3915353	total: 3.39s	remaining: 4.49s
215:	learn: 0.3915059	total: 3.4s	remaining: 4.47s
216:	learn: 0.3914586	total: 3.42s	remaining: 4.45s
217:	learn: 0.3914411	total: 3.43s	remaining: 4.44s
218:	learn: 0.3914234	total: 3.44s	remaining: 4.42s
219:	learn: 0.3913946	total: 3.46s	remaining: 4.4s
220:	learn: 0.3913460	total: 3.48s	remaining: 4.39s
221:	learn: 0.3913095	total: 3.49s	remaining: 4.37s
222:	learn: 0.3912955	total: 3.51s	remaining: 4.36s
223:	learn: 0.3912763	total: 3.52s	remaining: 4.34s
224:	learn: 0.3912519	total: 3.54s	remaining: 4.33s
225:	learn: 0.3912277	total: 3.56s	remaining: 4.31s
226:	learn: 0.3911994	total: 3.59s	remaining: 4.32s
227:	learn: 0.3911715	total: 3.62s	remaining: 4.32s
228:	learn: 0.3911492	total: 3.64s	remaining: 4.31s
229:	learn: 0.3911019	total: 3.66s	remaining: 4.29s
230:	learn: 0.3910503	total: 3.67s	remaining: 4.28s
231:	learn: 0.3910050	total: 3.69s	remaining: 4.26s
232:	learn: 0.3909724	total: 3.71s	remaining: 4.25s
233:	learn: 0.3909364	total: 3.72s	remaining: 4.23s
234:	learn: 0.3909260	total: 3.75s	remaining: 4.23s
235:	learn: 0.3909217	total: 3.78s	remaining: 4.22s
236:	learn: 0.3909051	total: 3.79s	remaining: 4.21s
237:	learn: 0.3908778	total: 3.81s	remaining: 4.2s
238:	learn: 0.3908476	total: 3.83s	remaining: 4.18s
239:	learn: 0.3908009	total: 3.84s	remaining: 4.17s
240:	learn: 0.3907630	total: 3.86s	remaining: 4.14s
241:	learn: 0.3907312	total: 3.87s	remaining: 4.13s
242:	learn: 0.3907277	total: 3.89s	remaining: 4.12s
243:	learn: 0.3907085	total: 3.9s	remaining: 4.1s
244:	learn: 0.3906953	total: 3.92s	remaining: 4.08s
245:	learn: 0.3906792	total: 3.93s	remaining: 4.06s
246:	learn: 0.3906713	total: 3.95s	remaining: 4.04s
247:	learn: 0.3906248	total: 3.97s	remaining: 4.03s
248:	learn: 0.3906076	total: 3.98s	remaining: 4.01s
249:	learn: 0.3905974	total: 3.99s	remaining: 3.99s
250:	learn: 0.3905602	total: 4.01s	remaining: 3.98s
251:	learn: 0.3905310	total: 4.02s	remaining: 3.96s
252:	learn: 0.3904474	total: 4.04s	remaining: 3.94s
253:	learn: 0.3904357	total: 4.05s	remaining: 3.93s
254:	learn: 0.3904172	total: 4.07s	remaining: 3.91s
255:	learn: 0.3903867	total: 4.08s	remaining: 3.89s
256:	learn: 0.3903385	total: 4.1s	remaining: 3.88s
257:	learn: 0.3903036	total: 4.12s	remaining: 3.86s
258:	learn: 0.3902882	total: 4.13s	remaining: 3.85s
259:	learn: 0.3902432	total: 4.15s	remaining: 3.83s
260:	learn: 0.3902053	total: 4.16s	remaining: 3.81s
261:	learn: 0.3901878	total: 4.18s	remaining: 3.79s
262:	learn: 0.3901779	total: 4.19s	remaining: 3.78s
263:	learn: 0.3901680	total: 4.2s	remaining: 3.76s
264:	learn: 0.3901501	total: 4.22s	remaining: 3.74s
265:	learn: 0.3900739	total: 4.23s	remaining: 3.73s
266:	learn: 0.3900302	total: 4.25s	remaining: 3.71s
267:	learn: 0.3899883	total: 4.26s	remaining: 3.69s
268:	learn: 0.3899485	total: 4.27s	remaining: 3.67s
269:	learn: 0.3899346	total: 4.29s	remaining: 3.65s
270:	learn: 0.3898879	total: 4.31s	remaining: 3.64s
271:	learn: 0.3897669	total: 4.32s	remaining: 3.63s
272:	learn: 0.3897466	total: 4.34s	remaining: 3.61s
273:	learn: 0.3897207	total: 4.35s	remaining: 3.59s
274:	learn: 0.3897077	total: 4.37s	remaining: 3.57s
275:	learn: 0.3896949	total: 4.38s	remaining: 3.56s
276:	learn: 0.3896635	total: 4.39s	remaining: 3.54s
277:	learn: 0.3896101	total: 4.41s	remaining: 3.52s
278:	learn: 0.3895380	total: 4.42s	remaining: 3.5s
279:	learn: 0.3895042	total: 4.44s	remaining: 3.49s
280:	learn: 0.3894748	total: 4.45s	remaining: 3.47s
281:	learn: 0.3894460	total: 4.47s	remaining: 3.45s
282:	learn: 0.3894146	total: 4.48s	remaining: 3.44s
283:	learn: 0.3893831	total: 4.5s	remaining: 3.42s
284:	learn: 0.3893197	total: 4.51s	remaining: 3.4s
285:	learn: 0.3892852	total: 4.52s	remaining: 3.38s
286:	learn: 0.3892780	total: 4.54s	remaining: 3.37s
287:	learn: 0.3892612	total: 4.55s	remaining: 3.35s
288:	learn: 0.3892446	total: 4.57s	remaining: 3.33s
289:	learn: 0.3892363	total: 4.58s	remaining: 3.31s
290:	learn: 0.3891980	total: 4.59s	remaining: 3.3s
291:	learn: 0.3891570	total: 4.61s	remaining: 3.28s
292:	learn: 0.3891502	total: 4.62s	remaining: 3.27s
293:	learn: 0.3891229	total: 4.64s	remaining: 3.25s
294:	learn: 0.3891175	total: 4.65s	remaining: 3.23s
295:	learn: 0.3891003	total: 4.67s	remaining: 3.21s
296:	learn: 0.3890724	total: 4.68s	remaining: 3.2s
297:	learn: 0.3890376	total: 4.7s	remaining: 3.18s
298:	learn: 0.3890140	total: 4.71s	remaining: 3.17s
299:	learn: 0.3889901	total: 4.73s	remaining: 3.15s
300:	learn: 0.3889656	total: 4.75s	remaining: 3.14s
301:	learn: 0.3889602	total: 4.76s	remaining: 3.12s
302:	learn: 0.3889372	total: 4.79s	remaining: 3.11s
303:	learn: 0.3889267	total: 4.81s	remaining: 3.1s
304:	learn: 0.3889241	total: 4.83s	remaining: 3.08s
305:	learn: 0.3888935	total: 4.84s	remaining: 3.07s
306:	learn: 0.3888547	total: 4.86s	remaining: 3.05s
307:	learn: 0.3888481	total: 4.87s	remaining: 3.04s
308:	learn: 0.3888193	total: 4.89s	remaining: 3.02s
309:	learn: 0.3887825	total: 4.91s	remaining: 3.01s
310:	learn: 0.3887632	total: 4.92s	remaining: 2.99s
311:	learn: 0.3887523	total: 4.94s	remaining: 2.98s
312:	learn: 0.3887286	total: 4.96s	remaining: 2.96s
313:	learn: 0.3886823	total: 4.98s	remaining: 2.95s
314:	learn: 0.3886209	total: 4.99s	remaining: 2.93s
315:	learn: 0.3885907	total: 5.01s	remaining: 2.92s
316:	learn: 0.3885378	total: 5.02s	remaining: 2.9s
317:	learn: 0.3885306	total: 5.03s	remaining: 2.88s
318:	learn: 0.3884778	total: 5.05s	remaining: 2.87s
319:	learn: 0.3884455	total: 5.06s	remaining: 2.85s
320:	learn: 0.3884368	total: 5.08s	remaining: 2.83s
321:	learn: 0.3884094	total: 5.1s	remaining: 2.82s
322:	learn: 0.3883500	total: 5.11s	remaining: 2.8s
323:	learn: 0.3883375	total: 5.12s	remaining: 2.78s
324:	learn: 0.3883250	total: 5.14s	remaining: 2.77s
325:	learn: 0.3882843	total: 5.16s	remaining: 2.75s
326:	learn: 0.3882093	total: 5.17s	remaining: 2.73s
327:	learn: 0.3881750	total: 5.18s	remaining: 2.72s
328:	learn: 0.3881516	total: 5.2s	remaining: 2.7s
329:	learn: 0.3881368	total: 5.21s	remaining: 2.68s
330:	learn: 0.3881185	total: 5.22s	remaining: 2.67s
331:	learn: 0.3880930	total: 5.24s	remaining: 2.65s
332:	learn: 0.3880702	total: 5.25s	remaining: 2.63s
333:	learn: 0.3880512	total: 5.27s	remaining: 2.62s
334:	learn: 0.3880152	total: 5.29s	remaining: 2.6s
335:	learn: 0.3880059	total: 5.3s	remaining: 2.59s
336:	learn: 0.3879716	total: 5.32s	remaining: 2.57s
337:	learn: 0.3879611	total: 5.33s	remaining: 2.56s
338:	learn: 0.3879489	total: 5.35s	remaining: 2.54s
339:	learn: 0.3879294	total: 5.37s	remaining: 2.53s
340:	learn: 0.3879155	total: 5.38s	remaining: 2.51s
341:	learn: 0.3878759	total: 5.4s	remaining: 2.49s
342:	learn: 0.3878215	total: 5.41s	remaining: 2.48s
343:	learn: 0.3877718	total: 5.43s	remaining: 2.46s
344:	learn: 0.3877058	total: 5.44s	remaining: 2.44s
345:	learn: 0.3876504	total: 5.45s	remaining: 2.43s
346:	learn: 0.3875954	total: 5.47s	remaining: 2.41s
347:	learn: 0.3875793	total: 5.48s	remaining: 2.39s
348:	learn: 0.3875789	total: 5.5s	remaining: 2.38s
349:	learn: 0.3875633	total: 5.51s	remaining: 2.36s
350:	learn: 0.3875563	total: 5.52s	remaining: 2.34s
351:	learn: 0.3875387	total: 5.54s	remaining: 2.33s
352:	learn: 0.3874630	total: 5.55s	remaining: 2.31s
353:	learn: 0.3874024	total: 5.57s	remaining: 2.3s
354:	learn: 0.3873758	total: 5.59s	remaining: 2.28s
355:	learn: 0.3873709	total: 5.6s	remaining: 2.27s
356:	learn: 0.3873331	total: 5.61s	remaining: 2.25s
357:	learn: 0.3872574	total: 5.63s	remaining: 2.23s
358:	learn: 0.3872195	total: 5.64s	remaining: 2.22s
359:	learn: 0.3871643	total: 5.66s	remaining: 2.2s
360:	learn: 0.3871416	total: 5.67s	remaining: 2.18s
361:	learn: 0.3871248	total: 5.69s	remaining: 2.17s
362:	learn: 0.3871000	total: 5.71s	remaining: 2.15s
363:	learn: 0.3870845	total: 5.72s	remaining: 2.14s
364:	learn: 0.3870302	total: 5.73s	remaining: 2.12s
365:	learn: 0.3870256	total: 5.75s	remaining: 2.1s
366:	learn: 0.3869788	total: 5.76s	remaining: 2.09s
367:	learn: 0.3869407	total: 5.78s	remaining: 2.07s
368:	learn: 0.3869051	total: 5.8s	remaining: 2.06s
369:	learn: 0.3868780	total: 5.82s	remaining: 2.05s
370:	learn: 0.3868134	total: 5.85s	remaining: 2.04s
371:	learn: 0.3867636	total: 5.87s	remaining: 2.02s
372:	learn: 0.3867016	total: 5.89s	remaining: 2s
373:	learn: 0.3866970	total: 5.9s	remaining: 1.99s
374:	learn: 0.3866856	total: 5.92s	remaining: 1.97s
375:	learn: 0.3866448	total: 5.94s	remaining: 1.96s
376:	learn: 0.3866113	total: 5.96s	remaining: 1.94s
377:	learn: 0.3865877	total: 5.97s	remaining: 1.93s
378:	learn: 0.3865452	total: 5.99s	remaining: 1.91s
379:	learn: 0.3865099	total: 6s	remaining: 1.9s
380:	learn: 0.3864901	total: 6.02s	remaining: 1.88s
381:	learn: 0.3864439	total: 6.04s	remaining: 1.86s
382:	learn: 0.3864346	total: 6.05s	remaining: 1.85s
383:	learn: 0.3864318	total: 6.07s	remaining: 1.83s
384:	learn: 0.3863877	total: 6.08s	remaining: 1.82s
385:	learn: 0.3863584	total: 6.1s	remaining: 1.8s
386:	learn: 0.3863543	total: 6.11s	remaining: 1.78s
387:	learn: 0.3863194	total: 6.13s	remaining: 1.77s

CatBoostClassifier(max_depth=4, min_data_in_leaf=5, n_estimators=500, random_state=42, reg_lambda=1.7391886518816502, subsample=0.8680963214010124)

In [39]:
print(X_train.shape)
print(y_train.shape)
print(y_train.value_counts(normalize=True))

(17448, 24)
(17448,)
cura
1    0.830754
0    0.169246
Name: proportion, dtype: float64

In [40]:
X_test_model = X_test_novo.copy()

y_prob = cat.predict_proba(X_test_model)[:, 1]

In [41]:
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score
from sklearn.utils import resample


def auc_por_subgrupo_com_ic(X_test, y_test, y_prob, coluna, n_boot=2000, seed=42):

    df = X_test.copy()
    df = df.copy()

    df["y_true"] = np.array(y_test)
    df["y_prob"] = np.array(y_prob)

    resultados = []

    for g in df[coluna].dropna().unique():

        sub = df[df[coluna] == g]

        y_true = sub["y_true"].values
        y_prob_sub = sub["y_prob"].values

        # precisa de pelo menos 2 classes
        if len(np.unique(y_true)) < 2:
            resultados.append({
                "Subgrupo": coluna,
                "Categoria": g,
                "N": len(sub),
                "AUC-ROC": np.nan,
                "IC95%_inferior": np.nan,
                "IC95%_superior": np.nan
            })
            continue

        # AUC original
        auc_original = roc_auc_score(y_true, y_prob_sub)

        # Bootstrap
        aucs = []

        rng = np.random.default_rng(seed)  # garante reprodutibilidade SEM travar o bootstrap

        n = len(y_true)

        for _ in range(n_boot):

            idx = rng.integers(0, n, n)

            y_true_b = y_true[idx]
            y_prob_b = y_prob_sub[idx]

            # precisa de pelo menos 2 classes no bootstrap
            if len(np.unique(y_true_b)) < 2:
                continue

            aucs.append(roc_auc_score(y_true_b, y_prob_b))

        aucs = np.array(aucs)

        ic_inf = np.percentile(aucs, 2.5)
        ic_sup = np.percentile(aucs, 97.5)

        resultados.append({
            "Subgrupo": coluna,
            "Categoria": g,
            "N": len(sub),
            "AUC-ROC": auc_original,
            "IC95%_inferior": ic_inf,
            "IC95%_superior": ic_sup
        })

    return pd.DataFrame(resultados)

In [42]:
auc_raca = auc_por_subgrupo_com_ic(
    X_test_novo,
    y_test,
    y_prob,
    "cs_raca_1.0"
)

print(auc_raca)

      Subgrupo  Categoria     N   AUC-ROC  IC95%_inferior  IC95%_superior
0  cs_raca_1.0        1.0  1670  0.749325        0.704217        0.790060
1  cs_raca_1.0        0.0  5419  0.753667        0.736882        0.770251

In [43]:
auc_raca = auc_por_subgrupo_com_ic(
    X_test_novo,
    y_test,
    y_prob,
    "cs_raca_2.0"
)

print(auc_raca)

      Subgrupo  Categoria     N   AUC-ROC  IC95%_inferior  IC95%_superior
0  cs_raca_2.0        0.0  5314  0.753108        0.733733        0.772894
1  cs_raca_2.0        1.0  1775  0.777796        0.748735        0.805939

In [44]:
auc_escola = auc_por_subgrupo_com_ic(
    X_test_novo,
    y_test,
    y_prob,
    "escola_faixa_1.0"
)

print(auc_escola)

           Subgrupo  Categoria     N   AUC-ROC  IC95%_inferior  IC95%_superior
0  escola_faixa_1.0        0.0  5259  0.755123        0.737126        0.770991
1  escola_faixa_1.0        1.0  1830  0.732113        0.689242        0.773245

In [45]:
auc_escola = auc_por_subgrupo_com_ic(
    X_test_novo,
    y_test,
    y_prob,
    "escola_faixa_0.0"
)

print(auc_escola)

           Subgrupo  Categoria     N   AUC-ROC  IC95%_inferior  IC95%_superior
0  escola_faixa_0.0        1.0  4444  0.763431        0.743853        0.782194
1  escola_faixa_0.0        0.0  2645  0.749061        0.720230        0.776364

In [46]:
auc_pop = auc_por_subgrupo_com_ic(
    X_test_novo,
    y_test,
    y_prob,
    "pop_grupo"
)

print(auc_pop)

    Subgrupo         Categoria     N   AUC-ROC  IC95%_inferior  IC95%_superior
0  pop_grupo  300000 a 1000000  1518  0.764929        0.733968        0.796083
1  pop_grupo          >1000000  4875  0.760141        0.740676        0.779359
2  pop_grupo          < 300000   696  0.724975        0.665271        0.782150

#Etapa3

In [47]:
#Import da base de treino e teste
df_train = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Artigo1_RJ/Etapa3/dados_treino_cat3boruta_rj_2015_2025.csv",
                        encoding='latin1', sep=",")
df_test = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Artigo1_RJ/Etapa3/dados_teste_cat3boruta_rj_2015_2025.csv",
                        encoding='latin1', sep=",")

In [48]:
df_train.shape

(16389, 20)

In [49]:
df_train.columns

Index(['pop', 'cs_sexo_0.0', 'cs_sexo_1.0', 'cs_raca_1.0', 'agravdiabe_1.0',
       'bacilosc_e_2.0', 'cultura_es_2.0', 'bacilosc_2_2.0', 'bacilosc_2_3.0',
       'bacilosc_4_2.0', 'bacilosc_4_9.0', 'pop_rua_1.0', 'agravdroga_0.0',
       'agravdroga_1.0', 'agravtabac_0.0', 'agravtabac_1.0',
       'escola_faixa_1.0', 'faixa_etaria_1.0', 'faixa_etaria_3.0', 'cura'],
      dtype='object')

In [50]:
import pandas as pd

df_train["pop_grupo"] = pd.cut(
    df_train["pop"],
    bins=[-float("inf"), -1.512, -1.28, float("inf")],
    labels=['< 300000', '300000 a 1000000', '>1000000']
)


df_test["pop_grupo"] = pd.cut(
    df_test["pop"],
    bins=[-float("inf"), -1.512, -1.28, float("inf")],
    labels=['< 300000', '300000 a 1000000', '>1000000']
)

In [51]:
#Separação das bases entre X_train, X_test, y_train, y_test
X_train_novo=df_train.drop(columns = "cura")
y_train=df_train.cura
X_test_novo=df_test.drop(columns = "cura")
y_test=df_test.cura

In [52]:
#Visualização da proporção do desfecho na base de treino
y_train.value_counts(normalize=True)

cura
1    0.878089
0    0.121911
Name: proportion, dtype: float64

In [53]:
import joblib

caminho = "/content/drive/MyDrive/Colab Notebooks/Artigo1_RJ/Etapa3/best_model_cat_novo.pkl"

cat = joblib.load(caminho)

print("✅ Modelo carregado com sucesso")

✅ Modelo carregado com sucesso

In [54]:
data = joblib.load(caminho)

cat = data["model_cat_novo"]
print(data["params_cat_novo"])
print(data["method_cat_novo"])

{'n_estimators': 500, 'max_depth': 3, 'min_data_in_leaf': 26, 'subsample': 0.9933475821943013, 'reg_lambda': 1.3719132702327823}
Optuna

In [55]:
from catboost import CatBoostClassifier

# ===============================
# Criar DataFrame final de AUCs
# ===============================

params_cat = data["params_cat_novo"]

cat = CatBoostClassifier(
    **params_cat,
    **({"random_state": seed}
       if "random_state" not in params_xgb
       else {})
)

In [56]:
X_train = df_train.drop(columns=['cura'])
y_train = df_train['cura']

# Identify categorical features
cat_features = X_train.select_dtypes(include='category').columns.tolist()

cat.fit(X_train, y_train, cat_features=cat_features)

0:	learn: 0.6704880	total: 16.3ms	remaining: 8.13s
1:	learn: 0.6468102	total: 28.8ms	remaining: 7.17s
2:	learn: 0.6257979	total: 43.6ms	remaining: 7.22s
3:	learn: 0.6056179	total: 56.4ms	remaining: 6.99s
4:	learn: 0.5877440	total: 73.1ms	remaining: 7.23s
5:	learn: 0.5710607	total: 85ms	remaining: 7s
6:	learn: 0.5547981	total: 99.3ms	remaining: 6.99s
7:	learn: 0.5395193	total: 114ms	remaining: 7.03s
8:	learn: 0.5259770	total: 129ms	remaining: 7.03s
9:	learn: 0.5142543	total: 144ms	remaining: 7.06s
10:	learn: 0.5018821	total: 158ms	remaining: 7.03s
11:	learn: 0.4910404	total: 171ms	remaining: 6.95s
12:	learn: 0.4809651	total: 183ms	remaining: 6.87s
13:	learn: 0.4707701	total: 195ms	remaining: 6.75s
14:	learn: 0.4619590	total: 209ms	remaining: 6.76s
15:	learn: 0.4535485	total: 223ms	remaining: 6.75s
16:	learn: 0.4458362	total: 238ms	remaining: 6.75s
17:	learn: 0.4382111	total: 250ms	remaining: 6.69s
18:	learn: 0.4318532	total: 264ms	remaining: 6.69s
19:	learn: 0.4256779	total: 283ms	remaining: 6.8s
20:	learn: 0.4201251	total: 308ms	remaining: 7.03s
21:	learn: 0.4152128	total: 327ms	remaining: 7.11s
22:	learn: 0.4099819	total: 342ms	remaining: 7.08s
23:	learn: 0.4050347	total: 355ms	remaining: 7.05s
24:	learn: 0.4003424	total: 370ms	remaining: 7.04s
25:	learn: 0.3959020	total: 383ms	remaining: 6.99s
26:	learn: 0.3928464	total: 397ms	remaining: 6.96s
27:	learn: 0.3888357	total: 409ms	remaining: 6.9s
28:	learn: 0.3851585	total: 420ms	remaining: 6.83s
29:	learn: 0.3822580	total: 434ms	remaining: 6.79s
30:	learn: 0.3791574	total: 445ms	remaining: 6.73s
31:	learn: 0.3760525	total: 456ms	remaining: 6.67s
32:	learn: 0.3736534	total: 467ms	remaining: 6.61s
33:	learn: 0.3714103	total: 479ms	remaining: 6.57s
34:	learn: 0.3688675	total: 491ms	remaining: 6.52s
35:	learn: 0.3667769	total: 505ms	remaining: 6.5s
36:	learn: 0.3646138	total: 516ms	remaining: 6.46s
37:	learn: 0.3623791	total: 527ms	remaining: 6.4s
38:	learn: 0.3604858	total: 538ms	remaining: 6.36s
39:	learn: 0.3586224	total: 552ms	remaining: 6.34s
40:	learn: 0.3572229	total: 567ms	remaining: 6.35s
41:	learn: 0.3557073	total: 580ms	remaining: 6.32s
42:	learn: 0.3542136	total: 591ms	remaining: 6.29s
43:	learn: 0.3527771	total: 603ms	remaining: 6.25s
44:	learn: 0.3514469	total: 614ms	remaining: 6.21s
45:	learn: 0.3503476	total: 627ms	remaining: 6.18s
46:	learn: 0.3492462	total: 641ms	remaining: 6.18s
47:	learn: 0.3482358	total: 652ms	remaining: 6.14s
48:	learn: 0.3469138	total: 663ms	remaining: 6.1s
49:	learn: 0.3459677	total: 674ms	remaining: 6.06s
50:	learn: 0.3449934	total: 685ms	remaining: 6.03s
51:	learn: 0.3442240	total: 701ms	remaining: 6.04s
52:	learn: 0.3431136	total: 712ms	remaining: 6.01s
53:	learn: 0.3424383	total: 725ms	remaining: 5.99s
54:	learn: 0.3418010	total: 737ms	remaining: 5.96s
55:	learn: 0.3411003	total: 748ms	remaining: 5.93s
56:	learn: 0.3404961	total: 763ms	remaining: 5.93s
57:	learn: 0.3398342	total: 777ms	remaining: 5.92s
58:	learn: 0.3391879	total: 788ms	remaining: 5.89s
59:	learn: 0.3386841	total: 800ms	remaining: 5.87s
60:	learn: 0.3379181	total: 811ms	remaining: 5.84s
61:	learn: 0.3371949	total: 823ms	remaining: 5.81s
62:	learn: 0.3366924	total: 834ms	remaining: 5.79s
63:	learn: 0.3361111	total: 849ms	remaining: 5.78s
64:	learn: 0.3356854	total: 861ms	remaining: 5.76s
65:	learn: 0.3353082	total: 874ms	remaining: 5.74s
66:	learn: 0.3348326	total: 885ms	remaining: 5.72s
67:	learn: 0.3341533	total: 896ms	remaining: 5.69s
68:	learn: 0.3335167	total: 909ms	remaining: 5.68s
69:	learn: 0.3330307	total: 920ms	remaining: 5.65s
70:	learn: 0.3325986	total: 931ms	remaining: 5.63s
71:	learn: 0.3322348	total: 942ms	remaining: 5.6s
72:	learn: 0.3319391	total: 953ms	remaining: 5.58s
73:	learn: 0.3315816	total: 970ms	remaining: 5.58s
74:	learn: 0.3312891	total: 983ms	remaining: 5.57s
75:	learn: 0.3309520	total: 995ms	remaining: 5.55s
76:	learn: 0.3305719	total: 1.01s	remaining: 5.54s
77:	learn: 0.3303174	total: 1.02s	remaining: 5.52s
78:	learn: 0.3300032	total: 1.03s	remaining: 5.5s
79:	learn: 0.3297701	total: 1.04s	remaining: 5.47s
80:	learn: 0.3294243	total: 1.05s	remaining: 5.46s
81:	learn: 0.3292333	total: 1.07s	remaining: 5.45s
82:	learn: 0.3287944	total: 1.08s	remaining: 5.43s
83:	learn: 0.3286010	total: 1.09s	remaining: 5.42s
84:	learn: 0.3284304	total: 1.11s	remaining: 5.4s
85:	learn: 0.3282430	total: 1.12s	remaining: 5.38s
86:	learn: 0.3280303	total: 1.13s	remaining: 5.36s
87:	learn: 0.3276386	total: 1.14s	remaining: 5.33s
88:	learn: 0.3274255	total: 1.15s	remaining: 5.31s
89:	learn: 0.3272366	total: 1.16s	remaining: 5.28s
90:	learn: 0.3269906	total: 1.17s	remaining: 5.26s
91:	learn: 0.3267450	total: 1.19s	remaining: 5.26s
92:	learn: 0.3266039	total: 1.2s	remaining: 5.25s
93:	learn: 0.3264566	total: 1.21s	remaining: 5.23s
94:	learn: 0.3262344	total: 1.22s	remaining: 5.21s
95:	learn: 0.3260546	total: 1.23s	remaining: 5.19s
96:	learn: 0.3257363	total: 1.24s	remaining: 5.17s
97:	learn: 0.3256057	total: 1.26s	remaining: 5.16s
98:	learn: 0.3254745	total: 1.27s	remaining: 5.14s
99:	learn: 0.3252494	total: 1.28s	remaining: 5.12s
100:	learn: 0.3251283	total: 1.29s	remaining: 5.1s
101:	learn: 0.3250286	total: 1.3s	remaining: 5.09s
102:	learn: 0.3249186	total: 1.33s	remaining: 5.12s
103:	learn: 0.3248325	total: 1.35s	remaining: 5.13s
104:	learn: 0.3247227	total: 1.36s	remaining: 5.11s
105:	learn: 0.3246213	total: 1.37s	remaining: 5.09s
106:	learn: 0.3245304	total: 1.39s	remaining: 5.09s
107:	learn: 0.3244358	total: 1.4s	remaining: 5.07s
108:	learn: 0.3243722	total: 1.41s	remaining: 5.06s
109:	learn: 0.3243106	total: 1.42s	remaining: 5.04s
110:	learn: 0.3241530	total: 1.43s	remaining: 5.02s
111:	learn: 0.3239684	total: 1.44s	remaining: 5s
112:	learn: 0.3238874	total: 1.46s	remaining: 4.98s
113:	learn: 0.3237950	total: 1.47s	remaining: 4.98s
114:	learn: 0.3237217	total: 1.48s	remaining: 4.97s
115:	learn: 0.3236404	total: 1.5s	remaining: 4.95s
116:	learn: 0.3233856	total: 1.51s	remaining: 4.93s
117:	learn: 0.3232750	total: 1.52s	remaining: 4.93s
118:	learn: 0.3232112	total: 1.53s	remaining: 4.9s
119:	learn: 0.3231075	total: 1.54s	remaining: 4.88s
120:	learn: 0.3228722	total: 1.55s	remaining: 4.86s
121:	learn: 0.3228189	total: 1.56s	remaining: 4.85s
122:	learn: 0.3226000	total: 1.57s	remaining: 4.83s
123:	learn: 0.3225171	total: 1.59s	remaining: 4.82s
124:	learn: 0.3224185	total: 1.6s	remaining: 4.81s
125:	learn: 0.3223494	total: 1.62s	remaining: 4.8s
126:	learn: 0.3222681	total: 1.63s	remaining: 4.78s
127:	learn: 0.3221864	total: 1.64s	remaining: 4.76s
128:	learn: 0.3221241	total: 1.65s	remaining: 4.75s
129:	learn: 0.3220539	total: 1.66s	remaining: 4.73s
130:	learn: 0.3219771	total: 1.67s	remaining: 4.72s
131:	learn: 0.3219395	total: 1.69s	remaining: 4.71s
132:	learn: 0.3218421	total: 1.7s	remaining: 4.69s
133:	learn: 0.3217715	total: 1.71s	remaining: 4.68s
134:	learn: 0.3217290	total: 1.72s	remaining: 4.66s
135:	learn: 0.3216974	total: 1.74s	remaining: 4.64s
136:	learn: 0.3216457	total: 1.75s	remaining: 4.63s
137:	learn: 0.3216307	total: 1.76s	remaining: 4.61s
138:	learn: 0.3214350	total: 1.77s	remaining: 4.59s
139:	learn: 0.3213625	total: 1.78s	remaining: 4.57s
140:	learn: 0.3213148	total: 1.79s	remaining: 4.56s
141:	learn: 0.3212484	total: 1.8s	remaining: 4.55s
142:	learn: 0.3211979	total: 1.82s	remaining: 4.54s
143:	learn: 0.3211052	total: 1.83s	remaining: 4.54s
144:	learn: 0.3210613	total: 1.85s	remaining: 4.53s
145:	learn: 0.3210278	total: 1.86s	remaining: 4.52s
146:	learn: 0.3209733	total: 1.88s	remaining: 4.51s
147:	learn: 0.3209180	total: 1.89s	remaining: 4.5s
148:	learn: 0.3208699	total: 1.9s	remaining: 4.49s
149:	learn: 0.3207847	total: 1.91s	remaining: 4.47s
150:	learn: 0.3207382	total: 1.93s	remaining: 4.45s
151:	learn: 0.3206821	total: 1.94s	remaining: 4.44s
152:	learn: 0.3206411	total: 1.95s	remaining: 4.43s
153:	learn: 0.3205911	total: 1.96s	remaining: 4.41s
154:	learn: 0.3205395	total: 1.97s	remaining: 4.39s
155:	learn: 0.3205032	total: 1.99s	remaining: 4.38s
156:	learn: 0.3204494	total: 2s	remaining: 4.37s
157:	learn: 0.3204197	total: 2.02s	remaining: 4.36s
158:	learn: 0.3204013	total: 2.03s	remaining: 4.35s
159:	learn: 0.3202339	total: 2.04s	remaining: 4.33s
160:	learn: 0.3201807	total: 2.06s	remaining: 4.33s
161:	learn: 0.3201513	total: 2.07s	remaining: 4.32s
162:	learn: 0.3201066	total: 2.09s	remaining: 4.31s
163:	learn: 0.3200302	total: 2.1s	remaining: 4.3s
164:	learn: 0.3199871	total: 2.11s	remaining: 4.28s
165:	learn: 0.3199569	total: 2.12s	remaining: 4.26s
166:	learn: 0.3199260	total: 2.13s	remaining: 4.24s
167:	learn: 0.3198519	total: 2.14s	remaining: 4.23s
168:	learn: 0.3198145	total: 2.15s	remaining: 4.21s
169:	learn: 0.3197592	total: 2.16s	remaining: 4.2s
170:	learn: 0.3197452	total: 2.17s	remaining: 4.18s
171:	learn: 0.3197042	total: 2.19s	remaining: 4.17s
172:	learn: 0.3196742	total: 2.2s	remaining: 4.16s
173:	learn: 0.3196208	total: 2.21s	remaining: 4.15s
174:	learn: 0.3196082	total: 2.23s	remaining: 4.14s
175:	learn: 0.3195646	total: 2.24s	remaining: 4.13s
176:	learn: 0.3194190	total: 2.25s	remaining: 4.11s
177:	learn: 0.3193962	total: 2.27s	remaining: 4.1s
178:	learn: 0.3193396	total: 2.28s	remaining: 4.09s
179:	learn: 0.3192042	total: 2.29s	remaining: 4.08s
180:	learn: 0.3191896	total: 2.31s	remaining: 4.07s
181:	learn: 0.3191662	total: 2.32s	remaining: 4.05s
182:	learn: 0.3191016	total: 2.33s	remaining: 4.04s
183:	learn: 0.3190764	total: 2.35s	remaining: 4.04s
184:	learn: 0.3190391	total: 2.37s	remaining: 4.04s
185:	learn: 0.3190338	total: 2.39s	remaining: 4.04s
186:	learn: 0.3189900	total: 2.42s	remaining: 4.06s
187:	learn: 0.3189312	total: 2.44s	remaining: 4.05s
188:	learn: 0.3188805	total: 2.45s	remaining: 4.04s
189:	learn: 0.3188458	total: 2.47s	remaining: 4.03s
190:	learn: 0.3188170	total: 2.48s	remaining: 4.01s
191:	learn: 0.3187809	total: 2.49s	remaining: 4s
192:	learn: 0.3187353	total: 2.5s	remaining: 3.98s
193:	learn: 0.3187106	total: 2.52s	remaining: 3.97s
194:	learn: 0.3186445	total: 2.53s	remaining: 3.96s
195:	learn: 0.3186180	total: 2.54s	remaining: 3.94s
196:	learn: 0.3185901	total: 2.55s	remaining: 3.93s
197:	learn: 0.3185535	total: 2.56s	remaining: 3.91s
198:	learn: 0.3185286	total: 2.58s	remaining: 3.9s
199:	learn: 0.3184959	total: 2.59s	remaining: 3.88s
200:	learn: 0.3183748	total: 2.6s	remaining: 3.87s
201:	learn: 0.3183571	total: 2.61s	remaining: 3.86s
202:	learn: 0.3183272	total: 2.63s	remaining: 3.84s
203:	learn: 0.3182813	total: 2.64s	remaining: 3.84s
204:	learn: 0.3182667	total: 2.66s	remaining: 3.82s
205:	learn: 0.3182610	total: 2.67s	remaining: 3.81s
206:	learn: 0.3182167	total: 2.68s	remaining: 3.8s
207:	learn: 0.3181986	total: 2.69s	remaining: 3.78s
208:	learn: 0.3181717	total: 2.71s	remaining: 3.78s
209:	learn: 0.3181531	total: 2.73s	remaining: 3.76s
210:	learn: 0.3180942	total: 2.74s	remaining: 3.75s
211:	learn: 0.3180552	total: 2.75s	remaining: 3.73s
212:	learn: 0.3180301	total: 2.76s	remaining: 3.72s
213:	learn: 0.3180196	total: 2.77s	remaining: 3.7s
214:	learn: 0.3179846	total: 2.78s	remaining: 3.68s
215:	learn: 0.3179716	total: 2.79s	remaining: 3.67s
216:	learn: 0.3179386	total: 2.81s	remaining: 3.66s
217:	learn: 0.3178949	total: 2.82s	remaining: 3.64s
218:	learn: 0.3178776	total: 2.83s	remaining: 3.63s
219:	learn: 0.3178511	total: 2.84s	remaining: 3.62s
220:	learn: 0.3178470	total: 2.86s	remaining: 3.61s
221:	learn: 0.3178011	total: 2.87s	remaining: 3.59s
222:	learn: 0.3177939	total: 2.88s	remaining: 3.58s
223:	learn: 0.3177815	total: 2.89s	remaining: 3.56s
224:	learn: 0.3177657	total: 2.9s	remaining: 3.55s
225:	learn: 0.3177495	total: 2.92s	remaining: 3.54s
226:	learn: 0.3177453	total: 2.93s	remaining: 3.52s
227:	learn: 0.3177345	total: 2.94s	remaining: 3.51s
228:	learn: 0.3177091	total: 2.96s	remaining: 3.5s
229:	learn: 0.3176909	total: 2.97s	remaining: 3.48s
230:	learn: 0.3176743	total: 2.98s	remaining: 3.47s
231:	learn: 0.3176487	total: 2.99s	remaining: 3.46s
232:	learn: 0.3176319	total: 3.01s	remaining: 3.44s
233:	learn: 0.3176101	total: 3.02s	remaining: 3.43s
234:	learn: 0.3176000	total: 3.03s	remaining: 3.42s
235:	learn: 0.3175847	total: 3.05s	remaining: 3.41s
236:	learn: 0.3175579	total: 3.06s	remaining: 3.4s
237:	learn: 0.3175195	total: 3.07s	remaining: 3.38s
238:	learn: 0.3174873	total: 3.08s	remaining: 3.37s
239:	learn: 0.3174604	total: 3.1s	remaining: 3.35s
240:	learn: 0.3174344	total: 3.11s	remaining: 3.34s
241:	learn: 0.3173997	total: 3.13s	remaining: 3.33s
242:	learn: 0.3173679	total: 3.14s	remaining: 3.32s
243:	learn: 0.3173378	total: 3.15s	remaining: 3.3s
244:	learn: 0.3173278	total: 3.16s	remaining: 3.29s
245:	learn: 0.3173245	total: 3.17s	remaining: 3.27s
246:	learn: 0.3173152	total: 3.18s	remaining: 3.26s
247:	learn: 0.3172706	total: 3.19s	remaining: 3.24s
248:	learn: 0.3172631	total: 3.2s	remaining: 3.23s
249:	learn: 0.3172531	total: 3.22s	remaining: 3.22s
250:	learn: 0.3172047	total: 3.23s	remaining: 3.2s
251:	learn: 0.3171983	total: 3.24s	remaining: 3.19s
252:	learn: 0.3171622	total: 3.25s	remaining: 3.17s
253:	learn: 0.3171294	total: 3.26s	remaining: 3.16s
254:	learn: 0.3171082	total: 3.27s	remaining: 3.15s
255:	learn: 0.3170923	total: 3.28s	remaining: 3.13s
256:	learn: 0.3170427	total: 3.29s	remaining: 3.12s
257:	learn: 0.3170322	total: 3.31s	remaining: 3.1s
258:	learn: 0.3170288	total: 3.32s	remaining: 3.09s
259:	learn: 0.3170091	total: 3.34s	remaining: 3.08s
260:	learn: 0.3170007	total: 3.35s	remaining: 3.07s
261:	learn: 0.3169625	total: 3.37s	remaining: 3.06s
262:	learn: 0.3169540	total: 3.38s	remaining: 3.04s
263:	learn: 0.3169399	total: 3.39s	remaining: 3.03s
264:	learn: 0.3169328	total: 3.41s	remaining: 3.03s
265:	learn: 0.3168958	total: 3.43s	remaining: 3.02s
266:	learn: 0.3168615	total: 3.45s	remaining: 3.01s
267:	learn: 0.3168585	total: 3.47s	remaining: 3s
268:	learn: 0.3168319	total: 3.48s	remaining: 2.98s
269:	learn: 0.3167959	total: 3.49s	remaining: 2.97s
270:	learn: 0.3167821	total: 3.5s	remaining: 2.96s
271:	learn: 0.3166973	total: 3.51s	remaining: 2.94s
272:	learn: 0.3166603	total: 3.52s	remaining: 2.93s
273:	learn: 0.3166429	total: 3.54s	remaining: 2.92s
274:	learn: 0.3165406	total: 3.55s	remaining: 2.9s
275:	learn: 0.3165288	total: 3.56s	remaining: 2.89s
276:	learn: 0.3165203	total: 3.57s	remaining: 2.88s
277:	learn: 0.3164586	total: 3.58s	remaining: 2.86s
278:	learn: 0.3164370	total: 3.6s	remaining: 2.85s
279:	learn: 0.3164075	total: 3.61s	remaining: 2.83s
280:	learn: 0.3163477	total: 3.62s	remaining: 2.82s
281:	learn: 0.3163251	total: 3.63s	remaining: 2.8s
282:	learn: 0.3162497	total: 3.64s	remaining: 2.79s
283:	learn: 0.3162365	total: 3.65s	remaining: 2.78s
284:	learn: 0.3162312	total: 3.67s	remaining: 2.77s
285:	learn: 0.3161921	total: 3.68s	remaining: 2.76s
286:	learn: 0.3161752	total: 3.7s	remaining: 2.74s
287:	learn: 0.3161610	total: 3.71s	remaining: 2.73s
288:	learn: 0.3161383	total: 3.72s	remaining: 2.72s
289:	learn: 0.3161150	total: 3.74s	remaining: 2.71s
290:	learn: 0.3160220	total: 3.75s	remaining: 2.69s
291:	learn: 0.3160069	total: 3.76s	remaining: 2.68s
292:	learn: 0.3159995	total: 3.77s	remaining: 2.67s
293:	learn: 0.3159736	total: 3.78s	remaining: 2.65s
294:	learn: 0.3159323	total: 3.8s	remaining: 2.64s
295:	learn: 0.3159192	total: 3.81s	remaining: 2.63s
296:	learn: 0.3159044	total: 3.83s	remaining: 2.62s
297:	learn: 0.3158958	total: 3.84s	remaining: 2.6s
298:	learn: 0.3158789	total: 3.85s	remaining: 2.59s
299:	learn: 0.3157924	total: 3.87s	remaining: 2.58s
300:	learn: 0.3157537	total: 3.88s	remaining: 2.57s
301:	learn: 0.3157446	total: 3.9s	remaining: 2.56s
302:	learn: 0.3157387	total: 3.91s	remaining: 2.54s
303:	learn: 0.3157258	total: 3.92s	remaining: 2.53s
304:	learn: 0.3156939	total: 3.93s	remaining: 2.51s
305:	learn: 0.3156649	total: 3.94s	remaining: 2.5s
306:	learn: 0.3156195	total: 3.96s	remaining: 2.49s
307:	learn: 0.3155904	total: 3.98s	remaining: 2.48s
308:	learn: 0.3155803	total: 3.99s	remaining: 2.46s
309:	learn: 0.3155508	total: 4s	remaining: 2.45s
310:	learn: 0.3155340	total: 4.01s	remaining: 2.44s
311:	learn: 0.3155099	total: 4.03s	remaining: 2.42s
312:	learn: 0.3155064	total: 4.04s	remaining: 2.42s
313:	learn: 0.3154274	total: 4.05s	remaining: 2.4s
314:	learn: 0.3154224	total: 4.07s	remaining: 2.39s
315:	learn: 0.3154189	total: 4.08s	remaining: 2.38s
316:	learn: 0.3153981	total: 4.09s	remaining: 2.36s
317:	learn: 0.3153891	total: 4.11s	remaining: 2.35s
318:	learn: 0.3153670	total: 4.12s	remaining: 2.34s
319:	learn: 0.3153527	total: 4.13s	remaining: 2.32s
320:	learn: 0.3153347	total: 4.14s	remaining: 2.31s
321:	learn: 0.3153255	total: 4.16s	remaining: 2.3s
322:	learn: 0.3152800	total: 4.17s	remaining: 2.29s
323:	learn: 0.3152710	total: 4.18s	remaining: 2.27s
324:	learn: 0.3152584	total: 4.2s	remaining: 2.26s
325:	learn: 0.3152472	total: 4.21s	remaining: 2.25s
326:	learn: 0.3152289	total: 4.22s	remaining: 2.23s
327:	learn: 0.3152046	total: 4.23s	remaining: 2.22s
328:	learn: 0.3151913	total: 4.25s	remaining: 2.21s
329:	learn: 0.3151843	total: 4.26s	remaining: 2.19s
330:	learn: 0.3151808	total: 4.27s	remaining: 2.18s
331:	learn: 0.3151097	total: 4.28s	remaining: 2.17s
332:	learn: 0.3150902	total: 4.3s	remaining: 2.15s
333:	learn: 0.3150882	total: 4.31s	remaining: 2.14s
334:	learn: 0.3150804	total: 4.33s	remaining: 2.13s
335:	learn: 0.3150698	total: 4.34s	remaining: 2.12s
336:	learn: 0.3150515	total: 4.35s	remaining: 2.1s
337:	learn: 0.3149923	total: 4.36s	remaining: 2.09s
338:	learn: 0.3149675	total: 4.38s	remaining: 2.08s
339:	learn: 0.3149494	total: 4.39s	remaining: 2.06s
340:	learn: 0.3148838	total: 4.4s	remaining: 2.05s
341:	learn: 0.3148747	total: 4.41s	remaining: 2.04s
342:	learn: 0.3148647	total: 4.43s	remaining: 2.03s
343:	learn: 0.3148508	total: 4.45s	remaining: 2.02s
344:	learn: 0.3148362	total: 4.47s	remaining: 2.01s
345:	learn: 0.3147803	total: 4.49s	remaining: 2s
346:	learn: 0.3147774	total: 4.5s	remaining: 1.98s
347:	learn: 0.3147520	total: 4.51s	remaining: 1.97s
348:	learn: 0.3147426	total: 4.53s	remaining: 1.96s
349:	learn: 0.3147270	total: 4.54s	remaining: 1.94s
350:	learn: 0.3147221	total: 4.55s	remaining: 1.93s
351:	learn: 0.3147164	total: 4.56s	remaining: 1.92s
352:	learn: 0.3146932	total: 4.57s	remaining: 1.9s
353:	learn: 0.3146521	total: 4.59s	remaining: 1.89s
354:	learn: 0.3146407	total: 4.6s	remaining: 1.88s
355:	learn: 0.3145907	total: 4.62s	remaining: 1.87s
356:	learn: 0.3145295	total: 4.63s	remaining: 1.85s
357:	learn: 0.3145179	total: 4.64s	remaining: 1.84s
358:	learn: 0.3145129	total: 4.65s	remaining: 1.83s
359:	learn: 0.3144955	total: 4.67s	remaining: 1.81s
360:	learn: 0.3144855	total: 4.68s	remaining: 1.8s
361:	learn: 0.3144802	total: 4.69s	remaining: 1.79s
362:	learn: 0.3144231	total: 4.7s	remaining: 1.77s
363:	learn: 0.3143983	total: 4.71s	remaining: 1.76s
364:	learn: 0.3143682	total: 4.73s	remaining: 1.75s
365:	learn: 0.3143252	total: 4.74s	remaining: 1.73s
366:	learn: 0.3143167	total: 4.75s	remaining: 1.72s
367:	learn: 0.3142786	total: 4.76s	remaining: 1.71s
368:	learn: 0.3142660	total: 4.77s	remaining: 1.69s
369:	learn: 0.3142274	total: 4.79s	remaining: 1.68s
370:	learn: 0.3142115	total: 4.8s	remaining: 1.67s
371:	learn: 0.3141821	total: 4.81s	remaining: 1.66s
372:	learn: 0.3141628	total: 4.82s	remaining: 1.64s
373:	learn: 0.3141155	total: 4.83s	remaining: 1.63s
374:	learn: 0.3140885	total: 4.85s	remaining: 1.62s
375:	learn: 0.3140586	total: 4.86s	remaining: 1.6s
376:	learn: 0.3140562	total: 4.87s	remaining: 1.59s
377:	learn: 0.3140024	total: 4.88s	remaining: 1.57s
378:	learn: 0.3139973	total: 4.89s	remaining: 1.56s
379:	learn: 0.3139572	total: 4.91s	remaining: 1.55s
380:	learn: 0.3139302	total: 4.92s	remaining: 1.54s
381:	learn: 0.3139214	total: 4.93s	remaining: 1.52s
382:	learn: 0.3138779	total: 4.94s	remaining: 1.51s
383:	learn: 0.3138524	total: 4.95s	remaining: 1.5s
384:	learn: 0.3138287	total: 4.97s	remaining: 1.48s
385:	learn: 0.3138239	total: 4.98s	remaining: 1.47s
386:	learn: 0.3138139	total: 4.99s	remaining: 1.46s
387:	learn: 0.3138078	total: 5.01s	remaining: 1.45s

CatBoostClassifier(max_depth=3, min_data_in_leaf=26, n_estimators=500, random_state=42, reg_lambda=1.3719132702327823, subsample=0.9933475821943013)

In [57]:
print(X_train.shape)
print(y_train.shape)
print(y_train.value_counts(normalize=True))

(16389, 20)
(16389,)
cura
1    0.878089
0    0.121911
Name: proportion, dtype: float64

In [58]:
X_test_model = X_test_novo.copy()

y_prob = cat.predict_proba(X_test_model)[:, 1]

In [59]:
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score
from sklearn.utils import resample


def auc_por_subgrupo_com_ic(X_test, y_test, y_prob, coluna, n_boot=2000, seed=42):

    df = X_test.copy()
    df = df.copy()

    df["y_true"] = np.array(y_test)
    df["y_prob"] = np.array(y_prob)

    resultados = []

    for g in df[coluna].dropna().unique():

        sub = df[df[coluna] == g]

        y_true = sub["y_true"].values
        y_prob_sub = sub["y_prob"].values

        # precisa de pelo menos 2 classes
        if len(np.unique(y_true)) < 2:
            resultados.append({
                "Subgrupo": coluna,
                "Categoria": g,
                "N": len(sub),
                "AUC-ROC": np.nan,
                "IC95%_inferior": np.nan,
                "IC95%_superior": np.nan
            })
            continue

        # AUC original
        auc_original = roc_auc_score(y_true, y_prob_sub)

        # Bootstrap
        aucs = []

        rng = np.random.default_rng(seed)  # garante reprodutibilidade SEM travar o bootstrap

        n = len(y_true)

        for _ in range(n_boot):

            idx = rng.integers(0, n, n)

            y_true_b = y_true[idx]
            y_prob_b = y_prob_sub[idx]

            # precisa de pelo menos 2 classes no bootstrap
            if len(np.unique(y_true_b)) < 2:
                continue

            aucs.append(roc_auc_score(y_true_b, y_prob_b))

        aucs = np.array(aucs)

        ic_inf = np.percentile(aucs, 2.5)
        ic_sup = np.percentile(aucs, 97.5)

        resultados.append({
            "Subgrupo": coluna,
            "Categoria": g,
            "N": len(sub),
            "AUC-ROC": auc_original,
            "IC95%_inferior": ic_inf,
            "IC95%_superior": ic_sup
        })

    return pd.DataFrame(resultados)

In [60]:
auc_raca = auc_por_subgrupo_com_ic(
    X_test_novo,
    y_test,
    y_prob,
    "cs_raca_1.0"
)

print(auc_raca)

      Subgrupo  Categoria     N   AUC-ROC  IC95%_inferior  IC95%_superior
0  cs_raca_1.0        1.0  1613  0.767974        0.714316        0.819385
1  cs_raca_1.0        0.0  5119  0.752747        0.731989        0.772869

In [61]:
auc_escola = auc_por_subgrupo_com_ic(
    X_test_novo,
    y_test,
    y_prob,
    "escola_faixa_1.0"
)

print(auc_escola)

           Subgrupo  Categoria     N   AUC-ROC  IC95%_inferior  IC95%_superior
0  escola_faixa_1.0        0.0  4949  0.758507        0.739511        0.777609
1  escola_faixa_1.0        1.0  1783  0.736960        0.685248        0.782934

In [62]:
auc_pop = auc_por_subgrupo_com_ic(
    X_test_novo,
    y_test,
    y_prob,
    "pop_grupo"
)

print(auc_pop)

    Subgrupo         Categoria     N   AUC-ROC  IC95%_inferior  IC95%_superior
0  pop_grupo  300000 a 1000000  1391  0.772117        0.733175        0.808962
1  pop_grupo          >1000000  4682  0.767669        0.745279        0.789025
2  pop_grupo          < 300000   659  0.723442        0.657840        0.780233