##• Lendo o banco

In [30]:
import pandas as pd

# Carregue o arquivo CSV em um DataFrame
df = pd.read_csv('SINAN_TB_2015_2025.csv')

/tmp/ipykernel_1829/2752533358.py:4: DtypeWarning: Columns (2,7,20,21,22,23,25,26,36,38,43,44,52,60,66,76,81,87,93) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('SINAN_TB_2015_2025.csv')

In [31]:
df.shape

(1068501, 98)

##• Verificação de duplicados (Obrigatório)

In [32]:
#DUPLICATAS

In [33]:
#Verificação se existem e quantos são os valores duplicados
df.duplicated().sum()

np.int64(19)

In [34]:
#Verificação de valores duplicados
df.loc[df.duplicated()]

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_DIAG,ANO_NASC,NU_IDADE_N,...,AGRAVDROGA,AGRAVTABAC,TEST_MOLEC,TEST_SENSI,ANT_RETRO,BAC_APOS_6,TRANSF,UF_TRANSF,MUN_TRANSF,ANO_BASE
113598,2,A169,20170502,2017,42,421660,1476.0,20170410,1997.0,4019.0,...,2.0,2.0,5.0,7.0,0.0,0,0.0,NaN,NaN,2017
155615,2,A169,20170411,2017,35,355100,0.0,20170407,1993.0,4023.0,...,1.0,1.0,1.0,5.0,0.0,0,0.0,NaN,NaN,2017
244206,2,A169,20181217,2018,24,240800,141.0,20181212,1992.0,4026.0,...,9.0,9.0,1.0,NaN,NaN,2.0,NaN,NaN,NaN,2018
301069,2,A169,20190220,2019,15,150650,148.0,20190219,1995.0,4023.0,...,2.0,2.0,5.0,NaN,NaN,2.0,NaN,NaN,NaN,2019
318422,2,A169,20190511,2019,33,330455,NaN,20190511,1990.0,4029.0,...,9.0,9.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,2019
320009,2,A169,20190520,2019,33,330455,NaN,20190520,2001.0,4018.0,...,9.0,9.0,5.0,7.0,NaN,NaN,NaN,NaN,NaN,2019
346155,2,A169,20190921,2019,33,330455,NaN,20190921,2001.0,4018.0,...,9.0,9.0,5.0,7.0,NaN,NaN,NaN,NaN,NaN,2019
395964,2,A169,20200217,2020,35,355100,NaN,20200217,1986.0,4033.0,...,2.0,2.0,1.0,5.0,NaN,NaN,NaN,NaN,NaN,2020
483090,2,A169,20210219,2021,33,330455,NaN,20210212,1993.0,4027.0,...,9.0,9.0,5.0,6.0,NaN,NaN,NaN,NaN,NaN,2021
525488,2,A169,20211001,2021,50,500320,197.0,20210930,1965.0,4056.0,...,9.0,9.0,1.0,5.0,NaN,3.0,NaN,NaN,NaN,2021
576081,2,A169,20220127,2022,24,240820,141.0,20220126,1994.0,4027.0,...,2.0,2.0,1.0,NaN,NaN,2.0,NaN,NaN,NaN,2022
630834,2,A169,20221012,2022,33,330455,NaN,20221011,1993.0,4029.0,...,2.0,2.0,5.0,7.0,NaN,NaN,NaN,NaN,NaN,2022
679144,2,A169,20230126,2023,24,240820,141.0,20230109,1996.0,4026.0,...,2.0,2.0,1.0,NaN,NaN,2.0,NaN,NaN,NaN,2023
697063,2,A169,20230331,2023,24,240820,141.0,20230331,1992.0,4030.0,...,2.0,2.0,1.0,NaN,NaN,2.0,NaN,NaN,NaN,2023
755055,2,A169,20240115,2024,24,240820,141.0,20231220,1993.0,4030.0,...,2.0,2.0,1.0,NaN,NaN,3.0,NaN,NaN,NaN,2023
781527,2,A169,2016-03-29,2016,33,330455,0.0,2016-03-29,NaN,4048.0,...,9.0,9.0,5.0,6.0,0.0,4,0.0,33.0,NaN,2016
806506,2,A169,2016-10-18,2016,33,330455,0.0,2016-09-13,2010.0,4006.0,...,2.0,2.0,5.0,7.0,0.0,0,0.0,NaN,NaN,2016
807972,2,A169,2016-09-23,2016,33,330100,0.0,2016-09-23,1990.0,4026.0,...,2.0,2.0,5.0,0.0,0.0,3,0.0,NaN,NaN,2016
1068251,2,A169,2025-12-30,2025,33,330455,NaN,2025-12-30,1997.0,4028.0,...,2.0,2.0,1.0,5.0,9.0,NaN,NaN,NaN,NaN,2025

In [35]:
duplicados_por_uf = (
    df[df.duplicated(keep=False)]
    .groupby("SG_UF")
    .size()
    .sort_values(ascending=False)
)

print(duplicados_por_uf)

SG_UF
33    18
24    10
35     4
15     2
42     2
50     2
dtype: int64

In [36]:
#Remoção dos Valores duplicados
df.drop_duplicates(inplace=True)

##• Informações gerais da base (shape, head, info etc.) (Obrigatório)

In [37]:
import pandas as pd
import numpy as np  # Importação d

In [38]:
df.columns

Index(['TP_NOT', 'ID_AGRAVO', 'DT_NOTIFIC', 'NU_ANO', 'SG_UF_NOT',
       'ID_MUNICIP', 'ID_REGIONA', 'DT_DIAG', 'ANO_NASC', 'NU_IDADE_N',
       'CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N', 'SG_UF', 'ID_MN_RESI',
       'ID_RG_RESI', 'ID_PAIS', 'NDUPLIC_N', 'IN_VINCULA', 'DT_DIGITA',
       'DT_TRANSUS', 'DT_TRANSDM', 'DT_TRANSSM', 'DT_TRANSRM', 'DT_TRANSRS',
       'DT_TRANSSE', 'CS_FLXRET', 'FLXRECEBI', 'MIGRADO_W', 'ID_OCUPA_N',
       'TRATAMENTO', 'INSTITUCIO', 'RAIOX_TORA', 'TESTE_TUBE', 'FORMA',
       'EXTRAPU1_N', 'EXTRAPU2_N', 'EXTRAPUL_O', 'AGRAVAIDS', 'AGRAVALCOO',
       'AGRAVDIABE', 'AGRAVDOENC', 'AGRAVOUTRA', 'AGRAVOUTDE', 'BACILOSC_E',
       'BACILOS_E2', 'BACILOSC_O', 'CULTURA_ES', 'CULTURA_OU', 'HIV',
       'HISTOPATOL', 'DT_INIC_TR', 'RIFAMPICIN', 'ISONIAZIDA', 'ETAMBUTOL',
       'ESTREPTOMI', 'PIRAZINAMI', 'ETIONAMIDA', 'OUTRAS', 'OUTRAS_DES',
       'TRAT_SUPER', 'NU_CONTATO', 'DOENCA_TRA', 'SG_UF_AT', 'ID_MUNIC_A',
       'DT_NOTI_AT', 'SG_UF_2', 'ID_MUNIC_2', 'BACILOSC_1', 'BACILOSC_2',
       'BACILOSC_3', 'BACILOSC_4', 'BACILOSC_5', 'BACILOSC_6', 'TRATSUP_AT',
       'DT_MUDANCA', 'NU_COMU_EX', 'SITUA_9_M', 'SITUA_12_M', 'SITUA_ENCE',
       'DT_ENCERRA', 'TPUNINOT', 'POP_LIBER', 'POP_RUA', 'POP_SAUDE',
       'POP_IMIG', 'BENEF_GOV', 'AGRAVDROGA', 'AGRAVTABAC', 'TEST_MOLEC',
       'TEST_SENSI', 'ANT_RETRO', 'BAC_APOS_6', 'TRANSF', 'UF_TRANSF',
       'MUN_TRANSF', 'ANO_BASE'],
      dtype='object')

In [39]:
df.head()

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_DIAG,ANO_NASC,NU_IDADE_N,...,AGRAVDROGA,AGRAVTABAC,TEST_MOLEC,TEST_SENSI,ANT_RETRO,BAC_APOS_6,TRANSF,UF_TRANSF,MUN_TRANSF,ANO_BASE
0,2,A169,20150226,2015,15,150240,1486.0,20150226,1962.0,4052.0,...,2.0,2.0,5.0,7.0,0.0,0,2.0,15.0,15.0,2015
1,2,A169,20150324,2015,29,292740,1380.0,20150324,1981.0,4033.0,...,2.0,2.0,5.0,0.0,0.0,0,2.0,29.0,29.0,2015
2,2,A169,20151005,2015,42,420890,1567.0,20151002,1988.0,4027.0,...,2.0,2.0,5.0,0.0,0.0,0,2.0,42.0,42.0,2015
3,2,A169,20151016,2015,41,410690,1356.0,20151014,1965.0,4050.0,...,2.0,2.0,5.0,0.0,0.0,3,2.0,41.0,41.0,2015
4,2,A169,20150424,2015,41,411990,1357.0,20150110,1964.0,4050.0,...,2.0,1.0,5.0,7.0,2.0,0,0.0,NaN,NaN,2015

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1068482 entries, 0 to 1068500
Data columns (total 98 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   TP_NOT      1068482 non-null  int64
 1   ID_AGRAVO   1068482 non-null  object
 2   DT_NOTIFIC  1068482 non-null  object
 3   NU_ANO      1068482 non-null  int64
 4   SG_UF_NOT   1068482 non-null  int64
 5   ID_MUNICIP  1068482 non-null  int64
 6   ID_REGIONA  740140 non-null   float64
 7   DT_DIAG     1068482 non-null  object
 8   ANO_NASC    1062870 non-null  float64
 9   NU_IDADE_N  1068154 non-null  float64
 10  CS_SEXO     1068482 non-null  object
 11  CS_GESTANT  1052288 non-null  float64
 12  CS_RACA     1055647 non-null  float64
 13  CS_ESCOL_N  1013582 non-null  float64
 14  SG_UF       1068482 non-null  int64
 15  ID_MN_RESI  1068482 non-null  int64
 16  ID_RG_RESI  737813 non-null   float64
 17  ID_PAIS     885427 non-null   float64
 18  NDUPLIC_N   339635 non-null   float64
 19  IN_VINCULA  336448 non-null   float64
 20  DT_DIGITA   623465 non-null   object
 21  DT_TRANSUS  47740 non-null    object
 22  DT_TRANSDM  13383 non-null    object
 23  DT_TRANSSM  391373 non-null   object
 24  DT_TRANSRM  0 non-null        float64
 25  DT_TRANSRS  14800 non-null    object
 26  DT_TRANSSE  256678 non-null   object
 27  CS_FLXRET   0 non-null        float64
 28  FLXRECEBI   0 non-null        float64
 29  MIGRADO_W   261962 non-null   float64
 30  ID_OCUPA_N  176789 non-null   float64
 31  TRATAMENTO  1068482 non-null  int64
 32  INSTITUCIO  262042 non-null   float64
 33  RAIOX_TORA  1053520 non-null  float64
 34  TESTE_TUBE  262038 non-null   float64
 35  FORMA       1068260 non-null  float64
 36  EXTRAPU1_N  796443 non-null   object
 37  EXTRAPU2_N  264443 non-null   float64
 38  EXTRAPUL_O  4275 non-null     object
 39  AGRAVAIDS   1054958 non-null  float64
 40  AGRAVALCOO  1055883 non-null  float64
 41  AGRAVDIABE  1054897 non-null  float64
 42  AGRAVDOENC  1052252 non-null  float64
 43  AGRAVOUTRA  800306 non-null   object
 44  AGRAVOUTDE  23922 non-null    object
 45  BACILOSC_E  1068274 non-null  float64
 46  BACILOS_E2  262068 non-null   float64
 47  BACILOSC_O  388566 non-null   float64
 48  CULTURA_ES  1068284 non-null  float64
 49  CULTURA_OU  364665 non-null   float64
 50  HIV         1066046 non-null  float64
 51  HISTOPATOL  1009009 non-null  float64
 52  DT_INIC_TR  1029317 non-null  object
 53  RIFAMPICIN  262015 non-null   float64
 54  ISONIAZIDA  262015 non-null   float64
 55  ETAMBUTOL   262010 non-null   float64
 56  ESTREPTOMI  262007 non-null   float64
 57  PIRAZINAMI  262014 non-null   float64
 58  ETIONAMIDA  262014 non-null   float64
 59  OUTRAS      262004 non-null   float64
 60  OUTRAS_DES  176503 non-null   object
 61  TRAT_SUPER  443578 non-null   float64
 62  NU_CONTATO  1041074 non-null  float64
 63  DOENCA_TRA  310884 non-null   float64
 64  SG_UF_AT    1066200 non-null  float64
 65  ID_MUNIC_A  1066181 non-null  float64
 66  DT_NOTI_AT  646916 non-null   object
 67  SG_UF_2     880451 non-null   float64
 68  ID_MUNIC_2  792777 non-null   float64
 69  BACILOSC_1  871984 non-null   float64
 70  BACILOSC_2  836933 non-null   float64
 71  BACILOSC_3  810893 non-null   float64
 72  BACILOSC_4  787899 non-null   float64
 73  BACILOSC_5  766102 non-null   float64
 74  BACILOSC_6  744813 non-null   float64
 75  TRATSUP_AT  717483 non-null   float64
 76  DT_MUDANCA  261970 non-null   object
 77  NU_COMU_EX  929848 non-null   float64
 78  SITUA_9_M   262077 non-null   float64
 79  SITUA_12_M  86232 non-null    float64
 80  SITUA_ENCE  999814 non-null   float64
 81  DT_ENCERRA  985764 non-null   object
 82  TPUNINOT    795727 non-null   float64
 83  POP_LIBER   1052247 non-null  float64
 84  POP_RUA     1049953 non-null  float64
 85  POP_SAUDE   1049619 non-null  float64
 86  POP_IMIG    1048623 non-null  float64
 87  BENEF_GOV   854746 non-null   object
 88  AGRAVDROGA  1052311 non-null  float64
 89  AGRAVTABAC  1051973 non-null  float64
 90  TEST_MOLEC  1022551 non-null  float64
 91  TEST_SENSI  692300 non-null   float64
 92  ANT_RETRO   619664 non-null   float64
 93  BAC_APOS_6  489677 non-null   object
 94  TRANSF      323374 non-null   float64
 95  UF_TRANSF   55972 non-null    float64
 96  MUN_TRANSF  46499 non-null    float64
 97  ANO_BASE    1068482 non-null  int64
dtypes: float64(69), int64(8), object(21)
memory usage: 807.0+ MB

In [41]:
df["NU_ANO"].unique()

array([2015, 2016, 2019, 2017, 2018, 2020, 2014, 2013, 1995, 2011, 1992,
       2012, 1987, 1991, 2009, 2010, 1998, 2021, 2022, 2023, 2025, 1989,
       2024, 1982, 1990, 1981, 1999, 1993, 2004, 2001, 2007, 1985, 2006,
       1997, 1983, 2003, 2008, 2026])

In [42]:
df["NU_ANO"] = (
    df["NU_ANO"]
    .astype(str)
    .str[:4]
    .astype("Int64")
)

In [43]:
sorted(df["NU_ANO"].dropna().unique())

[np.int64(1981),
 np.int64(1982),
 np.int64(1983),
 np.int64(1985),
 np.int64(1987),
 np.int64(1989),
 np.int64(1990),
 np.int64(1991),
 np.int64(1992),
 np.int64(1993),
 np.int64(1995),
 np.int64(1997),
 np.int64(1998),
 np.int64(1999),
 np.int64(2001),
 np.int64(2003),
 np.int64(2004),
 np.int64(2006),
 np.int64(2007),
 np.int64(2008),
 np.int64(2009),
 np.int64(2010),
 np.int64(2011),
 np.int64(2012),
 np.int64(2013),
 np.int64(2014),
 np.int64(2015),
 np.int64(2016),
 np.int64(2017),
 np.int64(2018),
 np.int64(2019),
 np.int64(2020),
 np.int64(2021),
 np.int64(2022),
 np.int64(2023),
 np.int64(2024),
 np.int64(2025),
 np.int64(2026)]

In [44]:
df["ANO_BASE"].unique()

array([2015, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2016, 2024, 2025])

#Pré-processamento

---

###Filtrando dataset

In [45]:
df["SG_UF"]

0          15
1          29
2          42
3          41
4          41
           ..
1068496    22
1068497    33
1068498    31
1068499    29
1068500    31
Name: SG_UF, Length: 1068482, dtype: int64

In [46]:
df = df[df["DT_ENCERRA"].notna()]

In [47]:
df['DT_ENCERRA'].isna().sum()

np.int64(0)

In [48]:
df = df[df["DT_INIC_TR"].notna()]

In [49]:
df['DT_INIC_TR'].isna().sum()

np.int64(0)

In [50]:
df.dropna(subset=["DT_ENCERRA", "DT_INIC_TR"])

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_DIAG,ANO_NASC,NU_IDADE_N,...,AGRAVDROGA,AGRAVTABAC,TEST_MOLEC,TEST_SENSI,ANT_RETRO,BAC_APOS_6,TRANSF,UF_TRANSF,MUN_TRANSF,ANO_BASE
0,2,A169,20150226,2015,15,150240,1486.0,20150226,1962.0,4052.0,...,2.0,2.0,5.0,7.0,0.0,0,2.0,15.0,15.0,2015
1,2,A169,20150324,2015,29,292740,1380.0,20150324,1981.0,4033.0,...,2.0,2.0,5.0,0.0,0.0,0,2.0,29.0,29.0,2015
2,2,A169,20151005,2015,42,420890,1567.0,20151002,1988.0,4027.0,...,2.0,2.0,5.0,0.0,0.0,0,2.0,42.0,42.0,2015
3,2,A169,20151016,2015,41,410690,1356.0,20151014,1965.0,4050.0,...,2.0,2.0,5.0,0.0,0.0,3,2.0,41.0,41.0,2015
4,2,A169,20150424,2015,41,411990,1357.0,20150110,1964.0,4050.0,...,2.0,1.0,5.0,7.0,2.0,0,0.0,NaN,NaN,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1068460,2,A169,2025-12-31,2025,29,292740,1380.0,2025-12-31,1982.0,4043.0,...,2.0,2.0,1.0,NaN,9.0,NaN,1.0,NaN,NaN,2025
1068467,2,A169,2025-12-31,2025,43,431770,1601.0,2025-12-31,1970.0,4055.0,...,2.0,1.0,5.0,NaN,9.0,NaN,NaN,NaN,NaN,2025
1068471,2,A169,2026-01-02,2026,29,291072,1387.0,2025-12-31,1977.0,4048.0,...,2.0,1.0,5.0,NaN,2.0,NaN,NaN,NaN,NaN,2025
1068474,2,A169,2026-01-02,2026,35,355030,NaN,2025-12-31,1985.0,4040.0,...,1.0,1.0,5.0,7.0,9.0,NaN,NaN,NaN,NaN,2025
1068484,2,A169,2026-01-06,2026,29,292740,1380.0,2025-12-31,1983.0,4042.0,...,2.0,1.0,1.0,NaN,9.0,NaN,2.0,29.0,29.0,2025

HIV infection, drug resistance, extrapulmonary disease, retreatment, transfer, unevaluated outcome, and other reasons.

1. Caso Novo
2. Recidiva
3. Reingresso após Abandono
4. Não Sabe
5. Transferência
6. Pós-óbito

In [51]:
# Suponha que seu DataFrame seja df e a variável seja 'TRATAMENTO'
tabela_frequencia = df['TRATAMENTO'].value_counts()

# Mostrar a tabela de frequência
print(tabela_frequencia)

TRATAMENTO
1    753038
3    100195
2     69017
5     25911
4      3127
6      2279
Name: count, dtype: int64

In [52]:
tabela_frequencia = df[df['SG_UF'] == 33]['TRATAMENTO'].value_counts(dropna=False)

print(tabela_frequencia)

TRATAMENTO
1    116849
3     16608
2     11443
5      4104
4       845
6       718
Name: count, dtype: int64

In [53]:
116849+16608+11443+4104+845+718

150567

In [54]:
import pandas as pd

# Filtrar as linhas onde 'TRATAMENTO' (tipo de entrada) é igual a 1 (caso novo)
df = df[df['TRATAMENTO'] == 1]

In [55]:
df.shape

(753038, 98)

1. Pulmonar
2. Extrapulmonar
3. Pulmonar + Extrapulmonar

In [56]:
# Suponha que seu DataFrame seja df e a variável seja 'TRATAMENTO'
tabela_frequencia = df['FORMA'].value_counts()

# Mostrar a tabela de frequência
print(tabela_frequencia)

FORMA
1.0    631231
2.0     98159
3.0     23648
Name: count, dtype: int64

In [57]:
tabela_frequencia = df[df['SG_UF'] == 33]['FORMA'].value_counts(dropna=False)

print(tabela_frequencia)

FORMA
1.0    101174
2.0     12502
3.0      3173
Name: count, dtype: int64

In [58]:
# Filtrar as linhas onde 'FORMA' é igual a 1 (pulmonar)
df = df[df['FORMA'] == 1]

df.shape

(631231, 98)

In [59]:
tabela_frequencia = df['HIV'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

HIV
2.0    490411
4.0     84667
1.0     49877
3.0      4625
NaN      1212
0.0       439
Name: count, dtype: int64

In [60]:
tabela_frequencia = df[df['SG_UF'] == 33]['HIV'].value_counts(dropna=False)

print(tabela_frequencia)

HIV
2.0    79361
4.0    13244
1.0     8052
3.0      517
Name: count, dtype: int64

In [61]:
tabela_frequencia = df[df['SG_UF'] == 33]['AGRAVAIDS'].value_counts(dropna=False)

print(tabela_frequencia)

AGRAVAIDS
2.0    80676
9.0    12328
1.0     7282
NaN      600
0.0      287
3.0        1
Name: count, dtype: int64

In [62]:
# Filtrar as linhas onde 'HIV' nao é igual a 1
df = df[df['HIV'] != 1]

df.shape

(581354, 98)

In [63]:
tabela_frequencia = df['AGRAVAIDS'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

AGRAVAIDS
2.0    531256
9.0     40478
NaN      6085
0.0      3030
1.0       504
3.0         1
Name: count, dtype: int64

In [64]:
tabela_frequencia = df[df['SG_UF'] == 33]['AGRAVAIDS'].value_counts(dropna=False)

print(tabela_frequencia)

AGRAVAIDS
2.0    79931
9.0    12144
NaN      590
0.0      280
1.0      176
3.0        1
Name: count, dtype: int64

In [65]:
#casos de HIV removidos da base RJ
8052+176

8228

In [66]:
101174-8228

92946

In [67]:
# Filtrar as linhas onde 'AIDS' nao é igual a 1
df = df[df['AGRAVAIDS'] != 1]

df.shape

(580850, 98)

In [68]:
tabela_frequencia = df['TEST_SENSI'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

TEST_SENSI
7.0    218468
NaN    183025
5.0     86870
0.0     77946
6.0      8120
1.0      2531
4.0      1621
2.0      1206
3.0      1015
9.0        43
8.0         5
Name: count, dtype: int64

In [69]:
tabela_frequencia = df[df['SG_UF'] == 33]['TEST_SENSI'].value_counts(dropna=False)

print(tabela_frequencia)

TEST_SENSI
7.0    30460
NaN    27516
5.0    15916
0.0    13786
6.0     3418
4.0      612
1.0      583
2.0      351
3.0      299
9.0        4
8.0        1
Name: count, dtype: int64

In [70]:
tabela_frequencia = df['TEST_MOLEC'].value_counts()

# Mostrar a tabela de frequência
print(tabela_frequencia)

TEST_MOLEC
5.0    295674
1.0    209186
3.0     23454
0.0     16338
4.0      9232
2.0      4976
Name: count, dtype: int64

In [71]:
tabela_frequencia = df[df['SG_UF'] == 33]['TEST_MOLEC'].value_counts(dropna=False)

print(tabela_frequencia)

TEST_MOLEC
5.0    45798
1.0    38351
3.0     3786
NaN     1408
0.0     1374
4.0     1311
2.0      918
Name: count, dtype: int64

In [72]:
15916+38351

54267

In [73]:
df= df[(df['TEST_SENSI'] == 5) | (df['TEST_MOLEC'] == 1)]

In [74]:
df['SITUA_ENCE'].value_counts (normalize=False)

SITUA_ENCE
1.0     172366
2.0      32713
5.0      11243
3.0       7056
4.0       3676
7.0       1961
8.0       1455
10.0      1346
0.0        208
9.0        191
Name: count, dtype: int64

In [75]:
tabela_frequencia = df[df['SG_UF'] == 33]['SITUA_ENCE'].value_counts(dropna=False)

print(tabela_frequencia)

SITUA_ENCE
1.0     31211
2.0      6430
5.0      1633
3.0       850
4.0       625
10.0      363
7.0       341
8.0       189
9.0        47
NaN        18
0.0        13
Name: count, dtype: int64

In [76]:
31211+ 6430+ 850

38491

In [77]:
df = df[df["SITUA_ENCE"].isin([1, 2, 3])]

In [78]:
df['SITUA_ENCE'].value_counts (normalize=False)

SITUA_ENCE
1.0    172366
2.0     32713
3.0      7056
Name: count, dtype: int64

###Filtrando categorias nao se aplica

In [79]:
df['RAIOX_TORA'].value_counts(dropna=False)

RAIOX_TORA
1.0    140610
4.0     64027
2.0      4539
NaN      1633
3.0      1033
0.0       293
Name: count, dtype: int64

In [80]:
tabela_frequencia = df[df['SG_UF'] == 33]['RAIOX_TORA'].value_counts(dropna=False)

print(tabela_frequencia)

RAIOX_TORA
1.0    32001
4.0     5236
2.0      940
3.0      155
NaN      134
0.0       25
Name: count, dtype: int64

In [81]:
38491-155

38336

In [82]:
df = df[~df['RAIOX_TORA'].isin([3])].copy()

In [83]:
df['BACILOSC_E'].value_counts(dropna=False)

BACILOSC_E
1.0    110960
3.0     74953
2.0     20553
4.0      4636
Name: count, dtype: int64

In [84]:
tabela_frequencia = df[df['SG_UF'] == 33]['BACILOSC_E'].value_counts(dropna=False)

print(tabela_frequencia)

BACILOSC_E
1.0    22687
3.0    11152
2.0     3404
4.0     1093
Name: count, dtype: int64

In [86]:
df = df[~df['BACILOSC_E'].isin([4])].copy()

In [87]:
df['BACILOSC_2'].value_counts(dropna=False)

BACILOSC_2
2.0    80970
3.0    79248
NaN    26645
1.0    14782
0.0     4409
4.0      412
Name: count, dtype: int64

In [88]:
tabela_frequencia = df[df['SG_UF'] == 33]['BACILOSC_2'].value_counts(dropna=False)

print(tabela_frequencia)

BACILOSC_2
3.0    17247
2.0    10013
NaN     6613
1.0     2020
0.0     1024
4.0      326
Name: count, dtype: int64

In [89]:
df = df[~df['BACILOSC_2'].isin([4])].copy()

In [90]:
df['BACILOSC_4'].value_counts(dropna=False)

BACILOSC_4
3.0    87410
2.0    73921
NaN    35708
0.0     5883
1.0     2815
4.0      317
Name: count, dtype: int64

In [91]:
tabela_frequencia = df[df['SG_UF'] == 33]['BACILOSC_4'].value_counts(dropna=False)

print(tabela_frequencia)

BACILOSC_4
3.0    19453
NaN     8728
2.0     6825
0.0     1302
1.0      317
4.0      292
Name: count, dtype: int64

In [92]:
df = df[~df['BACILOSC_4'].isin([4])].copy()

In [93]:
1093+326+292

1711

In [94]:
38336-1711

36625

In [95]:
df[df['SG_UF'] == 33].shape

(36625, 98)

In [96]:
df.shape

(205737, 98)

###Criando ou modificando variaveis

In [97]:


print(df.columns)

Index(['TP_NOT', 'ID_AGRAVO', 'DT_NOTIFIC', 'NU_ANO', 'SG_UF_NOT',
       'ID_MUNICIP', 'ID_REGIONA', 'DT_DIAG', 'ANO_NASC', 'NU_IDADE_N',
       'CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N', 'SG_UF', 'ID_MN_RESI',
       'ID_RG_RESI', 'ID_PAIS', 'NDUPLIC_N', 'IN_VINCULA', 'DT_DIGITA',
       'DT_TRANSUS', 'DT_TRANSDM', 'DT_TRANSSM', 'DT_TRANSRM', 'DT_TRANSRS',
       'DT_TRANSSE', 'CS_FLXRET', 'FLXRECEBI', 'MIGRADO_W', 'ID_OCUPA_N',
       'TRATAMENTO', 'INSTITUCIO', 'RAIOX_TORA', 'TESTE_TUBE', 'FORMA',
       'EXTRAPU1_N', 'EXTRAPU2_N', 'EXTRAPUL_O', 'AGRAVAIDS', 'AGRAVALCOO',
       'AGRAVDIABE', 'AGRAVDOENC', 'AGRAVOUTRA', 'AGRAVOUTDE', 'BACILOSC_E',
       'BACILOS_E2', 'BACILOSC_O', 'CULTURA_ES', 'CULTURA_OU', 'HIV',
       'HISTOPATOL', 'DT_INIC_TR', 'RIFAMPICIN', 'ISONIAZIDA', 'ETAMBUTOL',
       'ESTREPTOMI', 'PIRAZINAMI', 'ETIONAMIDA', 'OUTRAS', 'OUTRAS_DES',
       'TRAT_SUPER', 'NU_CONTATO', 'DOENCA_TRA', 'SG_UF_AT', 'ID_MUNIC_A',
       'DT_NOTI_AT', 'SG_UF_2', 'ID_MUNIC_2', 'BACILOSC_1', 'BACILOSC_2',
       'BACILOSC_3', 'BACILOSC_4', 'BACILOSC_5', 'BACILOSC_6', 'TRATSUP_AT',
       'DT_MUDANCA', 'NU_COMU_EX', 'SITUA_9_M', 'SITUA_12_M', 'SITUA_ENCE',
       'DT_ENCERRA', 'TPUNINOT', 'POP_LIBER', 'POP_RUA', 'POP_SAUDE',
       'POP_IMIG', 'BENEF_GOV', 'AGRAVDROGA', 'AGRAVTABAC', 'TEST_MOLEC',
       'TEST_SENSI', 'ANT_RETRO', 'BAC_APOS_6', 'TRANSF', 'UF_TRANSF',
       'MUN_TRANSF', 'ANO_BASE'],
      dtype='object')

###Variavel desfecho

In [98]:
# Criando a variável 'cura' baseada na coluna 'SITUA_ENCE'
df['cura'] = df['SITUA_ENCE'].apply(lambda x: 1 if x == 1 else 0)

In [100]:
df['cura'].value_counts(dropna=False)

cura
1    167356
0     38381
Name: count, dtype: int64

###Populacao

In [101]:
df['ID_MN_RESI'].value_counts(dropna=False)

ID_MN_RESI
355030    28676
330455    23026
130260    10308
292740     5301
431490     3083
          ...
210955        1
316160        1
410775        1
330160        1
411390        1
Name: count, Length: 3472, dtype: int64

In [102]:
df_pop = pd.read_csv('popBR.csv',sep=';',encoding='latin1')

In [103]:
df_pop.head()

       cod                        nome    pop
0  1100015  Alta Floresta D'Oeste (RO)  21494
1  1100023              Ariquemes (RO)  96833
2  1100031                 Cabixi (RO)   5351
3  1100049                 Cacoal (RO)  86887
4  1100056             Cerejeiras (RO)  15890

In [104]:
df_pop['ID_MN_RESI'] = df_pop['cod'].astype(str).str[:-1].astype(int)

In [105]:
df.shape

(205737, 99)

In [106]:
df = df.merge(df_pop[['ID_MN_RESI', 'pop']], on='ID_MN_RESI', how='left')

In [107]:
df.shape

(205737, 100)

Acrescentando variável front

In [108]:
df['ID_MN_RESI'].unique()

array([250760, 250750, 250320, ..., 350995, 310140, 500625])

In [109]:
codigos_fronteira_br = [
    # Amapá
    160050,  # Oiapoque
    160027,   # Laranjal do Jari

    #Para
    150375,  # Jacareacanga
    150503,  # Novo Progresso
    150172,  # Brasil Novo
    150145,  # Alenquer

    # Roraima
    140002,  # Amajari
    140005,  # Alto Alegre
    140015,  # Bonfim
    140040,  # Normandia
    140045,  # Pacaraima
    140070,  # Uiramutã
    140020,   # Caracaraí

    # Amazonas
    130002, 130006,

    # Acre
    120005,  # Assis Brasil
    120010,  # Brasiléia
    120025,  # Epitaciolândia
    120017,  # Capixaba
    120038,  # Plácido de Castro
    120080,  # Porto Acre
    120043,  # Santa Rosa do Purus
    120035,  # Marechal Thaumaturgo
    120039,  # Porto Walter
    120042,  # Rodrigues Alves
    120020,  # Cruzeiro do Sul
    120033,   # Mâncio Lima

    # Rondônia
    110001,  # Alta Floresta d'Oeste
    110002,  # Ariquemes
    110003,  # Cabixi
    110004,  # Cacoal
    110005,  # Cerejeiras
    110006,  # Colorado do Oeste
    110007,  # Corumbiara
    110008,  # Costa Marques
    110009,  # Espigão d'Oeste
    110010,  # Guajará-Mirim
    110011,  # Jaru
    110012,  # Ji-Paraná
    110013,  # Machadinho d'Oeste
    110014,  # Nova Brasilândia d'Oeste
    110015,  # Ouro Preto do Oeste
    110018,   # Pimenteiras do Oeste

    # Mato Grosso
    510250,  # Cáceres
    510682,  # Porto Esperidião
    510550,  # Vila Bela da Santíssima Trindade
    510330,  # Comodoro
    510675,  # Pontes e Lacerda

    # Mato Grosso do Sul
    500124, 500210, 500280, 500315, 500320, 500480, 500500, 500520, 500568,
    500635, 500660, 500690, 500770, # Added comma here

    # Paraná
    410290, 410315, 412430, 412030, 411920, 411960, 410400, 410410, 412382,
    412350, 412570, 412705, 410830, 410880, 412740, 412862, 410060, 411585,
    411460, # Added comma here

    # Santa Catarina
    420500,  # Dionísio Cerqueira
    421223,  # Princesa
    420930,  # Guarujá do Sul
    421605,  # São José do Cedro
    420180,   # Anchieta

    # Rio Grande do Sul
    430003, 430060, 430130, 430210, 430280, 430300, 430520, 430660,
    430890, 430960, 431020, 431100, 431310, 431510, 431540, 431560,
    431620, 431720, 431880, 431960, 432000, 432200, 432240, 432250
]

df['front'] = np.where(
    df['ID_MN_RESI'].astype(int).isin(codigos_fronteira_br),
    1,
    0
)

print(df['front'].value_counts())

front
0    202085
1      3652
Name: count, dtype: int64

In [110]:
print(pd.crosstab(df['SG_UF'], df['front']))

front      0     1
SG_UF
0          9     0
11      1728   415
12      1879   271
13     11800     8
14      1528   174
15      3992    10
16      1111    87
17       597     0
21      3427     0
22      1526     0
23      4575     0
24      3816     0
25      1684     0
26      6109     0
27      2446     0
28      2680     0
29      8118     0
31      9578     0
32      4604     0
33     36625     0
35     67162     0
41      6207   777
42      4822    21
43      7964  1348
50      3029   528
51       870    13
52      3371     0
53       828     0

In [111]:
df.shape

(205737, 101)

In [112]:
# Filtrar onde SG_UF == 0
df_zero = df[df['SG_UF'] == 0]

# Tabela de frequência absoluta
freq_abs = df_zero['ID_MN_RESI'].value_counts()

print(freq_abs)

ID_MN_RESI
0    9
Name: count, dtype: int64

In [113]:
df = df[df['SG_UF'] > 0]

In [114]:
df.shape

(205728, 101)

###Datas

In [115]:

# Selecionando as colunas específicas
df_selecionado = df[['DT_NOTIFIC', 'DT_DIAG', 'DT_INIC_TR', 'DT_ENCERRA']]

# Verificando o formato (tipo) das variáveis (colunas)
print(df_selecionado.dtypes)

# Convertendo as colunas para o formato datetime
df_selecionado['DT_DIAG'] = df_selecionado['DT_DIAG'].astype(str).str.replace(r'\.0$', '', regex=True)
df_selecionado['DT_DIAG'] = pd.to_datetime(df_selecionado['DT_DIAG'], format='%Y%m%d', errors='coerce')

df_selecionado['DT_INIC_TR'] = df_selecionado['DT_INIC_TR'].astype(str).str.replace(r'\.0$', '', regex=True)
df_selecionado['DT_INIC_TR'] = pd.to_datetime(df_selecionado['DT_INIC_TR'], format='%Y%m%d', errors='coerce')

# Verificando o novo formato das variáveis
print(df_selecionado.dtypes)

df_selecionado['DT_ENCERRA2'] = df_selecionado['DT_ENCERRA'].astype(str).str.replace(r'\.0$', '', regex=True)
df_selecionado['DT_ENCERRA2'] = pd.to_datetime(
    df_selecionado['DT_ENCERRA2'],
    format='%Y%m%d',
    errors='coerce'  # Trata erros e define valores inválidos como NaT
)

# Definindo como NaT as datas anteriores a 2000
df_selecionado['DT_ENCERRA2'] = df_selecionado['DT_ENCERRA2'].apply(
    lambda x: pd.NaT if pd.notna(x) and x.year < 2000 else x
)

# Calculando a diferença em dias entre 'DT_DIAG' e 'DT_INIC_TR'
df_selecionado['TEMPO_DIAG_TRAT'] = (df_selecionado['DT_INIC_TR'] - df_selecionado['DT_DIAG']).dt.days
df_selecionado['TEMPO_TRAT_ENC'] = (df_selecionado['DT_ENCERRA2'] - df_selecionado['DT_INIC_TR']).dt.days
df_selecionado['TEMPO_DIAG_ENC'] = (df_selecionado['DT_ENCERRA2'] - df_selecionado['DT_DIAG']).dt.days

import numpy as np

# Condição para substituir 'TEMPO_TRAT_OBITO' por NaN quando for igual a 'TEMPO_DIAG_OBITO' e o valor for negativo
df_selecionado['TEMPO_TRAT_ENC'] = np.where(
    (df_selecionado['TEMPO_TRAT_ENC'] < 0),
    0,  # Substitui por NaN
    df_selecionado['TEMPO_TRAT_ENC']  # Caso contrário, mantém o valor original
)

# Convertendo as colunas para o formato datetime
df['DT_DIAG'] = df['DT_DIAG'].astype(str).str.replace(r'\.0$', '', regex=True)
df['DT_DIAG'] = pd.to_datetime(df['DT_DIAG'], format='%Y%m%d', errors='coerce')

df['DT_INIC_TR'] = df['DT_INIC_TR'].astype(str).str.replace(r'\.0$', '', regex=True)
df['DT_INIC_TR'] = pd.to_datetime(df['DT_INIC_TR'], format='%Y%m%d', errors='coerce')


# Criando uma nova coluna DT_ENCERRA2, convertendo a coluna DT_ENCERRA para datetime
df['DT_ENCERRA'] = df['DT_ENCERRA'].astype(str).str.replace(r'\.0$', '', regex=True)
df['DT_ENCERRA'] = pd.to_datetime(
    df['DT_ENCERRA'],
    format='%Y%m%d',
    errors='coerce'  # Trata erros e define valores inválidos como NaT
)

# Definindo como NaT as datas anteriores a 2000
df['DT_ENCERRA'] = df['DT_ENCERRA'].apply(
    lambda x: pd.NaT if pd.notna(x) and x.year < 2000 else x
)

# Calculando a diferença em dias entre 'DT_DIAG' e 'DT_INIC_TR'
df['TEMPO_DIAG_TRAT'] = (df['DT_INIC_TR'] - df['DT_DIAG']).dt.days

# Calculando a diferença em dias entre 'DT_ENCERRA2' e 'DT_INIC_TR'
df['TEMPO_TRAT_ENC'] = (df['DT_ENCERRA'] - df['DT_INIC_TR']).dt.days

# Calculando a diferença em dias entre 'DT_ENCERRA2' e 'DT_DIAG'
df['TEMPO_DIAG_ENC'] = (df['DT_ENCERRA'] - df['DT_DIAG']).dt.days

# Condição para substituir 'TEMPO_TRAT_ENC' por NaN quando for igual a 'TEMPO_DIAG_ENC' e o valor for negativo
df['TEMPO_TRAT_ENC'] = np.where(
    (df['TEMPO_TRAT_ENC'] < 0),
    0,  # Substitui por NaN
    df['TEMPO_TRAT_ENC']  # Caso contrário, mantém o valor original
)

DT_NOTIFIC    object
DT_DIAG       object
DT_INIC_TR    object
DT_ENCERRA    object
dtype: object

/tmp/ipykernel_1829/1483725642.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selecionado['DT_DIAG'] = df_selecionado['DT_DIAG'].astype(str).str.replace(r'\.0$', '', regex=True)
/tmp/ipykernel_1829/1483725642.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selecionado['DT_DIAG'] = pd.to_datetime(df_selecionado['DT_DIAG'], format='%Y%m%d', errors='coerce')
/tmp/ipykernel_1829/1483725642.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selecionado['DT_INIC_TR'] = df_selecionado['DT_INIC_TR'].astype(str).str.replace(r'\.0$', '', regex=True)
/tmp/ipykernel_1829/1483725642.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selecionado['DT_INIC_TR'] = pd.to_datetime(df_selecionado['DT_INIC_TR'], format='%Y%m%d', errors='coerce')

DT_NOTIFIC            object
DT_DIAG       datetime64[ns]
DT_INIC_TR    datetime64[ns]
DT_ENCERRA            object
dtype: object

/tmp/ipykernel_1829/1483725642.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selecionado['DT_ENCERRA2'] = df_selecionado['DT_ENCERRA'].astype(str).str.replace(r'\.0$', '', regex=True)
/tmp/ipykernel_1829/1483725642.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selecionado['DT_ENCERRA2'] = pd.to_datetime(
/tmp/ipykernel_1829/1483725642.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selecionado['DT_ENCERRA2'] = df_selecionado['DT_ENCERRA2'].apply(
/tmp/ipykernel_1829/1483725642.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selecionado['TEMPO_DIAG_TRAT'] = (df_selecionado['DT_INIC_TR'] - df_selecionado['DT_DIAG']).dt.days
/tmp/ipykernel_1829/1483725642.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selecionado['TEMPO_TRAT_ENC'] = (df_selecionado['DT_ENCERRA2'] - df_selecionado['DT_INIC_TR']).dt.days
/tmp/ipykernel_1829/1483725642.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selecionado['TEMPO_DIAG_ENC'] = (df_selecionado['DT_ENCERRA2'] - df_selecionado['DT_DIAG']).dt.days
/tmp/ipykernel_1829/1483725642.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selecionado['TEMPO_TRAT_ENC'] = np.where(

In [116]:
df['TEMPO_DIAG_TRAT'] = df['TEMPO_DIAG_TRAT'].clip(lower=0)
#substituir todos os valores menores que 0 por 0.

In [117]:
df[df['TEMPO_DIAG_TRAT'] <= 14]['TEMPO_DIAG_TRAT'].value_counts(dropna=False)

TEMPO_DIAG_TRAT
0.0     78729
1.0     22249
2.0      8151
3.0      5982
4.0      4643
5.0      3989
6.0      3879
7.0      3707
8.0      2403
9.0      1435
10.0     1264
11.0     1046
14.0     1035
13.0     1007
12.0      946
Name: count, dtype: int64

In [118]:
df[df['TEMPO_DIAG_TRAT'] > 14]['TEMPO_DIAG_TRAT'].value_counts(dropna=False)

TEMPO_DIAG_TRAT
15.0     720
16.0     495
21.0     461
17.0     456
20.0     435
        ...
546.0      1
392.0      1
400.0      1
210.0      1
529.0      1
Name: count, Length: 513, dtype: int64

In [119]:
df['TEMPO_DIAG_TRAT'].isna().sum()

np.int64(54225)

In [121]:
# Criar variável binária mantendo valores ausentes
df['TEMPO_DIAG_TRAT_14'] = np.where(df['TEMPO_DIAG_TRAT'].isna(),
                                    np.nan,
                                    (df['TEMPO_DIAG_TRAT'] > 14).astype(int))

In [123]:
df['TEMPO_DIAG_TRAT_14'].value_counts(dropna=False)

TEMPO_DIAG_TRAT_14
0.0    140465
NaN     54225
1.0     11038
Name: count, dtype: int64

Criando data da baciloscopia 2 e 4

In [124]:
df["DT_INIC_TR"].head()

0   2015-05-19
1   2015-07-06
2   2015-12-01
3   2015-12-17
4   2015-02-10
Name: DT_INIC_TR, dtype: datetime64[ns]

In [125]:
df['DT_INIC_TR'].isna().sum()

np.int64(54225)

In [127]:
df[df['SG_UF'] == 33]['DT_INIC_TR'].isna().sum()

np.int64(10995)

In [128]:
df[df['SG_UF'] == 33]['DT_ENCERRA'].isna().sum()

np.int64(10995)

In [129]:
df = df[df["DT_INIC_TR"].notna()]

In [130]:
df['DT_INIC_TR'].isna().sum()

np.int64(0)

In [131]:
df = df[df["DT_ENCERRA"].notna()]

In [132]:
df['DT_ENCERRA'].isna().sum()

np.int64(0)

In [133]:
df.shape

(151503, 105)

In [134]:
df[df['SG_UF'] == 33].shape

(25630, 105)

In [135]:
36625-10995

25630

In [ ]:
from pandas.tseries.offsets import DateOffset
df["DT_CUL"] = df["DT_INIC_TR"] + DateOffset(months=2)
df["DT_BAC2"] = df["DT_INIC_TR"] + DateOffset(months=2)
df["DT_BAC4"] = df["DT_INIC_TR"] + DateOffset(months=4)

In [ ]:
df[["DT_INIC_TR", "DT_CUL", "DT_BAC2", "DT_BAC4", "DT_ENCERRA"]].head()

  DT_INIC_TR     DT_CUL    DT_BAC2    DT_BAC4 DT_ENCERRA
0 2015-05-19 2015-07-19 2015-07-19 2015-09-19 2015-06-22
1 2015-07-06 2015-09-06 2015-09-06 2015-11-06 2015-09-04
2 2015-12-01 2016-02-01 2016-02-01 2016-04-01 2016-05-01
3 2015-12-17 2016-02-17 2016-02-17 2016-04-17 2016-06-17
4 2015-02-10 2015-04-10 2015-04-10 2015-06-10 2015-05-02

In [ ]:
inicio = df["DT_ENCERRA"].min()
fim = df["DT_ENCERRA"].max()

print("Começa em:", inicio)
print("Termina em:", fim)

###Elegibilidade - Criando variaveis para definir quem é elegível para as etapas 2 e 3

In [ ]:
# eleg_eta2: 1 se DT_BAC2 <= DT_ENCERRA, senão 0
df['eleg_eta2'] = np.where(
    df['DT_BAC2'] <= df['DT_ENCERRA'],
    1,
    0
)

# eleg_eta3: 1 se DT_BAC4 <= DT_ENCERRA, senão 0
df['eleg_eta3'] = np.where(
    df['DT_BAC4'] <= df['DT_ENCERRA'],
    1,
    0
)

In [ ]:
df['eleg_eta2'].value_counts(dropna=False)

eleg_eta2
1    142023
0      9480
Name: count, dtype: int64

In [ ]:
df['eleg_eta3'].value_counts(dropna=False)

eleg_eta3
1    133825
0     17678
Name: count, dtype: int64

Criando ano de encerramento e ano de início do tratamento

In [ ]:
df['ano_inc_trat'] = df['DT_INIC_TR'].dt.year
df['ano_encerra'] = df['DT_ENCERRA'].dt.year

In [ ]:
df['ano_inc_trat'].value_counts(dropna=False)

ano_inc_trat
2023    25896
2022    23789
2021    19823
2019    18951
2020    18061
2018    17488
2017    15009
2015    11862
2024      480
2016      128
2025       16
Name: count, dtype: int64

In [ ]:
df[df['ano_inc_trat'].isna()][['DT_INIC_TR', 'ano_inc_trat']]

Empty DataFrame
Columns: [DT_INIC_TR, ano_inc_trat]
Index: []

In [ ]:
df['ano_encerra'].value_counts(dropna=False)

ano_encerra
2023    24960
2022    22300
2020    18553
2019    18495
2021    18310
2018    16283
2024    13757
2016     7139
2017     6756
2015     4779
2025      171
Name: count, dtype: int64

In [ ]:
df.shape

(151503, 112)

###Ajustando categorias das variaveis

In [ ]:
tabela_frequencia = df['CS_ESCOL_N'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

CS_ESCOL_N
3.0     33364
9.0     26851
5.0     25819
6.0     14732
1.0     13472
NaN      8600
4.0      8389
2.0      5648
0.0      5565
7.0      4859
8.0      3499
10.0      705
Name: count, dtype: int64

In [ ]:
import numpy as np

# Substituindo diretamente os valores
df.loc[df['CS_ESCOL_N'] == '', 'CS_ESCOL_N'] = np.nan

# Garantir que a coluna CS_ESCOL_N esteja no formato numérico
df['CS_ESCOL_N'] = pd.to_numeric(df['CS_ESCOL_N'], errors='coerce')

In [ ]:
tabela_frequencia = df['CS_ESCOL_N'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

CS_ESCOL_N
3.0     33364
9.0     26851
5.0     25819
6.0     14732
1.0     13472
NaN      8600
4.0      8389
2.0      5648
0.0      5565
7.0      4859
8.0      3499
10.0      705
Name: count, dtype: int64

0. Analfabeto,  1. 1ª a 4ª série incompleta do EF, 2. 4ª série completa do EF ( antigo 1° grau), 3. 5ª à 8ª série incompleta do EF (antigo ginásio ou 1° grau), 4. Ensino fundamental completo (antigo ginásio ou 1° grau), 5. Ensino médio incompleto (antigo colegial ou 2° grau), 6. Ensino médio completo (antigo colegial ou 2° grau), 7. Educação superior incompleta,  8. Educação superior completa,  9. Ignorado, 10. Não se aplica

In [ ]:
# Criar a variável ESCOLA_FAIXA
df['ESCOLA_FAIXA'] = np.select(
    [
        df['CS_ESCOL_N'].between(0, 5, inclusive='both'),  # 0 a 5
        df['CS_ESCOL_N'].between(6, 8, inclusive='both'),  # 6 a 8
        df['CS_ESCOL_N'] == 10                             # não se aplica
    ],
    [0, 1, 10],
    default=np.nan  # mantém os valores ausentes
)

# Converter para inteiro com suporte a NaN
df['ESCOLA_FAIXA'] = df['ESCOLA_FAIXA'].astype('Int64')

In [ ]:
df['ESCOLA_FAIXA'].value_counts(dropna=False)

ESCOLA_FAIXA
0       92257
<NA>    35451
1       23090
10        705
Name: count, dtype: Int64

In [ ]:
tabela_frequencia = df['CS_SEXO'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

CS_SEXO
M    110396
F     41097
I        10
Name: count, dtype: int64

In [ ]:
# Substituindo diretamente os valores
df.loc[df['CS_SEXO'] == 'I', 'CS_SEXO'] = np.nan

In [ ]:
df['CS_SEXO'] = df['CS_SEXO'].replace('F', 0)
df['CS_SEXO'] = df['CS_SEXO'].replace('M', 1)

/tmp/ipykernel_5628/3964444062.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['CS_SEXO'] = df['CS_SEXO'].replace('M', 1)

In [ ]:
tabela_frequencia = df['CS_RACA'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

CS_RACA
4.0    76278
1.0    42310
2.0    20982
9.0     6412
NaN     2408
3.0     1461
5.0     1147
0.0      504
6.0        1
Name: count, dtype: int64

In [ ]:
# Substituindo diretamente os valores
df.loc[df['CS_RACA'] == '', 'CS_RACA'] = np.nan
df.loc[df['CS_RACA'] == 0, 'CS_RACA'] = np.nan
df.loc[df['CS_RACA'] == 6, 'CS_RACA'] = np.nan
df.loc[df['CS_RACA'] == 9, 'CS_RACA'] = np.nan

In [ ]:
tabela_frequencia = df['CS_RACA'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

CS_RACA
4.0    76278
1.0    42310
2.0    20982
NaN     9325
3.0     1461
5.0     1147
Name: count, dtype: int64

In [ ]:
tabela_frequencia = df['AGRAVALCOO'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

AGRAVALCOO
2.0    116154
1.0     30234
9.0      4283
NaN       725
0.0       107
Name: count, dtype: int64

In [ ]:
df.loc[df['AGRAVALCOO'] == 0, 'AGRAVALCOO'] = np.nan

# Substituindo diretamente os valores 2 por 0
df.loc[df['AGRAVALCOO'] == 2, 'AGRAVALCOO'] = 0

# Substituindo diretamente os valores
df.loc[df['AGRAVALCOO'] == '', 'AGRAVALCOO'] = np.nan
df.loc[df['AGRAVALCOO'] == 9, 'AGRAVALCOO'] = np.nan

In [ ]:
tabela_frequencia = df['AGRAVALCOO'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

AGRAVALCOO
0.0    116154
1.0     30234
NaN      5115
Name: count, dtype: int64

In [ ]:
tabela_frequencia = df['AGRAVDIABE'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

AGRAVDIABE
2.0    132047
1.0     14072
9.0      4463
NaN       797
0.0       124
Name: count, dtype: int64

In [ ]:
df.loc[df['AGRAVDIABE'] == 0, 'AGRAVDIABE'] = np.nan
df.loc[df['AGRAVDIABE'] == 9, 'AGRAVDIABE'] = np.nan

# Substituindo diretamente os valores 2 por 0
df.loc[df['AGRAVDIABE'] == 2, 'AGRAVDIABE'] = 0

# Substituindo diretamente os valores ''
df.loc[df['AGRAVDIABE'] == '', 'AGRAVDIABE'] = np.nan

In [ ]:
tabela_frequencia = df['AGRAVDIABE'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

AGRAVDIABE
0.0    132047
1.0     14072
NaN      5384
Name: count, dtype: int64

In [ ]:
tabela_frequencia = df['AGRAVDOENC'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

AGRAVDOENC
2.0    142709
9.0      4520
1.0      3059
NaN      1042
0.0       173
Name: count, dtype: int64

In [ ]:
df.loc[df['AGRAVDOENC'] == 0, 'AGRAVDOENC'] = np.nan

# Substituindo diretamente os valores 2 por 0
df.loc[df['AGRAVDOENC'] == 2, 'AGRAVDOENC'] = 0

# Substituindo diretamente os valores ''
df.loc[df['AGRAVDOENC'] == '', 'AGRAVDOENC'] = np.nan
df.loc[df['AGRAVDOENC'] == 9, 'AGRAVDOENC'] = np.nan

In [ ]:
tabela_frequencia = df['AGRAVDOENC'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

AGRAVDOENC
0.0    142709
NaN      5735
1.0      3059
Name: count, dtype: int64

In [ ]:
tabela_frequencia = df['AGRAVDROGA'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

AGRAVDROGA
2.0    116727
1.0     29136
9.0      4767
NaN       675
0.0       198
Name: count, dtype: int64

In [ ]:
# Substituindo diretamente os valores 0
df.loc[df['AGRAVDROGA'] == 0, 'AGRAVDROGA'] = np.nan

# Substituindo diretamente os valores 2 por 0
df.loc[df['AGRAVDROGA'] == 2, 'AGRAVDROGA'] = 0

# Substituindo diretamente os valores
df.loc[df['AGRAVDROGA'] == '', 'AGRAVDROGA'] =np.nan
df.loc[df['AGRAVDROGA'] == 9, 'AGRAVDROGA'] = np.nan

In [ ]:
tabela_frequencia = df['AGRAVDROGA'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

AGRAVDROGA
0.0    116727
1.0     29136
NaN      5640
Name: count, dtype: int64

In [ ]:
tabela_frequencia = df['AGRAVTABAC'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

AGRAVTABAC
2.0    101521
1.0     44812
9.0      4249
NaN       723
0.0       198
Name: count, dtype: int64

In [ ]:
# Substituindo diretamente os valores 0
df.loc[df['AGRAVTABAC'] == 0, 'AGRAVTABAC'] = np.nan

# Substituindo diretamente os valores 2 por 0
df.loc[df['AGRAVTABAC'] == 2, 'AGRAVTABAC'] = 0

# Substituindo diretamente os valores ''
df.loc[df['AGRAVTABAC'] == '', 'AGRAVTABAC'] = np.nan
df.loc[df['AGRAVTABAC'] == 9, 'AGRAVTABAC'] = np.nan

In [ ]:
tabela_frequencia = df['AGRAVTABAC'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

AGRAVTABAC
0.0    101521
1.0     44812
NaN      5170
Name: count, dtype: int64

In [ ]:
tabela_frequencia = df['POP_RUA'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

POP_RUA
2.0    142922
1.0      5498
9.0      1957
NaN       837
0.0       289
Name: count, dtype: int64

In [ ]:
df.loc[df['POP_RUA'] == '', 'POP_RUA'] = np.nan
df.loc[df['POP_RUA'] == 0, 'POP_RUA'] = np.nan
df.loc[df['POP_RUA'] == 9, 'POP_RUA'] = np.nan
df.loc[df['POP_RUA'] == 2, 'POP_RUA'] = 0

In [ ]:
tabela_frequencia = df['POP_RUA'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

POP_RUA
0.0    142922
1.0      5498
NaN      3083
Name: count, dtype: int64

In [ ]:
tabela_frequencia = df['POP_LIBER'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

POP_LIBER
2.0    124425
1.0     24714
9.0      1599
NaN       555
0.0       210
Name: count, dtype: int64

In [ ]:
df.loc[df['POP_LIBER'] == '', 'POP_LIBER'] = np.nan
df.loc[df['POP_LIBER'] == 0, 'POP_LIBER'] = np.nan
df.loc[df['POP_LIBER'] == 9, 'POP_LIBER'] = np.nan
df.loc[df['POP_LIBER'] == 2, 'POP_LIBER'] = 0

In [ ]:
tabela_frequencia = df['POP_LIBER'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

POP_LIBER
0.0    124425
1.0     24714
NaN      2364
Name: count, dtype: int64

In [ ]:
tabela_frequencia = df['POP_IMIG'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

POP_IMIG
2.0    145986
9.0      2094
1.0      1320
NaN      1012
3.0       781
0.0       310
Name: count, dtype: int64

In [ ]:
df.loc[df['POP_IMIG'] == '', 'POP_IMIG'] = np.nan
df.loc[df['POP_IMIG'] == 0, 'POP_IMIG'] = np.nan
df.loc[df['POP_IMIG'] == 9, 'POP_IMIG'] = np.nan
df.loc[df['POP_IMIG'] == 2, 'POP_IMIG'] = 0

In [ ]:
df.loc[df['POP_IMIG'] == 3, 'POP_IMIG'] = np.nan

In [ ]:
tabela_frequencia = df['POP_IMIG'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

POP_IMIG
0.0    145986
NaN      4197
1.0      1320
Name: count, dtype: int64

In [ ]:
import pandas as pd

df["BENEF_GOV"] = pd.to_numeric(df["BENEF_GOV"], errors="coerce")

In [ ]:
tabela_frequencia = df['BENEF_GOV'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

BENEF_GOV
2.0    76494
NaN    41053
9.0    13085
0.0    11716
1.0     9154
8.0        1
Name: count, dtype: int64

In [ ]:
df.loc[(df['BENEF_GOV'] == 9), 'BENEF_GOV'] = np.nan
df.loc[(df['BENEF_GOV'] == 0), 'BENEF_GOV'] = np.nan
df.loc[(df['BENEF_GOV'] == 2), 'BENEF_GOV'] = 0
df.loc[(df['BENEF_GOV'] > 6), 'BENEF_GOV'] = np.nan

In [ ]:
tabela_frequencia = df['BENEF_GOV'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

BENEF_GOV
0.0    76494
NaN    65855
1.0     9154
Name: count, dtype: int64

In [ ]:
# Suponha que seu DataFrame seja df e a variável seja baciloscopia no diagnostico
tabela_frequencia = df['BACILOSC_E'].value_counts()

# Mostrar a tabela de frequência
print(tabela_frequencia)

BACILOSC_E
1.0    81924
3.0    54740
2.0    14839
Name: count, dtype: int64

In [ ]:
df.loc[df['BACILOSC_E'] == '', 'BACILOSC_E'] = np.nan
df.loc[df['BACILOSC_E'] == 0, 'BACILOSC_E'] = np.nan

In [ ]:
# Suponha que seu DataFrame seja df e a variável seja baciloscopia no diagnostico
tabela_frequencia = df['BACILOSC_E'].value_counts()

# Mostrar a tabela de frequência
print(tabela_frequencia)

BACILOSC_E
1.0    81924
3.0    54740
2.0    14839
Name: count, dtype: int64

In [ ]:
tabela_frequencia = df['BACILOSC_2'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

BACILOSC_2
2.0    59857
3.0    57127
NaN    20664
1.0    11063
0.0     2792
Name: count, dtype: int64

In [ ]:
df.loc[df['BACILOSC_2'] == '', 'BACILOSC_2'] = np.nan
df.loc[df['BACILOSC_2'] == 0, 'BACILOSC_2'] = np.nan

In [ ]:
tabela_frequencia = df['BACILOSC_4'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

BACILOSC_4
3.0    62585
2.0    55306
NaN    27749
0.0     3765
1.0     2098
Name: count, dtype: int64

In [ ]:
df.loc[df['BACILOSC_4'] == '', 'BACILOSC_4'] = np.nan
df.loc[df['BACILOSC_4'] == 0, 'BACILOSC_4'] = np.nan
#df.loc[df['BACILOSC_4'] == 2, 'BACILOSC_4'] = 0

In [ ]:
tabela_frequencia = df['BACILOSC_4'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

BACILOSC_4
3.0    62585
2.0    55306
NaN    31514
1.0     2098
Name: count, dtype: int64

In [ ]:
tabela_frequencia = df['RAIOX_TORA'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

RAIOX_TORA
1.0    101299
4.0     45621
2.0      3170
NaN      1204
0.0       209
Name: count, dtype: int64

In [ ]:
df.loc[df['RAIOX_TORA'] == '', 'RAIOX_TORA'] = np.nan
df.loc[df['RAIOX_TORA'] == 0, 'RAIOX_TORA'] = np.nan
#df.loc[df['RAIOX_TORA'] == 2, 'RAIOX_TORA'] = 0

In [ ]:
tabela_frequencia = df['RAIOX_TORA'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

RAIOX_TORA
1.0    101299
4.0     45621
2.0      3170
NaN      1413
Name: count, dtype: int64

In [ ]:
tabela_frequencia = df['CULTURA_ES'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

CULTURA_ES
1.0    73498
4.0    60764
2.0    13846
3.0     3285
0.0      110
Name: count, dtype: int64

In [ ]:
df.loc[df['CULTURA_ES'] == '', 'CULTURA_ES'] = np.nan
df.loc[df['CULTURA_ES'] == 0, 'CULTURA_ES'] = np.nan
#df.loc[df['CULTURA_ES'] == 2, 'CULTURA_ES'] = 0

In [ ]:
tabela_frequencia = df['CULTURA_ES'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

CULTURA_ES
1.0    73498
4.0    60764
2.0    13846
3.0     3285
NaN      110
Name: count, dtype: int64

In [ ]:
tabela_frequencia = df['TRATSUP_AT'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

TRATSUP_AT
1.0    65002
2.0    62491
NaN    13315
9.0     8533
0.0     2162
Name: count, dtype: int64

In [ ]:
df.loc[df['TRATSUP_AT'] == '', 'TRATSUP_AT'] = np.nan
df.loc[df['TRATSUP_AT'] == 0, 'TRATSUP_AT'] = np.nan
df.loc[df['TRATSUP_AT'] == 9, 'TRATSUP_AT'] = np.nan
#df.loc[df['TRATSUP_AT'] == 2, 'TRATSUP_AT'] = 0

In [ ]:
tabela_frequencia = df['TRATSUP_AT'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

TRATSUP_AT
1.0    65002
2.0    62491
NaN    24010
Name: count, dtype: int64

In [ ]:
#Garantir que a coluna  esteja no formato numérico
df['NU_CONTATO'] = pd.to_numeric(df['NU_CONTATO'], errors='coerce')

In [ ]:
tabela_frequencia = df['NU_CONTATO'].value_counts(dropna=False)

# Mostrar a tabela de frequência
print(tabela_frequencia)

NU_CONTATO
0.0     32014
2.0     23131
1.0     20986
3.0     20823
4.0     15103
        ...
89.0        1
79.0        1
96.0        1
84.0        1
68.0        1
Name: count, Length: 99, dtype: int64

In [ ]:
tabela_frequencia = (
    df[df["NU_CONTATO"] <= 50]["NU_CONTATO"]
    .value_counts(dropna=False)
    .sort_index()
)

print(tabela_frequencia)

NU_CONTATO
0.0     32014
1.0     20986
2.0     23131
3.0     20823
4.0     15103
5.0     10158
6.0      6355
7.0      3946
8.0      3137
9.0      1965
10.0     2129
11.0     1041
12.0     1077
13.0      762
14.0      811
15.0     1000
16.0      582
17.0      344
18.0      420
19.0      317
20.0      739
21.0      239
22.0      256
23.0      199
24.0      170
25.0      212
26.0      148
27.0      170
28.0      178
29.0      157
30.0      254
31.0      110
32.0      171
33.0      108
34.0       94
35.0       82
36.0       64
37.0       38
38.0       66
39.0       30
40.0       76
41.0       20
42.0       26
43.0        6
44.0        8
45.0       18
46.0       11
47.0        9
48.0       12
49.0       11
50.0      171
Name: count, dtype: int64

In [ ]:
tabela_frequencia = (
    df[df["NU_CONTATO"] > 50]["NU_CONTATO"]
    .value_counts(dropna=False)
    .sort_index()
)

print(tabela_frequencia)

NU_CONTATO
51.0      2
52.0      6
53.0      8
54.0      5
55.0      6
56.0      5
57.0      4
58.0      6
59.0      6
60.0     21
61.0      4
62.0      2
63.0      4
64.0      2
66.0      3
67.0      3
68.0      1
69.0      3
70.0      7
71.0      2
72.0      4
73.0      2
74.0      2
75.0      5
76.0      2
77.0      2
78.0      6
79.0      1
80.0     20
81.0      4
82.0      8
83.0      2
84.0      1
85.0      2
86.0      5
87.0      2
88.0      4
89.0      1
90.0      6
91.0      3
92.0      8
93.0      3
94.0      4
95.0      3
96.0      1
98.0      4
99.0    152
Name: count, dtype: int64

In [ ]:
df.loc[df['NU_CONTATO'] == '', 'NU_CONTATO'] = np.nan
df.loc[df['NU_CONTATO'] == 99, 'NU_CONTATO'] = np.nan

In [ ]:
import pandas as pd

df["CONTATO_5_15"] = pd.cut(
    df["NU_CONTATO"],
    bins=[-float("inf"), 5, 15, float("inf")],
    labels=[0, 1, 2]
).astype("Int64")

In [ ]:
tabela_frequencia = df['CONTATO_5_15'].value_counts(dropna=False)

In [ ]:
#TRABALHAR COM A IDADE

print(df['NU_IDADE_N'].unique())

[4026. 4030. 4062. 4036. 4049. 4039. 4054. 4001. 4027. 4019. 4023. 4034.
 4046. 4045. 4020. 4035. 4028. 4032. 4076. 4051. 4044. 4078. 4048. 4040.
 4058. 4025. 4021. 4059. 4024. 4029. 4050. 4057. 4042. 4017. 4053. 4041.
 4043. 4033. 4064. 4056. 4022. 4079. 4065. 4073. 4067. 4047. 4037. 4038.
 4052. 4014. 4018. 4016. 4031. 4070. 4077. 4055. 4015. 4068. 4061. 4060.
 4072. 4011. 4063. 4074. 4069. 4093. 4071. 3001. 4066. 4080. 4013. 4075.
 4012. 3004. 4082. 4085. 4088. 4081. 4083. 2000. 4086. 4004. 4002. 4084.
 4087. 4090. 1001. 4010. 4003. 4092. 4000. 4007. 3003. 4089. 4009. 3002.
 1000. 4005. 3006. 4104. 2007. 4095. 4008. 4094. 3005. 4097. 4096. 2002.
 3035. 2025. 4091. 3010. 4006.    0. 3009. 2010. 4100. 4099. 1020. 2021.
 1037. 4098.   nan 2030. 4108. 2017. 4107. 2028. 3011. 2003. 2006. 2012.
 3008. 1008. 4106. 3007. 2008. 4112. 4101. 2005. 2001. 2016. 2018. 2019.
 2022. 2013. 2014. 4109. 2029. 2026.]

In [ ]:
import numpy as np

df['NU_IDADE_N'] = df['NU_IDADE_N'].replace(0, np.nan)

In [ ]:
df['NU_IDADE_N'].isna().sum()

np.int64(62)

In [ ]:
#TRABALHAR COM A IDADE

# Criando a variável tipo_idade (primeiro dígito)
import numpy as np

# Aplica a transformação somente onde a idade não é nula
df['tipo_idade'] = df['NU_IDADE_N'].apply(lambda x: str(int(x))[0] if pd.notna(x) else np.nan)


# Tabela de frequência de tipo_idade
print(df['tipo_idade'].value_counts())

tipo_idade
4    151069
3       176
2       107
1        89
Name: count, dtype: int64

In [ ]:
valores_com_1 = df['NU_IDADE_N'].dropna().astype(str)
valores_com_1 = valores_com_1[valores_com_1.str.startswith('1')]
print(valores_com_1.unique())

['1001.0' '1000.0' '1020.0' '1037.0' '1008.0']

In [ ]:
import numpy as np

df['idade'] = df['NU_IDADE_N'].apply(
    lambda x: int(str(int(x))[2:]) if pd.notna(x) else np.nan
).astype('Int64')  # Int64 permite valores nulos

In [ ]:
df['idade'] = df['NU_IDADE_N'].astype(str).str[2:]

In [ ]:
df['idade'] = df['idade'].where(df['tipo_idade'] == "4", 0)

In [ ]:
# Converte para tipo inteiro que aceita nulos
df['idade'] = pd.to_numeric(df['idade'], errors='coerce').astype('Int64')

In [ ]:
df.loc[df['NU_IDADE_N'].isna(), 'idade'] = pd.NA

In [ ]:
print(df['idade'].unique())

<IntegerArray>
[  26,   30,   62,   36,   49,   39,   54,    1,   27,   19,
 ...
   95,    8,   94,   97,   96,   91,    6, <NA>,   99,   98]
Length: 101, dtype: Int64

In [ ]:
# Exibindo a descrição estatística da coluna 'idade' do DataFrame
print(df['idade'].describe())

count     151441.0
mean     38.198883
std      16.219796
min            0.0
25%           25.0
50%           35.0
75%           50.0
max           99.0
Name: idade, dtype: Float64

In [ ]:
df['idade'].isna().sum()

np.int64(62)

In [ ]:
df['faixa_etaria'] = np.select(
    [
        df['idade'].astype(float) < 20,
        (df['idade'].astype(float) >= 20) & (df['idade'].astype(float) < 40),
        (df['idade'].astype(float) >= 40) & (df['idade'].astype(float) < 60),
        df['idade'].astype(float) >= 60
    ],
    [0, 1, 2, 3],
    default=np.nan
)

In [ ]:
df['faixa_etaria'].value_counts(dropna=False)

faixa_etaria
1.0    77842
2.0    43313
3.0    18658
0.0    11628
NaN       62
Name: count, dtype: int64

##Exclusao de variaveis

---

In [ ]:
df.columns

Index(['TP_NOT', 'ID_AGRAVO', 'DT_NOTIFIC', 'NU_ANO', 'SG_UF_NOT',
       'ID_MUNICIP', 'ID_REGIONA', 'DT_DIAG', 'ANO_NASC', 'NU_IDADE_N',
       ...
       'DT_BAC4', 'eleg_eta2', 'eleg_eta3', 'ano_inc_trat', 'ano_encerra',
       'ESCOLA_FAIXA', 'CONTATO_5_15', 'tipo_idade', 'idade', 'faixa_etaria'],
      dtype='object', length=117)

In [ ]:
df = df.drop(columns=[
    'TP_NOT', 'ID_AGRAVO','POP_SAUDE',
    'SG_UF_NOT', 'ID_MUNICIP', 'ID_REGIONA','ANO_NASC',
    'CS_GESTANT', 'DT_DIGITA','HISTOPATOL',
    'ID_RG_RESI', 'ID_PAIS', 'NDUPLIC_N', 'IN_VINCULA',
    'DT_TRANSUS', 'DT_TRANSDM', 'DT_TRANSSM', 'DT_TRANSRM',
    'DT_TRANSRS', 'DT_TRANSSE', 'CS_FLXRET', 'FLXRECEBI', 'MIGRADO_W',
    'ID_OCUPA_N', 'INSTITUCIO','TESTE_TUBE',
    'EXTRAPU1_N', 'EXTRAPU2_N', 'EXTRAPUL_O', 'AGRAVOUTRA', 'AGRAVOUTDE',
    'HIV', 'RIFAMPICIN', 'ISONIAZIDA',
    'ETAMBUTOL', 'ESTREPTOMI', 'PIRAZINAMI', 'ETIONAMIDA', 'OUTRAS',
    'OUTRAS_DES', 'DOENCA_TRA', 'SG_UF_AT',
    'ID_MUNIC_A', 'DT_NOTI_AT', 'SG_UF_2', 'ID_MUNIC_2',
    'BACILOSC_3',  'BACILOSC_5','BACILOSC_1',
    'TRAT_SUPER', 'CULTURA_OU',
    'BACILOSC_6','BAC_APOS_6','BACILOS_E2', 'BACILOSC_O',
    'DT_MUDANCA', 'NU_COMU_EX', 'SITUA_9_M', 'SITUA_12_M',
    'ANT_RETRO',  'TRANSF','TPUNINOT',
    'UF_TRANSF', 'MUN_TRANSF','AGRAVAIDS'
])

In [ ]:
df = df.drop(columns=[
                     'NU_IDADE_N','tipo_idade','DT_NOTIFIC','DT_DIAG','DT_NOTIFIC','TEST_SENSI','TEST_MOLEC',
                     'TEMPO_DIAG_TRAT', 'TEMPO_TRAT_ENC','TEMPO_DIAG_ENC','CS_ESCOL_N','FORMA','TRATAMENTO','NU_CONTATO','idade',
                     'SITUA_ENCE','ID_MN_RESI'
])

In [ ]:
df.columns

Index(['NU_ANO', 'CS_SEXO', 'CS_RACA', 'SG_UF', 'RAIOX_TORA', 'AGRAVALCOO',
       'AGRAVDIABE', 'AGRAVDOENC', 'BACILOSC_E', 'CULTURA_ES', 'DT_INIC_TR',
       'BACILOSC_2', 'BACILOSC_4', 'TRATSUP_AT', 'DT_ENCERRA', 'POP_LIBER',
       'POP_RUA', 'POP_IMIG', 'BENEF_GOV', 'AGRAVDROGA', 'AGRAVTABAC',
       'ANO_BASE', 'cura', 'pop', 'front', 'TEMPO_DIAG_TRAT_14', 'DT_CUL',
       'DT_BAC2', 'DT_BAC4', 'eleg_eta2', 'eleg_eta3', 'ano_inc_trat',
       'ano_encerra', 'ESCOLA_FAIXA', 'CONTATO_5_15', 'faixa_etaria'],
      dtype='object')

In [ ]:
df.shape

(151503, 36)

##• Verificação de valores ausentes (Obrigatório)

In [ ]:
# Verificar a presença de valores nulos
print(df.isnull().sum())

NU_ANO                    0
CS_SEXO                  10
CS_RACA                9325
SG_UF                     0
RAIOX_TORA             1413
AGRAVALCOO             5115
AGRAVDIABE             5384
AGRAVDOENC             5735
BACILOSC_E                0
CULTURA_ES              110
DT_INIC_TR                0
BACILOSC_2            23456
BACILOSC_4            31514
TRATSUP_AT            24010
DT_ENCERRA                0
POP_LIBER              2364
POP_RUA                3083
POP_IMIG               4197
BENEF_GOV             65855
AGRAVDROGA             5640
AGRAVTABAC             5170
ANO_BASE                  0
cura                      0
pop                       7
front                     0
TEMPO_DIAG_TRAT_14        0
DT_CUL                    0
DT_BAC2                   0
DT_BAC4                   0
eleg_eta2                 0
eleg_eta3                 0
ano_inc_trat              0
ano_encerra               0
ESCOLA_FAIXA          35451
CONTATO_5_15           1344
faixa_etaria             62
dtype: int64

In [ ]:
#Converter o desfecho em variável numérica
df.cura = df.cura.astype('Int64')

#Visualização dos novos tipos
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 151503 entries, 0 to 151507
Data columns (total 36 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   NU_ANO              151503 non-null  Int64
 1   CS_SEXO             151493 non-null  float64
 2   CS_RACA             142178 non-null  float64
 3   SG_UF               151503 non-null  int64
 4   RAIOX_TORA          150090 non-null  float64
 5   AGRAVALCOO          146388 non-null  float64
 6   AGRAVDIABE          146119 non-null  float64
 7   AGRAVDOENC          145768 non-null  float64
 8   BACILOSC_E          151503 non-null  float64
 9   CULTURA_ES          151393 non-null  float64
 10  DT_INIC_TR          151503 non-null  datetime64[ns]
 11  BACILOSC_2          128047 non-null  float64
 12  BACILOSC_4          119989 non-null  float64
 13  TRATSUP_AT          127493 non-null  float64
 14  DT_ENCERRA          151503 non-null  datetime64[ns]
 15  POP_LIBER           149139 non-null  float64
 16  POP_RUA             148420 non-null  float64
 17  POP_IMIG            147306 non-null  float64
 18  BENEF_GOV           85648 non-null   float64
 19  AGRAVDROGA          145863 non-null  float64
 20  AGRAVTABAC          146333 non-null  float64
 21  ANO_BASE            151503 non-null  int64
 22  cura                151503 non-null  Int64
 23  pop                 151496 non-null  float64
 24  front               151503 non-null  int64
 25  TEMPO_DIAG_TRAT_14  151503 non-null  float64
 26  DT_CUL              151503 non-null  datetime64[ns]
 27  DT_BAC2             151503 non-null  datetime64[ns]
 28  DT_BAC4             151503 non-null  datetime64[ns]
 29  eleg_eta2           151503 non-null  int64
 30  eleg_eta3           151503 non-null  int64
 31  ano_inc_trat        151503 non-null  int32
 32  ano_encerra         151503 non-null  int32
 33  ESCOLA_FAIXA        116052 non-null  Int64
 34  CONTATO_5_15        150159 non-null  Int64
 35  faixa_etaria        151441 non-null  float64
dtypes: Int64(4), datetime64[ns](5), float64(20), int32(2), int64(5)
memory usage: 42.2 MB

In [ ]:
#converter todas as colunas para letras minusculas
df.columns = df.columns.str.lower()

#verificar novas colunas
df.columns

Index(['nu_ano', 'cs_sexo', 'cs_raca', 'sg_uf', 'raiox_tora', 'agravalcoo',
       'agravdiabe', 'agravdoenc', 'bacilosc_e', 'cultura_es', 'dt_inic_tr',
       'bacilosc_2', 'bacilosc_4', 'tratsup_at', 'dt_encerra', 'pop_liber',
       'pop_rua', 'pop_imig', 'benef_gov', 'agravdroga', 'agravtabac',
       'ano_base', 'cura', 'pop', 'front', 'tempo_diag_trat_14', 'dt_cul',
       'dt_bac2', 'dt_bac4', 'eleg_eta2', 'eleg_eta3', 'ano_inc_trat',
       'ano_encerra', 'escola_faixa', 'contato_5_15', 'faixa_etaria'],
      dtype='object')

In [ ]:
df.shape

(151503, 36)

### Salve o DataFrame no arquivo CSV 'df_br_filtrado_2015_2025.csv'

In [ ]:
# Salve o DataFrame no arquivo CSV
df.to_csv('df_br_filtrado_2015_2025.csv', index=False)

In [ ]:
df.shape

(151503, 36)

In [ ]:
import pandas as pd

# Carregue o arquivo CSV em um DataFrame
df = pd.read_csv('df_br_filtrado_2015_2025.csv')

In [ ]:
inicio = df["dt_encerra"].min()
fim = df["dt_encerra"].max()

print("Começa em:", inicio)
print("Termina em:", fim)

Começa em: 2015-01-07
Termina em: 2025-08-28

In [ ]:
df.loc[df["sg_uf"] == 33, "dt_encerra"].agg(["min", "max"])

min    2015-01-07
max    2025-06-25
Name: dt_encerra, dtype: object

In [ ]:
inicio = df["dt_inic_tr"].min()
fim = df["dt_inic_tr"].max()

print("Começa em:", inicio)
print("Termina em:", fim)

Começa em: 2015-01-01
Termina em: 2025-05-20

In [ ]:
df.loc[df["sg_uf"] == 33, "dt_inic_tr"].agg(["min", "max"])

min    2015-01-02
max    2025-01-31
Name: dt_inic_tr, dtype: object

In [ ]:
df[df["dt_encerra"].notna() & df["dt_inic_tr"].notna()]

,nu_ano,cs_sexo,cs_raca,sg_uf,raiox_tora,agravalcoo,agravdiabe,agravdoenc,bacilosc_e,cultura_es,...,dt_cul,dt_bac2,dt_bac4,eleg_eta2,eleg_eta3,ano_inc_trat,ano_encerra,escola_faixa,contato_5_15,faixa_etaria
0,2015,1.0,4.0,25,4.0,1.0,0.0,0.0,1.0,4.0,...,2015-07-19,2015-07-19,2015-09-19,0,0,2015,2015,NaN,0.0,1.0
1,2015,1.0,4.0,25,1.0,1.0,0.0,0.0,1.0,4.0,...,2015-09-06,2015-09-06,2015-11-06,0,0,2015,2015,0.0,0.0,1.0
2,2015,1.0,4.0,25,1.0,1.0,0.0,0.0,1.0,4.0,...,2016-02-01,2016-02-01,2016-04-01,1,1,2015,2016,NaN,0.0,3.0
3,2015,1.0,4.0,25,1.0,1.0,0.0,0.0,3.0,4.0,...,2016-02-17,2016-02-17,2016-04-17,1,1,2015,2016,0.0,0.0,1.0
4,2015,1.0,1.0,33,1.0,0.0,0.0,0.0,1.0,1.0,...,2015-04-10,2015-04-10,2015-06-10,1,0,2015,2015,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151498,2025,1.0,4.0,35,4.0,0.0,0.0,0.0,1.0,4.0,...,2025-04-05,2025-04-05,2025-06-05,1,1,2025,2025,NaN,2.0,1.0
151499,2023,0.0,4.0,35,1.0,0.0,0.0,0.0,1.0,1.0,...,2024-02-29,2024-02-29,2024-04-30,1,1,2023,2024,0.0,0.0,3.0
151500,2024,1.0,1.0,43,1.0,0.0,1.0,0.0,3.0,3.0,...,2024-03-08,2024-03-08,2024-05-08,1,1,2024,2024,NaN,0.0,3.0
151501,2024,1.0,NaN,35,1.0,1.0,0.0,0.0,1.0,2.0,...,2024-03-06,2024-03-06,2024-05-06,1,1,2024,2024,NaN,0.0,1.0
151502,2024,1.0,4.0,21,1.0,0.0,0.0,0.0,1.0,1.0,...,2024-04-02,2024-04-02,2024-06-02,1,0,2024,2024,1.0,0.0,2.0

#Banco inicio do tratamento

In [ ]:
df1 = df.drop(columns=['cultura_es','bacilosc_2', 'tratsup_at','bacilosc_4',
                       'dt_bac2', 'dt_bac4', 'eleg_eta2', 'eleg_eta3','dt_inic_tr','dt_encerra'

])

In [ ]:
# Salve o DataFrame no arquivo CSV
df1.to_csv('df1_br_filtrado_2015_2025.csv', index=False)

#Banco final do segundo mes de tratamento

In [ ]:
df['eleg_eta2'].value_counts(dropna=False)

eleg_eta2
1    142023
0      9480
Name: count, dtype: int64

In [ ]:
df2 = df.loc[df['eleg_eta2'] == 1].copy()

In [ ]:
df2.shape

(142023, 36)

In [ ]:
df2 = df2.drop(columns=['bacilosc_4',
                       'dt_bac2', 'dt_bac4', 'eleg_eta2', 'eleg_eta3','dt_inic_tr','dt_encerra'

])

In [ ]:
df2.shape

(142023, 29)

In [ ]:
# Salve o DataFrame no arquivo CSV
df2.to_csv('df2_br_filtrado_2015_2025.csv', index=False)

#Banco final do quarto mes de tratamento

In [ ]:
df['eleg_eta3'].value_counts(dropna=False)

eleg_eta3
1    133825
0     17678
Name: count, dtype: int64

In [ ]:
df3 = df.loc[df['eleg_eta3'] == 1].copy()

In [ ]:
df3.shape

(133825, 36)

In [ ]:
df3 = df3.drop(columns=['dt_bac2', 'dt_bac4', 'eleg_eta2', 'eleg_eta3','dt_inic_tr','dt_encerra'

])

In [ ]:
df3.shape

(133825, 30)

In [ ]:
# Salve o DataFrame no arquivo CSV
df3.to_csv('df3_br_filtrado_2015_2025.csv', index=False)

#Bancos por estado

Rio de Janeiro

In [ ]:
dfrj = df[df['sg_uf'] == 33].copy()

In [ ]:
dfrj.to_csv("dfrj.csv", index=False)

In [ ]:
dfrj1 = dfrj.drop(columns=['cultura_es','bacilosc_2', 'tratsup_at','bacilosc_4',
                       'dt_bac2', 'dt_bac4', 'eleg_eta2', 'eleg_eta3','dt_inic_tr','dt_encerra'

])

In [ ]:
dfrj1.shape

(25630, 26)

In [ ]:
dfrj1.to_csv("dfrj1.csv", index=False)

In [ ]:
dfrj['eleg_eta2'].value_counts(dropna=False)

eleg_eta2
1    24537
0     1093
Name: count, dtype: int64

In [ ]:
dfrj2 = dfrj[dfrj['eleg_eta2'] == 1].copy()

In [ ]:
dfrj2.shape

(24537, 36)

In [ ]:
dfrj2 = dfrj2.drop(columns=['bacilosc_4',
                       'dt_bac2', 'dt_bac4', 'eleg_eta2', 'eleg_eta3','dt_inic_tr','dt_encerra'

])

In [ ]:
dfrj2.shape

(24537, 29)

In [ ]:
dfrj2.to_csv("dfrj2.csv", index=False)

In [ ]:
dfrj['eleg_eta3'].value_counts(dropna=False)

eleg_eta3
1    23121
0     2509
Name: count, dtype: int64

In [ ]:
dfrj3 = dfrj[dfrj['eleg_eta3'] == 1].copy()

In [ ]:
dfrj3.shape

(23121, 36)

In [ ]:
dfrj3 = dfrj3.drop(columns=['dt_bac2', 'dt_bac4', 'eleg_eta2', 'eleg_eta3','dt_inic_tr','dt_encerra'

])

In [ ]:
dfrj3.shape

(23121, 30)

In [ ]:
dfrj3.to_csv("dfrj3.csv", index=False)

Todos os estados

In [ ]:
mapa_uf = {
    11: "RO",
    12: "AC",
    13: "AM",
    14: "RR",
    15: "PA",
    16: "AP",
    17: "TO",
    21: "MA",
    22: "PI",
    23: "CE",
    24: "RN",
    25: "PB",
    26: "PE",
    27: "AL",
    28: "SE",
    29: "BA",
    31: "MG",
    32: "ES",
    33: "RJ",
    35: "SP",
    41: "PR",
    42: "SC",
    43: "RS",
    50: "MS",
    51: "MT",
    52: "GO",
    53: "DF"
}

In [ ]:
# Criar arquivos separados por UF
# Usamos um conjunto (set) para controlar quais UFs já processamos
processados = set()

for uf in sorted(df['sg_uf'].unique()):
    uf_int = int(uf)

    # Se já processamos essa UF (no caso do 53 que vem depois do 52), pula
    if uf_int in processados:
        continue

    if uf_int in [52, 53]:
        # Filtra ambos, salva como GO_DF e marca ambos como processados
        df_uf = df[df['sg_uf'].isin([52, 53])].drop(columns=['sg_uf'])
        sigla = "GO_DF"
        processados.update([52, 53])
    else:
        # Processo normal para as outras UFs
        df_uf = df[df['sg_uf'] == uf_int].drop(columns=['sg_uf'])
        sigla = mapa_uf.get(uf_int, f"UF{uf_int}")
        processados.add(uf_int)

    # Caminho padronizado dentro da pasta criada
    nome_arquivo = f"dados{sigla}_tube_2015_2025.csv"
    df_uf.to_csv(nome_arquivo, index=False)

#Inicio do tratamento

In [ ]:
# Criar arquivos separados por UF
# Usamos um conjunto (set) para controlar quais UFs já processamos
processados = set()

for uf in sorted(df1['sg_uf'].unique()):
    uf_int = int(uf)

    # Se já processamos essa UF (no caso do 53 que vem depois do 52), pula
    if uf_int in processados:
        continue

    if uf_int in [52, 53]:
        # Filtra ambos, salva como GO_DF e marca ambos como processados
        df1_uf = df1[df1['sg_uf'].isin([52, 53])].drop(columns=['sg_uf'])
        sigla = "GO_DF"
        processados.update([52, 53])
    else:
        # Processo normal para as outras UFs
        df1_uf = df1[df1['sg_uf'] == uf_int].drop(columns=['sg_uf'])
        sigla = mapa_uf.get(uf_int, f"UF{uf_int}")
        processados.add(uf_int)

    # Caminho padronizado dentro da pasta criada
    nome_arquivo = f"dados{sigla}_tube2_2015_2025.csv"
    df1_uf.to_csv(nome_arquivo, index=False)

#Final do segundo mes de tratamento

In [ ]:
# Criar arquivos separados por UF
# Usamos um conjunto (set) para controlar quais UFs já processamos
processados = set()

for uf in sorted(df2['sg_uf'].unique()):
    uf_int = int(uf)

    # Se já processamos essa UF (no caso do 53 que vem depois do 52), pula
    if uf_int in processados:
        continue

    if uf_int in [52, 53]:
        # Filtra ambos, salva como GO_DF e marca ambos como processados
        df2_uf = df2[df2['sg_uf'].isin([52, 53])].drop(columns=['sg_uf'])
        sigla = "GO_DF"
        processados.update([52, 53])
    else:
        # Processo normal para as outras UFs
        df2_uf = df2[df2['sg_uf'] == uf_int].drop(columns=['sg_uf'])
        sigla = mapa_uf.get(uf_int, f"UF{uf_int}")
        processados.add(uf_int)

    # Caminho padronizado dentro da pasta criada
    nome_arquivo = f"dados{sigla}_tube2_2015_2025.csv"
    df2_uf.to_csv(nome_arquivo, index=False)

#Bancos final do quarto mes de tratamento

In [ ]:
# Criar arquivos separados por UF
# Usamos um conjunto (set) para controlar quais UFs já processamos
processados = set()

for uf in sorted(df3['sg_uf'].unique()):
    uf_int = int(uf)

    # Se já processamos essa UF (no caso do 53 que vem depois do 52), pula
    if uf_int in processados:
        continue

    if uf_int in [52, 53]:
        # Filtra ambos, salva como GO_DF e marca ambos como processados
        df3_uf = df3[df3['sg_uf'].isin([52, 53])].drop(columns=['sg_uf'])
        sigla = "GO_DF"
        processados.update([52, 53])
    else:
        # Processo normal para as outras UFs
        df3_uf = df3[df3['sg_uf'] == uf_int].drop(columns=['sg_uf'])
        sigla = mapa_uf.get(uf_int, f"UF{uf_int}")
        processados.add(uf_int)

    # Caminho padronizado dentro da pasta criada
    nome_arquivo = f"dados{sigla}_tube3_2015_2025.csv"
    df3_uf.to_csv(nome_arquivo, index=False)